### ISSUE TITLE
Option to limit CPU usage

### ISSUE THREAD

**Issue by 4rch0n** [0x90d/videoduplicatefinder#100]
**Environment**
 - OS: Any

**Describe the solution you'd like**
Option to limit CPU usage for more background friendly workflow.

**Comment by Revan654** [comment]
> 
> 
> **Environment**
> 
>     * OS: Any
> 
> 
> **Describe the solution you'd like**
> Option to limit CPU usage for more background friendly workflow.

It doesn't look that will happen, Given the dev recent comment: https://github.com/0x90d/videoduplicatefinder/issues/84

**Comment by 0x90d** [comment]
.NET does not allow something like this especially the APIs I am using.
