### ISSUE TITLE
Please use some highDPI aware font size / Current font size is way too small

### ISSUE THREAD

**Issue by PeterCodar** [0x90d/videoduplicatefinder#102]
**Environment**
 - OS: Windows 10, b2004, fully patched, 64bit, german
 - Resolution: 2560x1440px with 125% font scaling

**Describe the solution you'd like**
As you can see on the comparison (windows explorer) screen, your currently used font size is way to small and hard to read.

<a href="https://www.directupload.net/file/d/5930/an452mc4_png.htm" target="_blank"><img src="https://s12.directupload.net/images/200902/temp/an452mc4.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

Could you please use some bigger font size or use some highDPI aware technique?

Or - if this is too much work - just let the user choose the fontsize for his/her screen size manually.

**Comment by atescula** [comment]
Hello,

I am very interested in a solution for deduplication of my photo/video
collection over 15 years.
It seems I found it thanks to you but I am stuck on how to install it in
Linux.
I am using Arch based Manjaro with KDE desktop environment.

Any help would be appreciated.

Respectfully
Andrei Tescula

Linux addicted person

**Comment by PeterCodar** [comment]
@atescula How should this have anything to do with my issue?

**Comment by Sepulta** [comment]
@atescula This is indeed not relevant to the current issue. You might want to try to use Digikam to find duplicate fotos

**Comment by 0x90d** [comment]
This is already fixed, see below. Either download the source and compile it yourself or  wait until I add a new compiled version under releases for you to download.

![image](https://user-images.githubusercontent.com/46010672/92153338-65a88e00-ee24-11ea-9d93-988a2e43bc7e.png)
