### ISSUE TITLE
No thumbnails running in Linux

### ISSUE THREAD

**Issue by aris200** [0x90d/videoduplicatefinder#104]
**Environment**
 - OS: Zorin lite 15.03

**Describe the bug**
No thumbnails showing up.

**Expected behavior**
Though I followed the instructions 
sudo apt-get update
sudo apt-get install ffmpeg
sudo apt-get install libgdiplus
there were no thumbnails created. After a lot of searching, I did
sudo apt-get install libc6-dev
and everything worked like a charm.
Hope this is helpful to somebody...

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2

**Comment by tonglil** [comment]
Is there a v3 of the app somewhere?

**Comment by vsolina2** [comment]
I think there will be a v3 soon shortly as a number of the source files about 15 hours ago suddenly were updated to v3 and changes have been occurring since

All I can say is welcome back 0x90d and does this explain your absence?
