### ISSUE TITLE
no matches found

### ISSUE THREAD

**Issue by thevetteguy** [0x90d/videoduplicatefinder#105]
Just tried 2.08 .. it does not find any dupes where 2.07 finds 26 dupes with the same settings.  This is in Windows 10.

**Comment by 0x90d** [comment]
What does the log say?

**Comment by obs1dium** [comment]
Same here.  Looks like the percentage difference calculation got broken in 1e2765bcf977a1694e8eddab2fd11030711f93fb.

**Comment by NPastorale** [comment]
I stumbled upon the same issue. Version 2.0.7 finds duplicates but 2.0.8 does not, and does not produce any log output. The db is generated though, but that's about it. Also running on Windows 10.
I tried both the included ffmpeg and ffprobe and the latest version of those, which as of this writing is 4.3.2, it made no difference.

**Comment by mjmatthiesen** [comment]
I'd report the opposite, 207 will find duplicates that are super different. Diff length, res, size, screenshots all diff, audio diff, etc.

208 is more consistent in not finding those.

**Comment by NPastorale** [comment]
@mjmatthiesen how did you manage to make it work? It is not finding any duplicates for me neither on Windows nor on Linux, no matter how high or low I set the similarity percentage

**Comment by mjmatthiesen** [comment]
@NPastorale Honestly mate, just ran it, it worked.

**Comment by vsolina2** [comment]
May I ask which distribution/version of linux your using

**Comment by mjmatthiesen** [comment]
Windows

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
