### ISSUE TITLE
Option to pre-select all files within a choosen directory

### ISSUE THREAD

**Issue by PeterCodar** [0x90d/videoduplicatefinder#106]
**Environment**
 - OS: Windows 10 b2004, 64bit

**Describe the solution you'd like**
It would help a lot to have an option to "Select all files within a specific directory". 
Best way would be to get a file dialog to choose the base directory for pre-selection.

**Example:** 
Your software finds 2 identical files:
```
h:\backup1\Movies\Supermovie.mkv
i:\backup2\Movies\Supermovie.mkv
h:\backup1\Movies\Supermovie2.mkv
i:\backup2\Movies\Supermovie2.mkv
h:\backup1\Movies\Supermovie3.mkv
i:\backup2\Movies\Supermovie3.mkv
```

With the suggested option you can pre-select "all files within` i:\backup2\movies`", check them and delete them all.
Actually, I have to select every single file in this i:\backup2\Movies-directory manually.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
