### ISSUE TITLE
Multi processing to speed up workload

### ISSUE THREAD

**Issue by ehenara** [0x90d/videoduplicatefinder#110]
**Environment**
 - OS: [e.g. Windows / Linux / Any]

**Describe the solution you'd like**
Would be good if we can process multiple videos at the same time in order to allow the application to  utilize the full potential of the CPU & RAM and to complete the workload faster.

Currently the Application only seems to process one file at a time.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
