### ISSUE TITLE
Would be nice to create a tutorial on how you created this, and how to contribute to this

### ISSUE THREAD

**Issue by jeffward01** [0x90d/videoduplicatefinder#112]
**Environment**
 - OS: Windows, Visual Studio 2019 - Development

**Describe the solution you'd like**
This is a very cool application!  BIG BIG thank you for creating this!

Would love to contribute and see how I can help on this, I noticed you don't have any resources or docs on how you built this, or how developers could contribute.

Would be cool to have something (maybe less detailed) like this: https://medium.com/@nicolasdorier/creating-a-cross-platform-desktop-app-in-net-core-part-one-be29079bcc71

I presume you used this as well from your Readme.md: https://avaloniaui.net/

**Doc Request**:
- How you made this a cross platform desktop application
- Libraries / Frameworks that you used
- Dot net core version
- Feature list priority order
- Contribution / Pull Request instructions
- Deployment instructions

**Nice to have:**
- Simple tutorial on how to make a simple change.

Once you have those listed, it should be easy for any developer to jump on!

**Comment by 0x90d** [comment]
Build was explained in readme, I've added some notes about pull requests.
