### ISSUE TITLE
Not Responding while scanning large media library

### ISSUE THREAD

**Issue by jeffward01** [0x90d/videoduplicatefinder#113]
**Environment**
 - OS: Windows 10

**Describe the bug**
I have a very large media library (details below), currently I am only looking for duplicates in my Movie library, which is still very large.

When I 'search / scan' for duplicates, my `vidoduplicatefinder` windows desktop app goes to 'not responding', and stays like this for hours.  I have ran it overnight and it still does not respond.

I included a video of what my resource usage looks like. It appears its 'working', but the UI stays locked and 'is not responding'.

- **Video:** https://streamable.com/munr4r
- **Image:** https://ibb.co/WKtCxcj
- **Library Information:**
~ 1 TB
~ 1800 Movies

Note: I am on my laptop, my media is stored in my UnRaid server which is hosted on my network.  I connect to my Media folder by 'mapping' my media drive from my laptop, to my UnRaid share.

**Expected behavior**
- The UI does not freeze
- User can see progress bar with progress of scan & duplicate matching
- The UI always responds and does not show 'is not responding'

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
