### ISSUE TITLE
GPU Decode

### ISSUE THREAD

**Issue by themostinternet** [0x90d/videoduplicatefinder#114]
Would it be possible to use a GPU to decode the video files and generate thumbnails instead of CPU? I think this functionality already exists in ffmpeg...

**Comment by jeffward01** [comment]
I was literally about to ask the same question! haha, nice timing!

No GPU being used image: https://ibb.co/5hqXHwd

**Comment by smares** [comment]
Does it make sense to use the GPU when you only extract a couple of frames (or by default 1)?

**Comment by HASJ** [comment]
> 
> 
> Does it make sense to use the GPU when you only extract a couple of frames (or by default 1)?

It does. It obviously frees the CPU to do other stuff and this is a trivial task for a GPU since it has dedicated hardware for this, not so much for a CPU.

**Comment by matthewstrasiotto** [comment]
To speak to this - I estimate that enabling this is fairly trivial, it's just not given in settings:
Here is available ffmpeg settings:

https://github.com/0x90d/videoduplicatefinder/blob/c19190196588dd2982e269b28ff23abf78e8ff5e/DuplicateFinderEngine/FFmpegWrapper/FFmpegSettings.cs#L1-L13

Here is where these are initialized:

https://github.com/0x90d/videoduplicatefinder/blob/c19190196588dd2982e269b28ff23abf78e8ff5e/DuplicateFinderEngine/FFmpegWrapper/FFmpegWrapper.cs#L14-L18

Here is where the settings are used as arguments in calling the `ffmpeg` binary

https://github.com/0x90d/videoduplicatefinder/blob/c19190196588dd2982e269b28ff23abf78e8ff5e/DuplicateFinderEngine/FFmpegWrapper/FFmpegWrapper.cs#L35

From [the ffmpeg docs](https://ffmpeg.org/ffmpeg.html#Advanced-Video-options):

> ## 5.6 Advanced Video Options
>
> ...

> ...
> `-hwaccel[:stream_specifier] hwaccel (input,per-stream)`
> 
> Use hardware acceleration to decode the matching stream(s). The allowed values of hwaccel are:
> 
> `none`
>
> Do not use any hardware acceleration (the default).
> 
> `auto`
>
> Automatically select the hardware acceleration method.
>
> ...

> ...
>
> `-hwaccel_device[:stream_specifier] hwaccel_device (input,per-stream)`
> 
> Select a device to use for hardware acceleration.
> 
> This option only makes sense when the `-hwaccel` option is also specified. It can either refer to an existing device created with `-init_hw_device` by name, or it can create a new device as if `‘-init_hw_device’ type:hwaccel_device` were called immediately before.

Whether or not delegating decoding to a GPU will produce significant gains, I couldn't say. At the very least, I highly doubt it could reduce performance.

I will say, when it comes to things that GPUs are good at, GPUs are **very good** at them compared to CPUs.

That said, the magnitude of the improvement is probably upper bound on the amount of overhead in the current mechanism for launching decoding tasks: spawning a new ffmpeg prcoess for each file to process, & waiting for it to finish.

How easily this can improved on, I don't know.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
