### ISSUE TITLE
No similarity between x264 and x265 encodings?

### ISSUE THREAD

**Issue by Samhayne** [0x90d/videoduplicatefinder#115]
I just realized that I never get a duplicate report if one video is encoded in x264 and the other in x265.
To make things more confusing I added two low quality VP9 and ASP encodings... 

As you can see: It’s always the same video but similarities are only detected between videos which use the same codec. (except VP9/ASP which form their own group)

![image](https://user-images.githubusercontent.com/7030482/96787888-d286e000-13f2-11eb-86f1-18b5a29b102d.png)

I never seem to get a log... but here are the exported database entries...

Directory,FileName,Width,Height,FrameRate,BitRate,CodecName,CodecLongName,DurationMinutes,Duration,IsImage,Excluded,Errors
V:\tst\Godzi-Trailer3,Trailer - Godzilla (ASP).mkv,1920,800,24,2044734,mpeg4,MPEG-4 part 2,"2,45",00:02:27,False,False,0
V:\tst\Godzi-Trailer3,Trailer - Godzilla (VP9).mkv,1920,800,24,916842,vp9,Google VP9,"2,45",00:02:27,False,False,0
V:\tst\Godzi-Trailer3,Trailer - Godzilla (x264crf20).mp4,1920,800,24,3743427,h264,H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10,"2,45",00:02:27,False,False,0
V:\tst\Godzi-Trailer3,Trailer - Godzilla (x264crf30).mp4,1920,800,25,942560,h264,H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10,"2,45",00:02:27,False,False,0
V:\tst\Godzi-Trailer3,Trailer - Godzilla (x265).mkv,1920,800,24,0,hevc,H.265 / HEVC (High Efficiency Video Coding),"2,45",00:02:27,False,False,0
V:\tst\Godzi-Trailer3,Trailer - Godzilla (x265).mp4,1920,800,24,3415594,hevc,H.265 / HEVC (High Efficiency Video Coding),"2,45",00:02:27,False,False,0
V:\tst\Godzi-Trailer3,Trailer - Godzilla (x265crf20).mp4,1920,800,24,2620284,hevc,H.265 / HEVC (High Efficiency Video Coding),"2,45",00:02:27,False,False,0

The log also shows the correct stats... while the windows shows very weird values.

Here's a download link for the video files: 
https://www.filehosting.org/file/details/901304/Godzi-Trailer3.7z
Good trash-mail-service if desired for the download: https://dropmail.me/

**Comment by matthewstrasiotto** [comment]
Is this still an issue? If so, could you raise it in my fork, https://github.com/matthewstrasiotto/videoduplicatefinder ? 
Also, the filehost seems to have expired, if you'd be able to reup them :)

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
