### ISSUE TITLE
MacOS Support or at least instructions how to compile

### ISSUE THREAD

**Issue by haleelk** [0x90d/videoduplicatefinder#120]
Could you please provide some instructions how to compile or run that program on MacOS?

**Comment by matthewstrasiotto** [comment]
https://github.com/matthewstrasiotto/videoduplicatefinder/issues/29 I've built my fork for MacOS, and here's how to run it

**Comment by vsolina2** [comment]
It may be to do with versions of macOS I’m on 11.5

It gives the complaint message for every file
After that is done for about 30 files and you may have to restart the process multiple times
you will get the following on start attempts for most of those files. if the folder moves or is updated (I went through this with cognetizen? version


when it finally starts I got this message and am currently installing it

**Comment by vsolina2** [comment]
On MacOS version VDF 2.1 
Finally get everything installed and working with ffmpeg and ffprobe. Its not complaining to much about unsigned developer still needs to be told to open files quite often including while scanning

Result :- no thumbnails however it did detect 100% Duplicate files i.e. name change only did not detect resolution or other changes

Seperate issue if the file is stored on a NTFS drive MacOS likes to make a invisible file that stores file attributes these should be ignored as they create a large number of errors

[matroska,webm @ 0x7fba3100be00] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number
[matroska,webm @ 0x7fba3100be00] EBML header parsing failed
more info on these files

https://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
