### ISSUE TITLE
User Cancelled OneDrive Sync During Scan Causes Timeout Exception Accessing Data

### ISSUE THREAD

**Issue by Barnacules** [0x90d/videoduplicatefinder#123]
1) Select a OneDrive folder that is not synchronized containing video & images
2) Start scanning
3) When video toast pops up on task tray saying "OneDrive is syncing for VideoDuplicateFinder" click "Cancel"
4) Once the sync operation is cancelled VideoDuplicatorFinder will crash timing out

I suspect this may also happen with other cloud based storage where the file synchronizing causes a blocking operation on the file stream until it's ready but it can never become ready because of lack of storage or the sync operation fails or is cancelled.

Hope the screen shots helps you guys fix it, I love the tool! It's amazingballz 🤗

![image](https://user-images.githubusercontent.com/8484226/104869665-6d605f00-58fb-11eb-9825-23cd1d489c69.png)

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
