### ISSUE TITLE
Access Violation on Memory Stream when Scanning Full Drive Containing Steam & X-Plane 11

### ISSUE THREAD

**Issue by Barnacules** [0x90d/videoduplicatefinder#124]
1) Select top level drive containing a Steam install with X-Plane 11 installed (D:\)
2) Start File Scanning
3) Last File Successfully Scanned is [spinning@2x.png] which it finds a duplicate in X-Plane 11 folder

Crash occurred after thousands of duplicates were already found so I don't have more precise reproduction steps unfortunately. When I closed the exception dialog it fired 4 more times with the same exception before the whole process stopped but the program didn't crash? Maybe because of blanket exception handling to stabilize the program so not all work is lost? Thank you.

I suspect this is some kind of multi-threaded race condition where the MemoryStream is being disposed while another thread is still trying to access it for some comparison reasons perhaps. This is just a blind guess though since I don't have the source code up on my screen (sorry, I'm being really lazy right now). I'm sure a debug version with these repro steps should be able to hit the same issue and give you context into which object is being disposed prematurely or accessed when it shouldn't be.

Good luck and I love the tool! 🤗

![image](https://user-images.githubusercontent.com/8484226/104869903-08593900-58fc-11eb-8321-33259f67010a.png)

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
