### ISSUE TITLE
Add option on Windows 10 to replace duplicate with Symbolic Link to Primary

### ISSUE THREAD

**Issue by Barnacules** [0x90d/videoduplicatefinder#125]
- This feature applies to Windows 10 & NTFS specifically

**Request**
I would love a feature that allows me to remove a duplicate and replace it with a symbolically linked file to the primary so you regain the storage back from having multiple duplicates but programs can still access the file in all the locations where it was before you removed it.

This is very useful for game installs like X-Plane 11 where tons of video and image assets are duplicated in various different places (not really sure why) or you have video editing projects where you have multiple solutions that you copied for different stages of editing but the video files are also duplicated in each folder and eat a ton of space but deleting the duplicates would make the solutions in all but one folder fail to load.

If you leave a symbolic link where the duplicate was removed (make it optional obviously) then the program could open the file in either location using the common filesystem API's and it would redirect behind the scenes to the data from the primary file that was left somewhere else (like a shortcut kind of). This means you could literally create 100 copies of a video project with all its assets and only the assets that are different would remain in the folders and the common files would all be replaced with symbolic links back to the original. 

I realize there are some logistics as to figuring out which should be primary or not, etc and if you delete the primary you break all the symbolic links in the file system also but I figure you could add an option so the user has to make these decisions so they are aware of which one is the primary to avoid ever deleting it while they want the others to exist so they don't get confused if they break any of the symbolic links.

This has the potential to save an insane amount of space for users that have multiple installs of games from different platforms like Origin, Steam, etc or duplicating big projects before editing and changing them. Just thinking out loud on this one. I wouldn't be surprised if the Linux file systems also support symbolic linking of some kind but if they don't that could also make this more difficult to do cross platform without some wizardy.

Thanks for making such an awesome program! 🙏

_I'm @barnacules on Twitter_

**Comment by matthewstrasiotto** [comment]
> I wouldn't be surprised if the Linux file systems also support symbolic linking of some kind but if they don't that could also make this more difficult to do cross platform without some wizardy

Linux filesystems can do one better- hard links. Different paths reference the same underlying physicial place on the drive, and the file is only deleted when all references have been.

Besides that, it'd probably still take a degree of platform wrangling to cover the edge cases between the various filesystems, but its not impossible.

If this tool is capable of emitting dup data to structured output, I'd say you'd have good luck parsing that in a script and driving the linking there

**Comment by rockbyo5** [comment]
that feature might actually be reasonably easy to implement. As stated by @matthewstrasiotto , there is the option of hard link (and on top, they actually exist on Windows too! -but they have a different name-). To generate a hardlink, afaik, the only 2 informations needed are the 2 files to link together. I am unsure of how hardlinks work in cases with more than 2 copies but i assume it isn't a problem.
I likely wont get around to do it since i have so many projects, but i might look at the source code and try to add the feature myself, assuming it isnt too time-consuming for me. who knows.  but its definietely a feature which would be amazing!

**Comment by matthewstrasiotto** [comment]
Afaik, hardlinks are the same as tou add further copies

**Comment by rockbyo5** [comment]
> Afaik, hardlinks are the same as tou add further copies
This true in a way but it is too vague a claim. Hardlinks do not count as a duplicate in terms of hard drive usage but they do provide, in the eyes of most software, a "real" copy of the file and as such they function as if the file was "duplicated" (but, as I said above, they dont require more space).
