### ISSUE TITLE
CurrentDispatcher.UnhandledException

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#126]
**Environment**
 - OS: Windows 10 Pro (20H2) 
 -  AMD Ryzen 5 3600, 48.0GB, RTX3080

**Describe the bug**

Fisrt and Second 14TB Hard Disk scanning sucessful.

But CurrentDispatcher.UnhandledException Error message pops up when I scan 3rd 14TB Hard Disk.

This message pops up first. 

![error0](https://user-images.githubusercontent.com/43441443/107459171-ebc9bd00-6b98-11eb-9087-36cc46456eab.jpg)

And this message follows.
![error1](https://user-images.githubusercontent.com/43441443/107459167-ea989000-6b98-11eb-9b09-283c43789bad.jpg)

**Expected behavior**

I have more HDD have to scan.
Please patch this error message.

**Comment by wowkkwow** [comment]
2.0.7 version is O.K, No errors.

But 2.0.8 version shows error messages.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
