### ISSUE TITLE
Inconsistent failure to pick lowest quality (and leave best alone)

### ISSUE THREAD

**Issue by scruffynerf** [0x90d/videoduplicatefinder#127]
**Environment**
 - OS: Linux

**Describe the bug**

Whule the vast majority of auto-selected choices work as expected, I've found it'll pick the wrong file at times.  It'll pick the larger and higher quality file instead.  It's NOT the file(s) themselves.  I did a big batch, and found a half dozen or so mistakes.  I unchecked both/all of them, and then moved/deleted the remaining correctly checked dupes (and cleaned DB), and rescanned again, and it found all of the files in question again.  Clicked on Select Lower Quality, and SOME of the items were now selecting correcting.  However, not all of them.  I then redid the above again, and now out of 3 pairs, 1 was correctly checked this time.  So it's buggy code, not a weird file.  It was picking bigger files, with higher bitrates, over smaller filesizes with lower bitrates.

**Expected behavior**
Always save the best quality, and then select any that aren't that one.

**Comment by scruffynerf** [comment]
In looking at the code, I can't see exactly why it's doing this.  But I think it's related to the order of the checks, including Audio bitrate...  but it's inconsistent... the same two files being compared shouldn't sometimes say pick A and sometimes pick B.

All of these picked the 'wrong' file the first time, and reducing the list to just these, notice how some of this are now correctly picked.

![screen1](https://user-images.githubusercontent.com/21144471/108145157-fbfe0280-7098-11eb-92c2-abe1c539fcd8.png)
![screen2](https://user-images.githubusercontent.com/21144471/108145160-fc969900-7098-11eb-8c07-cfadf3963ba1.png)
![screen3](https://user-images.githubusercontent.com/21144471/108145162-fd2f2f80-7098-11eb-9c0b-a42e1340ff1c.png)
![screen4](https://user-images.githubusercontent.com/21144471/108145165-fd2f2f80-7098-11eb-80b6-e8ac91d001a6.png)
![screen5](https://user-images.githubusercontent.com/21144471/108145168-fdc7c600-7098-11eb-83ed-7082578bce5f.png)

**Comment by scruffynerf** [comment]
adding an OrderByDescending picker would be useful too... since that's 99% of the time what I want, not by smallest, which is the current option.

**Comment by scruffynerf** [comment]
ah, I figured out the issue...

Your logic is:
//Duration first
//resolution next, but only when keep is unchanged
etc

so if something makes the first one in the list the correct choice, but then a later check decides that the second/later is the 'right' one, then it ignores the first was better, and likes the second over the first.  This actually leads to picking a smaller resolution or duration IF the item has a higher bitrate, or even better audio.  Broken logic.

Ideally, you'd check which ever checks you wanted (given the note of allowing user choice here, or all checks), and if and only if all of the checks were better for one item, then would you check the others, otherwise check none, and let the user decide.

**Comment by amiga-500** [comment]
Nice catch!   Sadly, i get a sense the author has abandoned this project :(  I wish your solution was implemented.

**Comment by matthewstrasiotto** [comment]
Possibly related as may innacurately describe dimensions: #137 .

I believe @amiga-500 is right, the author seems to be MIA. I'm considering taking on stewardship of this in my own fork, https://github.com/matthewstrasiotto/videoduplicatefinder

**Comment by sergiotca** [comment]
> Possibly related as may innacurately describe dimensions: #137 .
> 
> I believe @amiga-500 is right, the author seems to be MIA. I'm considering taking on stewardship of this in my own fork, https://github.com/matthewstrasiotto/videoduplicatefinder

@matthewstrasiotto That would be awesome! This project has been in a desperate need of leadership for while now.

**Comment by vsolina2** [comment]
I agree that would be great and kind of you
If you do could the other forks be assimilated as some of them appear to have done some work

**Comment by matthewstrasiotto** [comment]
Sweet - I'll publsih the repo I've been working off of and notify people.
