### ISSUE TITLE
Exception crashes on Parallels VM - Windows 2019 Server hosted on MacOS BigSur

### ISSUE THREAD

**Issue by speedheathenULTRA** [0x90d/videoduplicatefinder#133]
Running VDF latest Windows release and under several VM's or on a Native windows installation I am getting the attached error related to files that are NOT corrupt.

Any ideas?

<img width="1560" alt="Screen Shot 2021-04-22 at 8 32 40 PM" src="https://user-images.githubusercontent.com/77904398/115801219-3726f580-a3aa-11eb-925e-4c8203cec24e.png">

**Comment by Maltragor** [comment]
VDF compares the videos by generating 16x16 greyscale thumbnails. This is done by GetVideoThumbnailAsBitmaps() by executing ffmpeg which should return the 16x16 pixels on StandardOutput.
But for the mentioned file this does not seem to happen, so the timeout exception is thrown.

You could try to call ffmpeg by hand to find out more:
`ffmpeg -hide_banner -y -ss 00:00:30 -i "c:/tmp/MyTestVideo.mp4" -t 1 -f rawvideo -pix_fmt gray -vframes 1 -s 16x16 -`
with -ss [Timestamp] and -i "[The file mentioned in your screenshot]"
(The timestamp of 30 seconds is only an example. I don't know the timestamp VDF used)

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
