### ISSUE TITLE
The program crashes

### ISSUE THREAD

**Issue by obtim** [0x90d/videoduplicatefinder#134]
**Environment**
 - OS: Windows 7 x64

**Describe the bug**
The program crashes when I put more than 580000 .ts files to process. I have archive of a video, in ts format, which consists of chunks. Chunks are in folders that are logically combined. I need to find dublicates.
Screen of folder structure: [https://c.radikal.ru/c09/2105/f8/9e7c14e74bc1.jpg](url)

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
