### ISSUE TITLE
VDF finds more results on Windows 7 than 10

### ISSUE THREAD

**Issue by saucefrog** [0x90d/videoduplicatefinder#135]
**Environment**
 - OS: Windows 7 and 10

**Describe the bug**
I have an external harddrive with more than 10,000 videos. If I use VDF on my Windows 7 computer, it finds a lot more duplicates than on my Windows 10 computer, no matter how I set the percentage.

For example at 90% I get 232 results on W7, on W10 it's three.

**Expected behavior**
VDF on Windows 10 should show the same results and amount of duplicates.

**Comment by Maltragor** [comment]
You could test the following:
Got to your VDF.Windows-x64 directories and rename ScannedFiles.db on both systems.
Set the same number of thumbnails on both systems an start the scan.
=> Are the results still different?

Background:
VDF generates the database file so as not to have to process all videos again. But in my opinion the conditions to decide if the database entry should be used or if the video should be processed again is buggy.
(VDF generates 16x16 pixel greyscale thumbnails to compare the videos.)
The number of thumbnails you select also determines the number of internal generated 16x16 greyscale thumbnails. But the database is not updated if you change the number.
This leads to the following effects:
- If you have no database (e.g. first run) the number of thumbnails determines the number of 16x16 greyscale thumbnails are created and stored in the database. The subsequent search actions for already scanned files only use the database.
So starting with no database and running the first scan with a different number of thumbnails will generate different database entries used for all subsequent searches.
- The number of the thumbnails defines the timestamps where the 16x16 thumbnails are created.
- Thumbnail 1 from video A is compared with thumbnail 1 from video B, 2 with 2, 3 with 3,.. the difference of each thumbnail pair needs to be smaller then the given percentage level. But to be classified as duplicate, the difference of all compared thumbnails must be smaller then the given level.
(-> So the number of thumbnails can have an impact on whether a two videos are classified as duplicate or not)
- If one of the 16x16 thumbnails is too dark in the medium, the complete video is ignored. (And gets a toDark flag in the database so it is not processed again)
- Videos are only compared if the number of 16x16 thumbnails is the same. But if you make the first scan with number X, then change the number an add another search path / add videos to an path / rename / ... the "new" videos are added with the other number Y of thumbnails and wont be compared with the others.

So there are many reasons why VDF will give different results depending on previous scans but independent from the system.
(And in my opinion there should be made some changes how VDF handles the number of thumbnails vs. the condition to reprocess the video vs. the toDark handling)

The other idea would be:
VDF uses ffmpeg to generate the 16x16 greyscale thumbnails.  
Maybe the video decoding differs on the two systems??? I don't know enough of ffmpeg to be able to make a statement about it.
But it would be possible to compare what ffmpeg generates.
The command line would be:
`ffmpeg -hide_banner -y -ss 00:00:30 -i "c:/tmp/MyTestVideo.mp4" -t 1 -f rawvideo -pix_fmt gray -vframes 1 -s 16x16 image.bin` with `-ss [Timestamp]` and `-i "[Your Video File]"`. The result will be written to `image.bin`. This in a raw binary file and you need e.g. a hex editor to view it. (Or you can compare two files by `fc /b image.bin image1.bin`

**Comment by saucefrog** [comment]
My thought too was that something in ffmpeg or its settings is different depending on the operating system. But now that you mention the whole thing with ScannedFiles.db, I might simply delete that file and restart from scratch in hope to get better results.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
