### ISSUE TITLE
File location 

### ISSUE THREAD

**Issue by nachetnnn** [0x90d/videoduplicatefinder#141]
**Environment**
 - OS: Linux

**Describe the solution you'd like**
I'd like to be able to have files I'm comparing to be launched through a video player if I double click them, or at least have the option to open the location of the files directly on the file manager.

**Comment by matthewstrasiotto** [comment]
As far as i know, this feature is working - if you double click an entry it should at least open the containing folder

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
