### ISSUE TITLE
APP CRASH, Windows 2019 Server - FFMPEG? .NET?

### ISSUE THREAD

**Issue by speedheathenULTRA** [0x90d/videoduplicatefinder#143]
Fresh install of Windows 2019 Server with all updates.

Running 2.0.8 version ends up with the error in the screenshot randomly.  Can anyone point me in the right direction please?

<img width="1013" alt="Capture" src="https://user-images.githubusercontent.com/77904398/127255138-af66088f-fc69-425f-a9da-cccdc2a40062.PNG">

**Comment by matthewstrasiotto** [comment]
The issue that triggers this has to do with FFMPEG, but it shouldn't be a showstopper- the program shouldn't panic & crash on failure to extract some thumbnails.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
