### ISSUE TITLE
Feedback on upcoming v3

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#145]
I hope it's ok that I don't create a new issue for every little bug for now. V3 is still in the development process (I guess), so I would rather use this bug report as a collector for various anomalies I stumbled across.

**Environment**
 - OS:  Linux
 - Running and also building under Linux
 - 6.0.100-preview.6.21355.2

**Describe the bugs**
0x90d@2725080
1) Cannot be built under Linux because of:
MainWindowViewModel.cs, line 691
`File.CreateSymbolicLink(dub.ItemInfo.Path, s.ItemInfo.Path);`
-> There is no CreateSymbolicLink in my System.IO.File. And also "s" is not found in the current context
_(My workaround to compile: line commented out)_

2) FFmpeg not found although it is installed
FFToolsUtils.cs, line 56
`return files.Length == 0 ? null : files[0].FullName;`
This seems wrong. The loop iterates through all PATH entries, but the return breaks the loop at the first entry.
I suppose it should be: 
`
if (files.Length > 0)
     return files[0].FullName;
`
The `null` is returned at the end of the function when nothing was found.

3) If FFmpeg is not found the "Cannot find FFmpeg" exception is thrown but not handled at any place, so the program "crashes".
Probably it would be nicer to show a normal error dialog instead and generate a log entry.

4) Context menu -> "Open in Folder" will  
When no row is selected, `currentItem` is `null` and a "System.NullReferenceException" is thrown in `public ReactiveCommand<Unit, Unit> OpenItemInFolderCommand)`
OK, if no debugger is attached you notice nothing of it and the program continues.
Apart from the zero reference thing, is it intentional that not the element on which the right click for the context menu takes place is then opened but the still active element selected at some time earlier?
Based on the comparison with the/a file manager, my expectation would have been to open the item on which the right-click takes place and, if applicable, to make that item the active one as well. 

4) Context menu -> "Groups" -> "Expand/Collapse all"
The functionality does not work deterministically. Often one or two groups keep unchanged, so are not expanded/collapsed.
Playing a while with "Expand/Collapse all" sometimes result in an "System.ArgumentOutOfRangeException" 
<details><summary>Details of ArgumentOutOfRangeException</summary>
<p>
Exception has occurred: CLR/System.ArgumentOutOfRangeException
Eine Ausnahme vom Typ "System.ArgumentOutOfRangeException" ist in System.Private.CoreLib.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.: 'Index must be within the bounds of the List.'
   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei System.Collections.Generic.List`1.Insert(Int32 index, T item)
   bei Avalonia.Controls.DataGrid.InsertDisplayedElement(Int32 slot, Control element, Boolean wasNewlyAdded, Boolean updateSlotInformation) in /_/src/Avalonia.Controls.DataGrid/DataGridRows.cs: Zeile1231
   bei Avalonia.Controls.DataGrid.InsertDisplayedElement(Int32 slot, Boolean updateSlotInformation) in /_/src/Avalonia.Controls.DataGrid/DataGridRows.cs: Zeile1160
   bei Avalonia.Controls.DataGrid.GetExactSlotElementHeight(Int32 slot) in /_/src/Avalonia.Controls.DataGrid/DataGridRows.cs: Zeile1051
   bei Avalonia.Controls.DataGrid.UpdateDisplayedRows(Int32 newFirstDisplayedSlot, Double displayHeight) in /_/src/Avalonia.Controls.DataGrid/DataGridRows.cs: Zeile2046
   bei Avalonia.Controls.DataGrid.UpdateRowGroupVisibility(DataGridRowGroupInfo targetRowGroupInfo, Boolean newIsVisible, Boolean isDisplayed) in /_/src/Avalonia.Controls.DataGrid/DataGridRows.cs: Zeile2678
   bei Avalonia.Controls.DataGrid.OnRowGroupHeaderToggled(DataGridRowGroupHeader groupHeader, Boolean newIsVisibile, Boolean setCurrent) in /_/src/Avalonia.Controls.DataGrid/DataGridRows.cs: Zeile2809
   bei Avalonia.Controls.DataGridRowGroupHeader.ToggleExpandCollapse(Boolean isVisible, Boolean setCurrent) in /_/src/Avalonia.Controls.DataGrid/DataGridRowGroupHeader.cs: Zeile411
   bei Avalonia.Controls.DataGridRowGroupHeader.<OnApplyTemplate>b__59_0(Nullable`1 v) in /_/src/Avalonia.Controls.DataGrid/DataGridRowGroupHeader.cs: Zeile187
   bei System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs: Zeile54
   bei Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs: Zeile148
   bei Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyObservable.cs: Zeile65
   bei Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs: Zeile785
   bei Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs: Zeile701
   bei Avalonia.Controls.Primitives.ToggleButton.set_IsChecked(Nullable`1 value) in /_/src/Avalonia.Controls/Primitives/ToggleButton.cs: Zeile98
   bei VDF.GUI.Utils.TreeHelper.ToggleExpander(DataGrid datagrid, Boolean expand) in /mnt/hgfs/videoduplicatefinder/0x90d_cloned_videoduplicatefinder/VDF.GUI/Utils/TreeHelper.cs: Zeile39
   bei VDF.GUI.ViewModels.MainWindowViewModel.<get_CollapseAllGroupsCommand>b__179_0() in /mnt/hgfs/videoduplicatefinder/0x90d_cloned_videoduplicatefinder/VDF.GUI/ViewModels/MainWindowViewModel.cs: Zeile753
   bei ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveCommand\ReactiveCommand.cs: Zeile110
   bei System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs: Zeile35
   bei System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/ObservableBase.cs: Zeile58
</p>
</details>

**Comment by floydcg** [comment]
pressing F2 to rename no longer works now either, right click and rename works, but it brings up the windows 'save as' box. I was able to make it crash pretty easy trying to rename a file. The old version worked better IMO. Also, not sure if its supposed to be this way or not but you can't change the width of the columns unless you maximize the window, and that only expands them to the right (like the %of dupe gets bigger, but the filename and thumbnail column stay relatively the same as the original size). otherwise the changes and nvidia video acceleration are nice.

**Comment by matthewstrasiotto** [comment]
> The old version worked better IMO.

Sounds like you were using windows previously. The reason the old version worked better was because in v2 there was a Windows only implementation of the GUI, and a separate cross platform implementation, and in v3 theyve been consolidated to the cross platform one only. 

It's an improvement moving forward, but the windows version was slightly more mature than the cross platform version

**Comment by 0x90d** [comment]
> 3\. If FFmpeg is not found the "Cannot find FFmpeg" exception is thrown but not handled at any place, so the program "crashes".
>     Probably it would be nicer to show a normal error dialog instead and generate a log entry.

Fixed

**Comment by 0x90d** [comment]
> 1. Cannot be built under Linux because of:
>    MainWindowViewModel.cs, line 691
>    `File.CreateSymbolicLink(dub.ItemInfo.Path, s.ItemInfo.Path);`
>    -> There is no CreateSymbolicLink in my System.IO.File. And also "s" is not found in the current context

Fixed, you need .NET 6 SDK daily build because `CreateSymbolicLink` is a new API added few days ago.

**Comment by 0x90d** [comment]
> 5\. Context menu -> "Groups" -> "Expand/Collapse all"
>     The functionality does not work deterministically. Often one or two groups keep unchanged, so are not expanded/collapsed.
>     Playing a while with "Expand/Collapse all" sometimes result in an "System.ArgumentOutOfRangeException"

Works fine here with a small list of groups. Could be an Avalonia issue, how many groups do you have?

**Comment by 0x90d** [comment]
> 4\. Context menu -> "Open in Folder" will
>     When no row is selected, `currentItem` is `null` and a "System.NullReferenceException" is thrown in `public ReactiveCommand<Unit, Unit> OpenItemInFolderCommand)`
>     OK, if no debugger is attached you notice nothing of it and the program continues.
>     Apart from the zero reference thing, is it intentional that not the element on which the right click for the context menu takes place is then opened but the still active element selected at some time earlier?
>     Based on the comparison with the/a file manager, my expectation would have been to open the item on which the right-click takes place and, if applicable, to make that item the active one as well.

Fixed. Selection behavior is handled by Avalonia. I agree with you but this should be "fixed" by Avalonia. You would need to report it on their repo.

**Comment by Maltragor** [comment]
>(5) Works fine here with a small list of groups. Could be an Avalonia issue, how many groups do you have?
Only a small set of videos and images. 19 Files, 6-8 duplicate Groups.
I can play around with it when I get a chance, because the debugger had stopped at an unhelpful place and there was so much Avalonia in the trace, which spontaneously didn't help me narrow it down either, I stopped searching last time.

**Comment by 0x90d** [comment]
> 2\. FFmpeg not found although it is installed
>     FFToolsUtils.cs, line 56
>     `return files.Length == 0 ? null : files[0].FullName;`
>     This seems wrong. The loop iterates through all PATH entries, but the return breaks the loop at the first entry.
>     I suppose it should be:
>     `if (files.Length > 0) return files[0].FullName;`
>     The `null` is returned at the end of the function when nothing was found.

Good catch, thanks. Fixed.

**Comment by Maltragor** [comment]
> 2. FFmpeg not found although it is installed

Please also take into account the wildcard issue mentioned in the already closed  #147:  
`var files = new DirectoryInfo(path).GetFiles(tool == FFTool.FFmpeg ? $"{FFmpegExecutableName}*" : $"{FFprobeExecutableName}*",`

As in the case of @wallace11 this e.g returned "ffmpegthumbnailer" as result.
My assumption was that your idea behind the PATH search part is the general fallback if the OS specific search does not provide a result. An so e.g. for windows the wildcard is for the ".exe" extension.
But in this case the star wildcard without any subsequent testing would be just too general.
(As I don't know whether the ".exe" was actually the idea and because I don't know OSX world I had refrained from making more concrete proposals)

**Comment by Maltragor** [comment]
6. DirectoryNotFoundException if not all specified directories exist
 -> FileUtils, GetFilesRecursive()  `var files = Directory.EnumerateFiles(initial, "*", enumerationOptions)...`

This could e.g. happen if you have your Videos on an USB drive, a disk not mounted by default or only moved/renamed one of the configured directories and start the search.

**Comment by 0x90d** [comment]
Can you please create a new issue for every bug instead of posting everything into one large discussion? Thank you

**Comment by Maltragor** [comment]
Ok, I can do it if you prefer.

My motivation behind the collection-issue was to quickly list here the kind of mini-bugs that tend to be fixable by changing a line. So the bug report itself is already longer than the fix.
Then I thought initial... should I really start spamming issues a few hours after his commit to a not released version^^
Especially since I didn't know how you would react to it after you rigorously closed everything to v2, including things that are still in v3. And even at least one, Issue, so the long "How to open the software on Linux? (#129)" was completely deleted. (Why actually?)

But as I said, if/as you obviously prefer that organization-wise, I'll not do such a widely scattered collector in the future then.
