### ISSUE TITLE
Recognize horizontally flipped videos/Images as duplicate 

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#148]
**Environment**
 - OS: Any

**Describe the solution you'd like**
In a certain common domain where a large number of videos are offered (which I won't go into in detail here), it often happens that videos are flipped horizontally.

In order to recognize these as duplicates regardless of whether the scene used as a thumbnail happens to be sufficiently symmetrical, it would be good if VDF compared the grayscale thumbnails with each other in horizontally flipped variants as well. (Probably as a configurable option, since this will increase the scan time).

**Comment by Maltragor** [comment]
up-for-grabs:

I had already thought about it, but then I wasn't sure where to put it in, how much value you put on optimization, and of course I didn't know if you would be interested in integrating/adopting something like that.

How about creating the mirrored variant in ScanForDuplicates in the outer loop for entry and then making a second call with GrayBytesUtils.PercentageDifference(entry_flipped.grayBytes[j], compItem.grayBytes![j]);?

From an optimization point of view, on the other hand, there might be a small advantage in extending PercentageDifference so that three images are passed directly,...
And in principle you could of course also store the mirrored variant in the .db file to not always have to recalculate it. For mirroring itself there are surely more or less performant approaches.
Since you have implemented three variants in PercentageDifference on the one hand, but on the other hand generate e.g. the colored thumbnails by creating files as an intermediate step and also calling ffmpeg multiple times for the individual timestamps per file is certainly not the most performant approach, I could not estimate how important the degree of optimization is to you at which point.

Speaking of which: Why are you actually creating the colored thumbnails as a file? Purely for converting to an Avalonia image, a MemoryStream would do, right? - JoinImages:
```c#
using (MemoryStream memory = new MemoryStream())
{
      img.Save(memory, img.RawFormat);
      memory.Position = 0;
      return new Avalonia.Media.Imaging.Bitmap(memory);
}
```

Since the width of the image is necessary for mirroring, but I think it only occurs somewhere as a ffmpeg parameter (16x16) - should it be introduced somewhere globally as a constant?

**Comment by 0x90d** [comment]
Performance is always good. If you believe if you can make something faster without any drawbacks go ahead and make a PR.

**Comment by Maltragor** [comment]
> If you believe if you can make something faster without any drawbacks

That's why I mentioned the coloured thumbnails over files.
If you need the files fore something else in future e.g. a "create html file" it would be a big drawback not to create them. But I don't know this, so I asked and mentioned the conversion using a memory stream.

I didn't bring up the performance topic to criticize you, if that's how it came across, and I didn't claim that I had a better solution spontaneously, for example with regard to ffmpeg. It was at the point more the relation that if you use multiple thumbnails, their creation times quickly scratched at the second mark. And one calls here just a command line program and that several times for the same file. And on the other side I had seen that for the comparison of the 16x16 bytes even three comparison variants exist although one lies here temporally anyway in another order of magnitude.

> go ahead and make a PR

And this is the other reason for my last post.
To get a feeling for the boundary conditions of the PR.
I use git but don't work with github and have never created pull requests. VDF is the first project where I came in contact with C#. (I am more at home on the embedded microcontroller side)
So this is the reason why I tried to coordinate a little at the beginning and to assess whether it is purposeful to tackle this.
