### ISSUE TITLE
ffmpeg: other / auto hwaccel

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#164]
**Environment**
 - OS: Any

**Describe the solution you'd like**
You decided add a configuration option adding the cuda acceleration. But why only cuda?

hwaccel supports also the automatic detection:
https://ffmpeg.org/ffmpeg.html
> -hwaccel[:stream_specifier] hwaccel (input,per-stream)
    auto:  Automatically select the hardware acceleration method.

Is there a reason why you have decided against the automatic recognition?
(On my system: Linux, Intel Graphic, auto works and selects vaapi)

**Comment by 0x90d** [comment]
Automatic detection didn't worked on my system. I thought about making this customizable along with #118

**Comment by speedheathenULTRA** [comment]
I still haven't even been able to make any of your versions work in either macOS or windows. The farthest I've got was with Windows but even after a full scan that I know had dupes it's not showing anything for results, nada. Zip, zilch. Side-bar to --- I would love to use this and I TOTALLY AGREE WITH @Maltragor on his comment to allow an option to add you own FFPMEG commands. Some people have very complex and unique systems for encoding and decoding video. Especially, live. FFMPEG is the native language to make movies do anything we want them to do, essentially.
