### ISSUE TITLE
V3 - Make 'Search Directories" and 'Exclude Directories' resizeable\scrollable

### ISSUE THREAD

**Issue by bobsage123** [0x90d/videoduplicatefinder#165]
**Environment**
Windows

**Describe the solution you'd like**
After adding 5-10 locations to either, these windows keep getting bigger and bigger until it goes off the bottom of the screen, covering the results section on the bottom as well. There's no way to resize these windows or scroll as far as I was able to figure out.

**Comment by Maltragor** [comment]
Bug in MainWindow.xaml, i wanted to create a PR yesterday together with some other scaling adjustments, but then didn't get around to it... just like today.

https://github.com/0x90d/videoduplicatefinder/blob/fd02535069c4ddea96a56d18e4c670fcc4e493fa/VDF.GUI/Views/MainWindow.xaml#L308-L311

`Height="70`
as it is also with the blacklist.

But the spacing between the Listbox items is quite large. Is there a way to reduce it?

**Comment by Maltragor** [comment]
Whereas I just see that you also have the problem with the Exclude list.
I had not tried the Exclude list, but with the Include list it had worked for me (Linux) to specify the Height instead of the MaxHeight, just analogous to the Exclude list.
_(To late to test it this night again...)_

**Comment by bobsage123** [comment]
> Whereas I just see that you also have the problem with the Exclude list.
> I had not tried the Exclude list, but with the Include list it had worked for me (Linux) to specify the Height instead of the MaxHeight, just analogous to the Exclude list.
> _(To late to test it this night again...)_

I actually did not try the exclude list either, just assumed it worked the same way.
