### ISSUE TITLE
Using CUDA crash the computer and make it reboot

### ISSUE THREAD

**Issue by yami-no-tusbas** [0x90d/videoduplicatefinder#166]
**Environment**
 - OS: Windows 11 (build : 22000.132)
 - GPU : RTX2060

**Describe the bug**
Launch the app, check GPU acceleration, and enjoy random crash. Tried with only  you app oppen after cold boot, crash too.

**Expected behavior**
Not crash my computer, just the app and log the events.

**Comment by 0x90d** [comment]
If it crashes then because of ffmpeg (if its a bug report it to them) or because of your computer. If you enable it in VDF all it does is passing a single argument to ffmpeg.
