### ISSUE TITLE
Add commit number to 3.x

### ISSUE THREAD

**Issue by yami-no-tusbas** [0x90d/videoduplicatefinder#172]
**Environment**
 - OS: Any

**Describe the solution you'd like**
Add the last commit of a version before it was built into the title or the logs so we know if there is a more recent one before downloading the archive.

For now I don't know if there is a new version since 2 days ago, the download page for 3.x indicate the same commit, so maybe it is a new one, maybe not, how do I know ?

**Comment by 0x90d** [comment]
Fixed, please note it's a little bit messy. Probably have to wait for https://github.com/softprops/action-gh-release/pull/145 gets merged.
