### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by yami-no-tusbas** [0x90d/videoduplicatefinder#173]
**Environment**
 - OS: Any

**Describe the solution you'd like**
The log for this version 3.x are a bit too useless. We don't know what the application is doing, how much it has done, when a task run we know nothing about the task except for what is in the corner of the window, and even that is pretty useless since it does not seem to be alphabetical or anything.

So here some suggestions : 
- Add the numer of file found after building the file list.
- Use the log to log how much progress is done, i know there is a little thing on the bottom left, but it's not a number, a percentage would be more usefull. (and log something like : " file x of $total gathered")
- If there is an error, report it, even a ffmpeg one (format unknow, video corrupted, etc) so the user know there is a file that need her/his attention.

**Comment by Maltragor** [comment]
> If there is an error, report it, even a ffmpeg one (format unknow, video corrupted, etc) so the user know there is a file that need her/his attention.

Yes, this is a feature I also miss.
There are several reasons why files could be skipped and if you don't know the background you have no Idea that it happens and which files are effected.
- If the Thumbnails could not be created
- If the Media Info could not be retrieved
- If the video frame used for comparison is "to dark"
- All files with an extension not listed in the extension list of VDF
- ? Any more? I don't know at the moment.  
Reason 1-3 cause VDF to add an corresponding flag in the database. Based of current features you could export the database as json and look at the flags. But this would be not so easy if you have thousands of files in the database without using an extra tool. And there can be more files in the database then files you compared in the last scan.
