### ISSUE TITLE
Is it possible to display file creation date on the results please?

### ISSUE THREAD

**Issue by reddyshyam** [0x90d/videoduplicatefinder#175]
At times this helps to decide which file to keep as the older one could be original though the newer one could be better resolution. I know we can sort but displaying helps with default settings.

**Comment by Maltragor** [comment]
Where would be an accepted place for it?
- Adding a 4th row
- Adding a new column
- Using the similarity column
- ...?

Since none of the variants is ideal at first glance, this should probably be clarified first.

**Comment by reddyshyam** [comment]
> Where would be an accepted place for it?
> 
> * Adding a 4th row
> * Adding a new column
> * Using the similarity column
> * ...?
> 
> Since none of the variants is ideal at first glance, this should probably be clarified first.

Hi @Maltragor, thanks for looking it. Ideal, it would be 4th row of 'Duration/Type/Resolution/Size' column. Since it shows the stats of the file, would make sense date also is listed here. 

So the column header would show up as below

**Duration/Type
Resolution
Size
Date**

Even more so if user given flexibility of selecting the values to display in settings somewhere would be terrific! Users can then, select the values to be displayed as per their requirement.

Just a suggestion though. :)

**Comment by Maltragor** [comment]
Adding it as new row could look like this:

![VDF_CreationDate_V1](https://user-images.githubusercontent.com/36803696/130802441-c1e69b25-decc-42a1-8d8e-035f02d88c21.png)

- In the example the date is auto formatted by using format specifier "g". It probably would look different depending on system language settings so it could be even longer if AM/PM is added. The other option would be to set a fixed short language independent format like "yy/MM/dd hh:mm"  -> "20/05/30 16:28" but probably someone would get confused where to find the year, month and day^^. I personally do not care about the format in the end.
- The second question would be the colour. Is the date neutral or is it better / worse when it is older. -> white vs. green / ...?

> Even more so if user given flexibility of selecting the values to display in settings somewhere would be terrific! 

Yes, but I at least won't implement that, as I'm not familiar enough with the UI framework used for VDF.

**Comment by reddyshyam** [comment]
> Adding it as new row could look like this:
> 
> ![VDF_CreationDate_V1](https://user-images.githubusercontent.com/36803696/130802441-c1e69b25-decc-42a1-8d8e-035f02d88c21.png)
> 
> * In the example the date is auto formatted by using format specifier "g". It probably would look different depending on system language settings so it could be even longer if AM/PM is added. The other option would be to set a fixed short language independent format like "yy/MM/dd hh:mm"  -> "20/05/30 16:28" but probably someone would get confused where to find the year, month and day^^. I personally do not care about the format in the end.

Awesome @Maltragor. Just what I wanted. Thanks a ton! 👏 

Regarding your question, short date would be just fine please if possible in system locale. 

> * The second question would be the colour. Is the date neutral or is it better / worse when it is older. -> white vs. green / ...?

Same as other values, green and red please. 
> 
> > Even more so if user given flexibility of selecting the values to display in settings somewhere would be terrific!
> 
> Yes, but I at least won't implement that, as I'm not familiar enough with the UI framework used for VDF.

Absolutely! Better not touch things we are not comfortable with. :)

**Comment by 0x90d** [comment]
@Maltragor I would not add a color to the date because VDF obviously cannot know what is better. Same for audio format. If the date really matters the user can compare it himself or use the filter function. I'm fine with adding it as row because I don't like if I need to scroll horizontal (too many columns) and vertical. If you want to make a PR you're welcome 👍

**Comment by reddyshyam** [comment]
> @Maltragor I would not add a color to the date because VDF obviously cannot know what is better. Same for audio format. If the date really matters the user can compare it himself or use the filter function. I'm fine with adding it as row because I don't like if I need to scroll horizontal (too many columns) and vertical. If you want to make a PR you're welcome 👍

Thanks @0x90d. I agree with you. I guess White will keep it nuetral and should be good enough.

**Comment by reddyshyam** [comment]
Thanks @Maltragor and @0x90d for this feature. 🙏👏 It is a great help to me. :)

Apologies for not replying earlier, I wasn't around.
