### ISSUE TITLE
Linux: CoreUtils.CurrentFolder changed to folder where only root has write access

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#178]
**Environment**
 - OS: Linux

**Describe the bug**
In 34afcc1c5e033195d675aa0900b72ff80710a123 CoreUtils.CurrentFolder was changed from `typeof(CoreUtils).Assembly.Location` to `Environment.ProcessPath`.
At least on my system the new path is "/usr/share/dotnet/". This seems to be no good place to store temporary application specific files^^. And only root has write access.

What was the expected place CurrentFolder should be on linux?
Should it be only an alternative way to get the same directory?
_(If so, sorry I have no suggestion what would be the "best" way to get the directory)_

Options for other locations would be:
For temporary only files, `Path.GetTempPath()` or `Path.GetTempFileName()`.
For the settings an the database file if not using the application directory, `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)`.

**Comment by 0x90d** [comment]
In this case it's a .NET bug, please report it here: https://github.com/dotnet/runtime/issues

**Comment by Maltragor** [comment]
FYI: 

OK, I have found out the reason.

Environment.ProcessPath() -> Returns the path of the executable that started the currently executing process.
And my Visual Studio Code runs the VDF.GUI.dll what probably means executing `dotnet VDF.GUI.dll`.
=> So the 'executable that started the process' was dotnet...
