### ISSUE TITLE
VDF.GUI.dll reported as trojan by windows defender

### ISSUE THREAD

**Issue by yami-no-tusbas** [0x90d/videoduplicatefinder#179]
**Environment**
 - OS: Windows 11
 - build : 8c9c30e

**Describe the bug**
while extracting the archive i got : 
![image](https://user-images.githubusercontent.com/3921598/130319540-103dfc5c-7ae8-4a4d-b602-c7f4c53b2412.png)

**Expected behavior**
Not trigger my AV ?

**Comment by 0x90d** [comment]
Report false positive to MS. I am not responsible for their shitty detection algorithms. If you dont trust it, download source and compile it yourself. Builds are auto generated.
