### ISSUE TITLE
Renaming loss of function from v2 to v3

### ISSUE THREAD

**Issue by bobsage123** [0x90d/videoduplicatefinder#180]
Windows
 - OS: [e.g. Windows / Linux / Any]

In v2 if you go to rename a file, it will nicely bring up the full filename and you can edit it, hit save, and the new name will appear in the results list. In v3, it makes you manually find the file, and when you do, the new name does not update in the list. Is it possible to revert back the more convenient behavior that is in v2 or is this not possible with this new codeset?

**Comment by 0x90d** [comment]
The current behavior is just a place holder:
https://github.com/0x90d/videoduplicatefinder/blob/95c1c84772603a8a06996979c9ce601fcf6aa119/VDF.GUI/ViewModels/MainWindowViewModel.cs#L479

**Comment by 0x90d** [comment]
Added by @Maltragor
