### ISSUE TITLE
Additional Graphic Acceleration with AMD GPU

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#188]
I have AMD 6900xt.

I hope VDF can use a AMD GPU Acceleration.

**Comment by Maltragor** [comment]
VDF uses ffmpeg to generate the thumbnails. / to compare videos.
The hardware acceleration you select is passed as `-hwaccel` parameter to ffmpeg.

_If you select "Extended FFTools Logging" in the settings dialog and start a search with a not working acceleration mode the complete ffmpeg command line is output in the logging window._

So if hardware acceleration for your GPU is supported by ffmpeg and you find out the the parameters to activate it, then it would at least be technically possible that VDF can use it.

**Comment by 0x90d** [comment]
@Maltragor explained it. Here you can see the status of ffmpeg hardware support: [http://trac.ffmpeg.org/wiki/HWAccelIntro](http://trac.ffmpeg.org/wiki/HWAccelIntro)
