### ISSUE TITLE
"Open In Folder" does not obtain focus of the selected item

### ISSUE THREAD

**Issue by CrendKing** [0x90d/videoduplicatefinder#193]
**Environment**
 - OS: Windows

**Describe the bug**
Suppose I have two sets of dups. Set 1 are from folder A. Set 2 are from folder B. First left click either item in set 1. Then, directly right click either item in set 2 and select "Open In Folder". Observe that folder A is opened.

However, if I first left click the set 2 item then right click, folder B is opened as expected.

**Expected behavior**
Folder B should open. Right clicking item in Windows should obtain focus for that item.

**Comment by 0x90d** [comment]
It (was) an Avalonia bug. Wait until they released a new version and it gets updated in VDF, see https://github.com/AvaloniaUI/Avalonia/pull/6394
