### ISSUE TITLE
Can I use this repo to detect in the same video, the replayed part?

### ISSUE THREAD

**Issue by zydjohnHotmail** [0x90d/videoduplicatefinder#196]
**Environment**
-OS: Windows 10

**Describe the solution you'd like**
Hello:
I have one question: can I use this repo to detect the replayed part of the video?
For example, like in a soccer game video, let’s say there is only one goal scored for the whole game. Usually, the part of goal being scored will be played at least 3 times.  The first time, it is played in normal speed, but the second and third time, usually the underlying part of the video will be played in slow motion.  The part being replayed is not very long, about 10 seconds to 20 seconds.
I want to know if I can use this repo to catch the part being replayed a few time.

**Comment by 0x90d** [comment]
No, VDF takes thumbnails on X percent of a video file and compare it against the same X percent of another video file. If you have a soccer video of the whole match and two files with replays of the goal in slow motion, the thumbnails of all 3 videos at lets say 50% of each will be completely different.
