### ISSUE TITLE
Scanning profile save and load

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#198]
It would be good if VDF had a scanning folder and settings profile save and load.

**Comment by gtTracy** [comment]
Just for clarity, are you asking:

1) To save all selections in the Settings tab to a named file (for instance, MySettings.xml), so that you can have multiple configurations (MySettings.xml, YourSettings.xml, etc), and be able to load and save such files

2) Something else?

**Comment by wowkkwow** [comment]
I mean 1 and also the last result list and thumbnails include.

**Comment by 0x90d** [comment]
> I mean 1 and also the last result list and thumbnails include.

You can create a copy of VDF for this.

**Comment by gtTracy** [comment]
@wowkkwow One suggestion. The settings for the current session are stored in settings.xml. To have custom settings for a run, the best workaround I can give you is to set everything up the way you want it in Settings, then exit the program (thus saving the current settings to settings.xml). Then, go copy settings.xml to a new file (MySettings.xml). Then you can go back into the program and change everything to the way you want it for another profile, then exit, and copy settings.xml to a new file (MyOtherSettings.xml). Do this for each way you want to have things configured. Then you can create a shell script (or batch file in Windows) to copy your custom settings (MySettings.xml) to settings.xml before starting the program. It's kind of a kludge, but it will work for the profile settings (including which drives and folders get scanned),

**Comment by wowkkwow** [comment]
Now I'm doing just you write. I suggest this for more easy to others.
