### ISSUE TITLE
Folder structure cleanup, ideas

### ISSUE THREAD

**Issue by naxolotl** [0x90d/videoduplicatefinder#20]
.net core simply does not support it at the moment, and the only thing that kind of looks like it could work (additionalProbingPaths in runtimeconf.json) is tailored to the nuget folder structure.

MS is planning a to add a single-exe option, (see https://github.com/dotnet/coreclr/issues/20287) which is shaping up to become the most boneheaded implementation one could think of. selfextracting zip into a temp folder basically. (especially since the same thing has been built a thousand times already, e.g. https://github.com/dgiagio/warp)

there is also CoreRT, which can build a single native executable, but is not ideal
 - WPF support is not planned
 - Avalonia support is planned, but work in progress (mostly this: https://github.com/dotnet/corert/issues/5011)
 - no x86 support, but seriously, who cares
 - works already with VDF.Console: https://github.com/naxolotl/videoduplicatefinder/tree/test_full_native, 13MB exe

**Comment by 0x90d** [comment]
Honestly I prefer MS to just add all the runtime libraries into one single folder called "runtime" or similar instead of having the developers dealing with that problem. I'm pretty much sure once .NET Core 3 releases there will be sooner or later such an option when more desktop application uses it.

As of now I don't see any good existing solution for this problem for this project but leaving the issue open to discuss and update when there have been changes to .NET Core.

**Comment by Revan654** [comment]
You could Target .netFrameWork on Windows Side. Since .net comes Pre-installed on Windows. That would reduce all those files.

In the Mean time just do This:

<img width="855" alt="untitled" src="https://user-images.githubusercontent.com/38091898/51500109-e3786c80-1d9a-11e9-9306-315f30fbb31a.png">

**Comment by 0x90d** [comment]
The app currently relies on .NET Core 3.0 which is in alpha thus it's not pre-installed. And I personally prefer to have the app runs everywhere without bothering about missing frameworks / dependencies over having too anyfiles in a folder. 

Having too many files is just cosmetic and can be solved by creating a shortcut where it crashes or doesn't show up without any clear information for the user is a major problem.

**Comment by Revan654** [comment]
> 
> 
> The app currently relies on .NET Core 3.0 which is in alpha thus it's not pre-installed. And I personally prefer to have the app runs everywhere without bothering about missing frameworks / dependencies over having too anyfiles in a folder.
> 
> Having too many files is just cosmetic and can be solved by creating a shortcut where it crashes or doesn't show up without any clear information for the user is a major problem.

Don't you have Catch Code and pre-checks? Meaning if dll is missing it will throw out a error box and tell you exactly what is missing and then close the program. For example My one program if c++ runtime is missing the program will slightly load up telling you it's is missing and then send you to the link to for the file.

Or maybe that's something that can only be done on WinForm side. I always found WPF strange and a bit messy.

**Comment by 0x90d** [comment]
Notice: Possible solution may be patching the app hoster executable: https://github.com/dotnet/core-setup/issues/5120 but there is no guarantee it will work in the future.

**Comment by liesauer** [comment]
i think this tool is the right one for you，[NetCoreBeauty](https://github.com/nulastudio/NetCoreBeauty), it moves a .NET Core app runtime components and dependencies into a sub-directory and make it beauty.

**Comment by Revan654** [comment]
> 
> 
> i think this tool is the right one for you，[NetCoreBeauty](https://github.com/nulastudio/NetCoreBeauty), it moves a .NET Core app runtime components and dependencies into a sub-directory and make it beauty.

Fody would be a better options since all files are added to the Exe rather then moving them to another Location.

Fody is amazing piece of Software with dozens of addons Which can Help Coding.

**Comment by liesauer** [comment]
> > i think this tool is the right one for you，[NetCoreBeauty](https://github.com/nulastudio/NetCoreBeauty), it moves a .NET Core app runtime components and dependencies into a sub-directory and make it beauty.
> 
> Fody would be a better options since all files are added to the Exe rather then moving them to another Location.
> 
> Fody is amazing piece of Software with dozens of addons Which can Help Coding.

i have tried Fody, and it damaged my app, i have talked to the developer but we have no idea why.

**Comment by 0x90d** [comment]
The only reliable way would be publishing as single file executable, closing with reference to #161
