### ISSUE TITLE
Settings: Load From File dialog - unhandled Cancel action

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#200]
**Environment**
 - OS: Linux

**Describe the bug**
https://github.com/0x90d/videoduplicatefinder/blob/13c2d40f17997278148c11c2be92921ea42ecc56/VDF.GUI/ViewModels/MainWindowVM.cs#L789
If the Settings: Load From File dialog is canceled, OpenFileDialog returns `null`. 
The case is not yet considered -> Exception, VDF is terminated.

**Comment by 0x90d** [comment]
Does it? On Windows it returns an empty string array 👀

**Comment by Maltragor** [comment]
Tested on Linux Mint 20 Ulyana.
I just wanted to click on the new buttons to see what happens... and since there was nothing to load, I clicked cancel. ... and got a ReactiveUI.UnhandledErrorException. 
When writing the issue I already assumed that the behavior could be system dependent and added the initially removed OS section again. :-)

**Comment by Maltragor** [comment]
There is another OpenFileDialog in ImportScanResultsIncludingThumbnails with `if (paths.Length == 0) return;`
No problem at the moment, because ImportScanResultsIncludingThumbnails is not used to open the dialog, but may be in future use.
