### ISSUE TITLE
Native ffmpeg bugs

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#201]
**Environment**
 - OS: Linux  (not yet tested under windows)

**Describe the bug**
- Path detection and handling does not consider Linux
- Size(100, -1) not supported by VideoFrameConverter
- Thumbnail pixel format used for VideoFrameConverter does not match the bitmap pixel format  

**Details (intermediate result)**

After setting `ffmpeg.RootPath = "/usr/lib/x86_64-linux-gnu/"; ` and removing the `avcodec-58.dll` check, VideoStreamDecoder() could be called without errors.
(This is the path where all ffmpeg dependencies e.g. libavcodec.so.58 are installed on my system. Of course this is no final solution. )

Size(100, -1): The -1 is not supported by `VideoFrameConverter()`. `sws_getContext()` returns `null`. So I added 
```
if  (_destinationSize.Height == -1)
	_destinationSize.Height = System.Convert.ToInt32(sourceSize.Height * ((double)destinationSize.Width / (double)sourceSize.Width));
```
And used `_destinationSize.Height` everywhere in VideoFrameConverter.cs instead of the original `destinationSize.Height`.

The pixel format issue is a bit strange.
![grafik](https://user-images.githubusercontent.com/36803696/134095019-9ec009e7-4fda-4d1e-b75b-8b5a923beef3.png)
If I use AV_PIX_FMT_BGRA (32 Bit per pixel) instead of AV_PIX_FMT_BGR24 in 
 `AVPixelFormat destinationPixelFormat = isGrayByte ? AVPixelFormat.AV_PIX_FMT_GRAY8 : AVPixelFormat.AV_PIX_FMT_BGRA;//AV_PIX_FMT_BGR24;` the Thumbnails are created as expected. But as the bitmap is created with `PixelFormat.Format24bppRgb` that is not what you would expect. (Which of the two (converter or bitmap) has an "alternative" interpretation of the 24bit RGB value, I don't know yet. Already too late to investigate this further.)

**Comment by 0x90d** [comment]
> and removing the `avcodec-58.dll` check, VideoStreamDecoder() could be called without errors.

This is a too rare scenario as that I would call this a bug in VDF. My check just making sure that people are using the shared version of ffmpeg.

> Size(100, -1): The -1 is not supported by `VideoFrameConverter()`.

On Windows this works perfectly fine. Does it return `null` on some videos or all under Linux? Which Linux do you use btw?
