### ISSUE TITLE
V3 doesn't start when installed over a v2

### ISSUE THREAD

**Issue by cooperdk** [0x90d/videoduplicatefinder#204]
**Environment**
Windows x64

**Bug Description**

The app starts, blurred window, but closes again.
I have used VDF 2 in the past so there is data for thousands of video clips. I extracted the archive into the v2 folder without removing anything.

**Expected behavior**

VDF 3 should simply start. If necessary, convert the already-generated database.

**Comment by 0x90d** [comment]
v2 database is not fully compatible with v3. It takes over the files but not the gray bytes because v3 supports multiple gray bytes depending on how many thumbnails you have selected. Extract v3 into a new folder and copy over the database file and perhaps the settings file.

**Comment by cooperdk** [comment]
That didn't work.

Starting the application without the db copied over does work.
That suggests there's an issue reading the db file.
