### ISSUE TITLE
Question about expected Linux setup for native ffmpeg

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#205]
In #201 you replied to the question  
> After setting ffmpeg.RootPath = "/usr/lib/x86_64-linux-gnu/"; and removing the avcodec-58.dll

with

> This is a too rare scenario as that I would call this a bug in VDF. My check just making sure that people are using the shared version of ffmpeg.

So I'm a little confused about the expected setup.
As you described in README.md you will usually install ffmpeg via the package manager on Linux. At least on my system ffmpeg depends on libavcodec-extra58 and libavfilter-extra7 so the libraries are installed as well. (And otherwise you would also install them via the package manger)
So ffmpeg will be installed e.g. in "/usr/bin/". Setting `ffmpeg.RootPath = Path.GetDirectoryName(FFmpegPath);` independently of the OS and the way FFmpegPath was determined may fit to some windows installations or if you copy everything to the "bin" directory of VDF. But if you have installed ffmpeg with apt-get, the executable will be in one of the "bin" directories listed in the PATH variable and the libraries are installed in one of the "lib" directories. So there is no relation between FFmpegPath and the (avcodec,...) libs. In addition all libraries are installed with the file extension ".so" / ".so.[version]".

So one possibility to meet the expectations of VDF would be create soft links of ffmpeg and all required libraries in VFDs bin directory, and add a dummy avcodec-58.dll. - But this seems to be a little strange. Therefore, when I wrote #201, I assumed that the handling for a ffmpeg standard installation using apt-get was missing.

But as you answered with "a too rare scenario" you obviously have a different Linux setup with shared dll libraries,...?

**Comment by 0x90d** [comment]
> if you have installed ffmpeg with apt-get, the executable will be in one of the "bin" directories listed in the PATH variable and the libraries are installed in one of the "lib" directories

This was a misunderstanding then. I didn't know that, I'm not using Linux. I thought you mean that deleting the `avcodec-58` causes my check to fail but that wasn't the case. Can you make a PR fixing this problem in a way that it works on Linux then (I'm asking because you are able to immediately test this). You can use `RuntimeInformation.IsOSPlatform` like [here](https://github.com/0x90d/videoduplicatefinder/blob/245b914420c17795f92283cfceb11315075577a5/VDF.Core/Utils/CoreUtils.cs#L24) to see if you're running this under Linux and then set a different path

**Comment by Maltragor** [comment]
> I'm not using Linux

Does this mean you are writing a cross-platform application and have never run it yourself on Linux?
Do not misunderstand,... I'm just saying that I did not expect this^^. 

> Can you make a PR fixing this problem in a way that it works on Linux then

I had already started looking yesterday for ways to specifically search for the path to a library. But I only got results based on Linux command line programs. Like e.g. `whereis "libavcodec.so.58"` (file search in the usual bin/lib folders) or `ldd /usr/bin/ffmpeg | grep libavcodec.so.58 | awk '{print $3}'`. (list which dependencies ffmpeg has and search for the libavcodec in it), or `ldconfig -p | grep libavcodec.so.58 | awk '{print $4}'` (search the library cache for the file)

But typically you don't search for the location yourself but simply load the library with dlopen(), because the function itself searches the library cache, and various environment variables and directories.
FFmpeg.AutoGen (as I just saw) also uses dlopen() on Linux. And the "trick" is simply to set `ffmpeg.RootPath = "";`. (By default a path is set, so with that the automatic search doesn't work anymore).

=> My suggestion would be to use any FFmpeg.AutoGen function raising an exception if the library is missing and try it with different values for RootPath.
In the PR #207 I'm using ffmpeg.GetOrLoadLibrary() directly. This is the function which is called from all shared function wrappers.

**Comment by 0x90d** [comment]
> and have never run it yourself on Linux?

This is not what I've said. I've said I'm not using Linux which means, it's not the platform I'm developing on. I don't run 3 different OS on every commit, instead I've tested the functionality once then wrote the readme. Native ffmpeg binding is pretty new commit. I leave it up to Linux or Mac users to report if there is a problem after a commit.

> And the "trick" is simply to set `ffmpeg.RootPath = "";`.

Why didn't you used this trick for Linux users instead of calling ffmpeg.GetOrLoadLibrary()?

**Comment by Maltragor** [comment]
Because you decided in your version on the one hand to check if the preconditions are fulfilled, i.e. if the shared libraries are available (exemplarily by the existence check of avcodec-58.dll) to be able to show a specific error message to the user based on this. On the other hand there is the FFmpeg.AutoGen exception handling with the fallback to the call of the ffmpeg application.
I liked the approach of dependency checking independent of runtime error handling. (I had removed your avcodec-58.dll check only as a test to get it to work initially. And in principle the check mechanism would allow to inform the user already when selecting the native option...).
But only setting `ffmpeg.RootPath = "";` would bypass this check mechanism, so that only the fallback error handling would be active.
Of course one can then again extend the error handling and react specifically to the DllNotFoundException,... (but on the one hand it would probably have led again to discussions if I had modified the error handling, and having a separate check functionality is certainly nothing bad.)

So the idea was to have a list of preferred places to search and as last option to let the OS specific loading function search based on its specific strategy. And at the end you know if loading will be successful or not (since the libraries are actually already loaded with it).
And as I noted in the PR comment, you could move the check and thus the loading to another place and add a configuration check, so that no loading attempt is made when native ffmpeg is disabled.
And in that case I see no negative side effect for e,g. calling `ffmpeg.GetOrLoadLibrary("avformat");` to check if the library exists. 

But yes, if you don't like the approach with GetOrLoadLibrary(), you could also not specify a path under Linux as well as skip the check on the DLL. ... And ideally adjust the error handling, so handle the DllNotFoundException separately to draw attention to the missing library.

**Comment by Maltragor** [comment]
> Why didn't you used this trick for Linux users instead of calling ffmpeg.GetOrLoadLibrary()?

To exclude possible misunderstandings:
The "trick" is used, GetOrLoadLibrary is only used as platform independent replacement for your Windows DLL existence check.
And since it is not bad to search for the library in the installation path of ffmpeg under Linux, and since Windows also searches in a few places when omitting the path, an OS specific treatment seemed unnecessary to me.
(And the original search path I had simply kept as a third option in the path list).

**Comment by Maltragor** [comment]
@0x90d: Since I don't know if you read new comments already closed issues, please let me know if you have read this.

The reason why I decided against an approach where you search the directories by yourself was:
https://opensource.com/article/20/6/linux-libraries
> Red Hat family
    - 32 bit: /usr/lib
    - 64 bit: /usr/lib64
Debian family
    - 32 bit: /usr/lib/i386-linux-gnu
    - 64 bit: /usr/lib/x86_64-linux-gnu
Arch Linux family
    - 32 bit: /usr/lib32
    - 64 bit: /usr/lib64
And I definitel

And I definitely didn't want to research if these are all possible paths or if there are other variants depending on whatever.
