### ISSUE TITLE
Whatever I do, the program doesn't detect FFMPEG and FFPROBE

### ISSUE THREAD

**Issue by elcosomalo1** [0x90d/videoduplicatefinder#210]
**Environment**
 - OS: WINDOWS 10

**Describe the bug**
The program refuses to detect ffmpeg & probe.
-Tried putting them in the same folder directly (both files)
-Tried putting them inside a "bin" folder inside the program folder
-Tried making a PATH variable to the path where both files are.
-Tried a different SHARED version of ffmpeg and probe and copied ALL files to the program folder.

**Expected behavior**
That the program works.

**Comment by elcosomalo1** [comment]
Nice program btw!

**Comment by 0x90d** [comment]
Try starting VDF as admin and see if that works. If not, try moving VDF to a different folder/path.

**Comment by elcosomalo1** [comment]
Tried as admin too, didn't work.
Tried on another path, nope.

![image](https://user-images.githubusercontent.com/43975882/134783992-c87b4154-ffb2-4110-82e7-aec6da371fe8.png)

**Comment by elcosomalo1** [comment]
do you have an ffmpeg distribution that you know its working? I could test that

**Comment by 0x90d** [comment]
You are using native ffmpeg bindings, you should have said that. It only works with stable SHARED version of ffmpeg (4.4), try this one: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-09-25-12-22/ffmpeg-n4.4-154-g79c114e1b2-win64-gpl-shared-4.4.zip

**Comment by elcosomalo1** [comment]
Working now! 
A humble suggestion is to put that link as example in the readme because there are like 18 versions on that page (and I just downloaded the "N" version that said "shared" and apparently it looks the same, has all the files but doesn't work.
Some people like me who doesn't know will download wrong versions in the future too.

![image](https://user-images.githubusercontent.com/43975882/134784798-f775184e-251d-4c99-9a00-a21ea1640aaf.png)

**Comment by elcosomalo1** [comment]
> Like written in readme it explicit looks files like avcodec-58.dll the nightly ffmpeg build has other file names. Make sure you extract all .dll files!

Just to clarify, in the readme it doesn't say that.

![image](https://user-images.githubusercontent.com/43975882/134784906-f6af27a2-4e0d-4266-bc88-badc3713cbdf.png)

Also, the "N" (now I know it was a nightly, doh!)  has all the files in it but the name changes as you say, now its version 59.
![image](https://user-images.githubusercontent.com/43975882/134784921-28555cde-377a-456a-985a-bcb963e1b223.png)
