### ISSUE TITLE
Bug: GetGrayScaleValues 

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#211]
int stride = tempImage.GetPixelRowSpan(0).Length;  -> 16
int bytes = stride * original.Height;  -> 256

for (int i = 0; i < bytes; i += 4)
=> Only 64 bytes of the 256 GrayScale image are processed

**Comment by 0x90d** [comment]
FYI: If you click on the line number in code here in Github you can reference to it. Clicking a line number, holding down shift and clicking another line number let you reference to multi lines.
