### ISSUE TITLE
Open in Explorer

### ISSUE THREAD

**Issue by StephKoenig** [0x90d/videoduplicatefinder#216]
**Environment**
 - OS: Win10 x64
- v3

**Describe the bug**
Context/Right-click a row amd select open in Explorer. VDF opens the explorer for the selected row (blue row) not the row clicked on

**Expected behavior**
Explorer should open with at the file whose row was clicked on.

**Work Around**
Click the row first to make it selected before context/right-clicking to open in explorer

Will load the daily and check later reporting just in case.

Also quick one....  would be handy if tapping del with a row selected offered to delete the file immediately...

Love this app!

**Comment by 0x90d** [comment]
Dupe #193

**Comment by StephKoenig** [comment]
Sorry rookie error.
