### ISSUE TITLE
ffmpeg native binding + cuda HW acceleration doesn't work

### ISSUE THREAD

**Issue by CrendKing** [0x90d/videoduplicatefinder#219]
**Environment**
 - OS: Windows 10

**Describe the bug**
I have NVIDIA RTX 2070 Super.

When using both ffmpeg native binding and CUDA hardware acceleration, I always get this error in the log:
```
21:19:52 => Failed using native FFmpeg binding on '<redacted>', try switching to process mode. Exception: VDF.Core.FFTools.FFInvalidExitCodeException: Could not initialize the conversion context.
   at VDF.Core.FFTools.FFmpegNative.VideoFrameConverter..ctor(Size sourceSize, AVPixelFormat sourcePixelFormat, Size destinationSize, AVPixelFormat destinationPixelFormat)
   at VDF.Core.FFTools.FfmpegEngine.GetThumbnail(FfmpegSettings settings, Boolean extendedLogging)
```
If I switch off hardware acceleration, no more error happens.

I know as a fact that when using standalone exe mode, `-hwaccel cuda` works. I also know that when I use ffmpeg library in C/C++, cuda hardware accel works, even though it requires some extra steps to properly set up. If you want, I can share the snippet, but I'm not sure how to convert to .NET.

**Comment by 0x90d** [comment]
> even though it requires some extra steps to properly set up. If you want, I can share the snippet

I would appreciate that, thank you

**Comment by CrendKing** [comment]
I was trying to only post the hardware acceleration part of my code, but it turns out they are quite intertwined with rest of the code, so I decided to just post the full-workflow code: https://gist.github.com/CrendKing/0be37d6b61b5346b921c4db168f6bcd6

For `HW_DEVICE_TYPE`, both `AV_HWDEVICE_TYPE_NONE`, `AV_HWDEVICE_TYPE_CUDA` and `AV_HWDEVICE_TYPE_D3D11VA` work for my card.

To be honest, nowadays I stopped to use ffmpeg to extract thumbnails, because as you can see, it is quite verbose. Since I mainly use Windows, C++/WinRT offers a much simpler solution. And since you are on .net, it is even better. I don't know about cross-platform compatibility though.

Here's the relevant part of my C++/WinRT code, for comparison. A .net version should be even simpler:
```cpp
const MediaComposition mediaComp;
TimeSpan totalDuration {};

for (std::wstring_view input : inputFiles) {
    const auto sourceFile = StorageFile::GetFileFromPathAsync(input).get();
    const auto videoFile = MediaClip::CreateFromFileAsync(sourceFile).get();
    mediaComp.Clips().Append(videoFile);
    totalDuration += videoFile.OriginalDuration();
}

const int thumbnails_count = 10;
const TimeSpan frameGap = totalDuration / thumbnails_count;

for (int i = 0; i < thumbnails_count; ++i) {
    const auto thumbnailTime = frameGap * i;
    const auto thumbnailStream = mediaComp.GetThumbnailAsync(thumbnailTime, 0, 0, VideoFramePrecision::NearestFrame).get();
    const auto decoder = BitmapDecoder::CreateAsync(thumbnailStream).get();

    const auto outputFolder = StorageFolder::GetFolderFromPathAsync(outputDirPath).get();
    const auto outputFile = outputFolder.CreateFileAsync(std::format(L"{:3d}.jpg", i), CreationCollisionOption::ReplaceExisting).get();
    const IRandomAccessStream imageStream = outputFile.OpenAsync(FileAccessMode::ReadWrite).get();
    const auto encoder = BitmapEncoder::CreateForTranscodingAsync(imageStream, decoder).get();
    // encoder.BitmapTransform() can be used here to do additional transformations
    encoder.FlushAsync().get();
}
```

Sure, there is no hardware acceleration, but hardware acceleration is [recommended against most of the time](https://mpv.io/manual/master/#options-hwdec), because it leads to more errors, and thumbnail extraction is an use case light enough (I think) that hwaccel doesn't provide enough benefit to justify. The concise and easy-to-maintenance nature is way more important in my opinion.

**Comment by CrendKing** [comment]
Interestingly, if I use `AV_HWDEVICE_TYPE_DXVA2` in my snippet, I get error. But if I use "dxva2" in VDF in conjunction with native binding, there is no error in log.

**Comment by 0x90d** [comment]
I'm calling the same APIs as you except that of `avcodec_get_hw_config` and `av_hwdevice_get_hwframe_constraints` but these are only for checking compatibility, right? So they shouldn't be required.

https://gist.github.com/CrendKing/0be37d6b61b5346b921c4db168f6bcd6#file-ffmpeg_thumbnail-cpp-L74-L95
https://github.com/0x90d/videoduplicatefinder/blob/master/VDF.Core/FFTools/FFmpegNative/VideoStreamDecoder.cs#L39-L41

It's basically just `av_hwdevice_ctx_create` that matters.

**Comment by CrendKing** [comment]
Those two calls help getting out appropriate pixel format for hardware and software (e.g. `AV_HWDEVICE_TYPE_CUDA` -> `AV_PIX_FMT_YUV420P`). The hardware format is purely for checking, but the software format is used for swscale conversion. If you don't need swscale or hardcode some appropriate format, sure you don't need them.

If you don't have a CUDA-capable device, you can send me a verbosely logged version of the library and I can help debug. If you do, can you confirm the original issue? If yes, can you run my code and yours side by side and see where is the problem?

**Comment by 0x90d** [comment]
For AV_HWDEVICE_TYPE_CUDA I'm using AVPixelFormat.AV_PIX_FMT_CUDA, changing it to AV_PIX_FMT_YUV420P (or whatever av_hwdevice_ctx_create -> pix_fmt is) no longer throws an error but I only get black or broken thumbnails.

`avcodec_get_hw_config` does not exist in ffmpeg stable branch.

**Comment by CrendKing** [comment]
The hardware pixel format should be `AV_PIX_FMT_CUDA`. The software pixel format is `AV_PIX_FMT_NV12`. `avcodec_get_hw_config` is defined at https://github.com/FFmpeg/FFmpeg/blob/2761a7403b5e905c7f9f70b4887ddfdab598dbcd/libavcodec/codec.h#L491. You can see it's defined in all those release tags.

Again, if you can come up with a small issue-reproducible snippet, I can help verify where our result diverge.

**Comment by Maltragor** [comment]
> In example app HW Acceleration cuda doesn't work   - Oct 4, 2021 

Ruslan-B/FFmpeg.AutoGen#176

Could that be the problem we're talking about here?

**Comment by CrendKing** [comment]
I didn't realize you were using a dependency. How is ffmpeg get used in the runtime? Do you use the host machine's dll or you statically link? If latter, what flags is ffmpeg built with?

**Comment by Maltragor** [comment]
VDF uses FFmpeg.AutoGen _(FFmpeg auto generated unsafe bindings for C#/.NET and Mono.)_ to call the functions of the shared ffmpeg libraries. (It's a wrapper to get the unsafe dll functions in the C# world.)
VDF is not linked statically. The libraries are loaded at runtime (FFmpeg.AutoGen calls dlopen() / LoadLibrary()).

If following the README.md of VDF
> Get latest package from https://ffmpeg.org/download.html I recommend the shared version
> Extract ffmpeg and ffprobe _[and the dlls]_ into the same directory of VDF.GUI.dll. Or into a sub folder called bin

This would be the dlls loaded at runtime on Windows.

**Comment by CrendKing** [comment]
OK. I use Scoop to install the released version of ffmpeg, from https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-09-22-12-21/ffmpeg-n4.4-154-g79c114e1b2-win64-gpl-shared-4.4.zip . It's GPL version anyways. Previously I used PATH env var. I just copied all the dll to the same folder as VDF. Same error.

What else do you need from me?

**Comment by Maltragor** [comment]
Search directories - only for the sake of completeness:

The quoted paragraph was only half the truth. 
The main message should be that if the DLLs are copied together with the ffmpeg exe to one of the two locations mentioned, VDF looks there first and uses them. (Independently of possibly existing additional ffmpeg locations).
-> So I could easily answer your question without having to make any assumptions of your setup.   

The complete search runs (if I do not miss anything spontaneously) as follows:
_(In the following with VDF the directory is meant, in which among other things the VDF.GUI.dll is located)._
1 ) Search for ffmpeg.exe in VDF\bin\\.
2 ) Search ffmpeg.exe in VDF\\
3 ) Search ffmpeg.exe in the entries of the PATH variable
4a) Search the ffmpeg DLLs in the previously determined ffmpeg directory
4b) If ffmpeg.exe was not found, search the DLLs in VDF\bin\\
5 ) Search for the ffmpeg DLLs in VDF\\
6*) Let LoadLibrary() search for the ffmpeg DLLs automatically
8 ) Search the ffmpeg DLLs in the entries of the PATH variable

So far the detailed variant for Windows^^
_(6*: This is planned, but it doesn't work at the moment, because ffmpeg.RootPath is not set to  "")_

**Comment by 0x90d** [comment]
> > In example app HW Acceleration cuda doesn't work   - Oct 4, 2021
> 
> ~Ruslan-B/FFmpeg.AutoGen#176~ (Issue was deleted)
> 
> Could that be the problem we're talking about here?

Yes, unfortunately as you said the issue is deleted. I've tested `dxva2` and this doesn't give any errors. I think its only cuda which fails, but I don't know why. I also don't know what ffmpeg does internally if cuda is selected. Maybe ffmpeg just silently skips cuda and fallback to `dxva2` or even no HW acceleration on our systems? I need a ffmpeg expert to solve this.
