### ISSUE TITLE
Should we drop 32bit support?

### ISSUE THREAD

**Issue by 0x90d** [0x90d/videoduplicatefinder#22]
Honestly, the source is available and everyone really needing it can compile it themselves. On the other hand I have no idea how much people are still using a 32bit system. Are there any public reliable stats?

**Comment by Revan654** [comment]
Not Sure How .netCore is Config. On .netFrameWork. You can Target AnyCPU Which will work on 32 or 64Bit. It will look at the person arch and then runs it based on that data.

I'm thinking why your asking is based off the external files that have to be compiled One way or another.

Most Dev's target 64bit Now of days. 32Bits is pretty much a dying breed.

**Comment by 0x90d** [comment]
32bit support will be dropped. Source is available for those who need it.
