### ISSUE TITLE
Delayed window animations

### ISSUE THREAD

**Issue by geeooff** [0x90d/videoduplicatefinder#220]
**Environment**
 - OS: Windows 11 Pro (Release Preview / Version	10.0.22000)
 - App Version: 2.0.8 and 3.x

**Describe the bug**
When you grab the main window title bar to move it to a different place the animation will be extremely slow and delayed.
If you move a lot your mouse while keeping your left mouse button down you will have to wait for the full animation to finish, which could be dozens of seconds.
The same issue is happening at resizing the window.

Reproduced on two computers running the same Windows build:
- one computer with a Nvidia RTX 3080 display adapter, G-Sync enabled for both fullscreen and windowed apps
- another on a more common Intel UHD 630 display adapter, no VRR tech enabled

**Expected behavior**
No delay in moving / resizing the window.
Animation to finish when releasing left mouse button.

It's the first time I have such issue with my running apps, so I suppose it could come from a Presentation Layer library used in both 2.x and 3.x versions?

**Comment by 0x90d** [comment]
What animations? v2 uses WPF and v3 uses Avalonia. They are very different from each other btw.

**Comment by 0x90d** [comment]
Closed because of missing feedback
