### ISSUE TITLE
Bug: Confirmation dialog is sized too large

### ISSUE THREAD

**Issue by gtTracy** [0x90d/videoduplicatefinder#222]
**Environment**
 - OS: [e.g. Windows / Linux]

Ubuntu 20.04.3

**Describe the bug**

The confirmation dialog that comes up with "Delete Selected", then "Delete Permanently" is selected covers 2/3 of the height of the screen, with the large majority of the dialog box empty. The "Yes" and "No" buttons are correctly placed just under the text, but the large displayed area below is empty and should not be shown.

**Expected behavior**

Selecting "Delete Selected", then "Delete Permanently" correctly presents an "Are you sure" dialog, but the dialog box should be sized appropriately for just the amount of text and controls that are presented.

**Comment by 0x90d** [comment]
This should be fixed with https://github.com/0x90d/videoduplicatefinder/commit/07478682000c3cf129c6c090f0d98e6b7443e7c9 which version do you use?

**Comment by gtTracy** [comment]
At this moment, I am a couple behind. I will download the most current in
the next day or so, and check again.

**Comment by gtTracy** [comment]
Verified fixed in currently available build
