### ISSUE TITLE
Feature Request - Add by double-clicking in Expression Builder

### ISSUE THREAD

**Issue by gtTracy** [0x90d/videoduplicatefinder#233]
**Environment**
 - OS: [e.g. Windows / Linux / Any]
Using Ubuntu 20.04.3, but this should apply to any environment

**Describe the solution you'd like**

When using the Expression Builder (Selection > Select Custom), it would be very helpful if it were possible to have the various expressions added to the "Expression" text box by double-clicking on them in the list of possible expressions (ie. if each possible expression that is listed were a click target, and double-clicking on them added them to the end of the text in the text box, as opposed to having to highlight and copy and paste them individually).

**Comment by 0x90d** [comment]
This is not possible because avalonia has no hyperlink control. But if you build an expression once and the ability to save/load them (see #190) is added it's not a big deal anymore.
