### ISSUE TITLE
Mediainfo duration timer is wrong

### ISSUE THREAD

**Issue by 0x90d** [0x90d/videoduplicatefinder#24]
When paused the GUI timer is paused but when finished the duration printed to log shows the overall time including the time it was paused.

**Comment by Revan654** [comment]
> 
> 
> When paused the GUI timer is paused but when finished the duration printed to log shows the overall time including the time it was paused.

MediaInfo is known to have problems and it takes them ages to fix it. I constantly have to fight with MediaInfo when coding my video encoders.

As nice as the SDK is to have, It does have it share of problems.
