### ISSUE TITLE
Some duplicates not identified

### ISSUE THREAD

**Issue by scrapix** [0x90d/videoduplicatefinder#250]
**Environment**
 Windows

**Describe the bug**
Some duplicate videos are not identified properly for videos (different compression).
Attached is one example.

**Expected behavior**
identification

[DuplicatesNotIdentified.zip](https://github.com/0x90d/videoduplicatefinder/files/7656368/DuplicatesNotIdentified.zip)

**Comment by Maltragor** [comment]
When you scan the files for the first time (so that there is no database entry of the files yet), you will get following messages in the log:
> ERROR: Graybytes too dark of: ***/20050104_170524-2.mp4
> ERROR: Graybytes too dark of: ***/20050104_170524.mp4

If the scenes (thumbnails) viewed by VDF are too dark, they are ignored because dark scenes are always very similar for VDF in general.

**Comment by scrapix** [comment]
Oh, Thank you for the hint!

**Comment by scrapix** [comment]
Just wondering. How does VDF compare the videos? 
By comparing the extracted thumbnails with a hashing algorithm? 
If so, which one(s) is in use?
Is there maybe some hashing algorithm (Blake3, dhash, phash, ahash ...) which is more suitable for dark thumbnails?

May following abstract proposal be a possible way to also compare dark videos?
**IF** Graybytes too dark **use** _'most suitable alogrithm for Gaybytes'_

**Comment by 0x90d** [comment]
VDF takes the graybyte thumbnails and compare both. If too many bytes are equal its considered as duplicate. There is no hashing algorithm. To get better results I suggest just increasing the amount of thumbnails assuming that only the one frame is too dark. If the whole videos are dark all the time you're out of luck.

**Comment by 0x90d** [comment]
Closing as the original issue seems to be solved
