### ISSUE TITLE
Make database editable by user

### ISSUE THREAD

**Issue by 0x90d** [0x90d/videoduplicatefinder#253]
**Environment**
 - OS: Any

**Describe the solution you'd like**
Currently if there is something wrong users have to delete the entire database. Therefore users should be able to edit database entries. For example edit/remove the file flags or delete entries and so on.

**Comment by Maltragor** [comment]
As a preliminary stage, or also generally for the extended editability, one could also offer the import of a database in the Json format.
This would at least lower the hurdle for a manual adjustment or processing in a custom script. 

It might also be possible to allow exporting without grayscale images as an additional option. When importing, the entries of the Json file will be enriched again (if available) with the corresponding thumbnails from the (old) database.
