### ISSUE TITLE
"Invalid data found when processing input"

### ISSUE THREAD

**Issue by Erothas** [0x90d/videoduplicatefinder#254]
**Environment**
 - OS: [e.g. Windows / Linux]
Linux

**Describe the bug**

No results whatsoever despite many duplicates existing.
Checking the log file, I am getting a bunch of errors: "ERROR: Failed to retrieve media info from: *insert file name and path": /usr/bin/ffprobe  -hide_banner -loglevel error -print_format json -sexagesimal -show_format -show_streams  *insert file name and path*
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f999c81900] moov atom not found
Invalid data found when processing input
FFprobe exited with: 1"

What's even more fascinating is the fact that I tested a smaller folder. I created a three copies of one video, and started VDF scanning. No errors were found, but no duplicates were found either. So, even fixing that error won't solve the issue entirely.

**Expected behavior**

Detect the duplicates.

**What have you tried?**

- I switched Use native ffmpeg binding on and off. 
- I tried most hardware acceleration options. I increased the thumbnails from 1. Nothing was changed (aside from the scanning speed, of course). 
- I lowered the matching percent value.

**Comment by 0x90d** [comment]
This sounds more like a ffmpeg/ffprobe/video file issue. What happens if you run ffprobe or ffmpeg with the same commands on the same videos outside of VDF?

**Comment by Erothas** [comment]
> This sounds more like a ffmpeg/ffprobe/video file issue. What happens if you run ffprobe or ffmpeg with the same commands on the same videos outside of VDF?

You are right. It returns the same exact error mentioned above. 

So, the bug is coming from ffprobe, huh? I doubt waiting will just resolve the problem though.

**Comment by gtTracy** [comment]
Coming in late to the party here, but the `MOOV atom not found` error from ffmpeg and/or ffprobe is usually caused by a corrupt or incomplete video file - the MOOV atom contains some of the video characteristics, and is written last when originally creating an MP4 file. If the file is not completely written (ie. the encoder stops/exits/crashes before writing the MOOV atom), then this will occur.

Are these files video captures that you created, or are they downloads from a streaming site (where the connection may have collapsed before the entire stream was received/encoded)? I seem to recall seeing something a while back about a tool that might be able to repair this kind of thing - for some reason AtomicParsley is coming to mind, but it's been a while and I'm not sure... Might be worth a search around to see what turns up....

**Comment by Erothas** [comment]
You were absolutely right! Upon checking the video in question, I noticed they don't even have a thumbnail, and were not playable with any media player that I had. And there were so many of them too! Which is honestly a very bizarre phenomenon to happen.

They are, indeed, videos that were downloaded online. But there should be no reason to why they were downloaded in a corrupt state like that. So, I went ahead and checked that AtomicParsley program that you mentioned. Are you sure it's the right tool here? It parses metadata from media files. I don't see any sort of repairing features there.

If it's not possible, is there a way to curate all these corrupt files from the log and delete them? Handling that manually could easily take half a day.

**Comment by gtTracy** [comment]
No, I was misremembering about AtomicParsley - there was another app that would scan looking for missing markers like that, and close the file properly when found. But I can't remember what that app was now, and some light googling didn't turn it up.

But at the least, here is a quick way to identify the corrupted files:

```
#!/bin/bash

# modify the following two lines for your own use
LogFile='/media/Testing/Sorted/badfiles.txt'
StartPath='/media/Testing/Sorted'

# LogErr
#
# Takes an input path name (or really, any string) and writes it (the path name or string,
# not the file content) to a log file
#
# LogErr <path name>

LogErr()
{
	echo "$1" >> "$LogFile"
}

# ProcessVideo
#
# Takes an input file name (presumably for a video file, but the function doesn't
# actually attempt to verify that), and hands it off to ffprobe to do some basic 
# processing of the video stream. We look for the referenced error in the output
# from ffprobe, then log the file name to a file.
#
# ProcessVideo <path to video>

ProcessVideo()
{
	local vfn=$1
	local oput
	echo "Checking video $vfn"
	oput=$(ffprobe -loglevel warning "$vfn" 2>&1)
	if [[ "$oput" == *"moov atom not found"* ]]
	then
		echo "Error string $vfn"
		LogErr "$vfn"
	fi
}

# NextDir
#
# Recursively loop through $StartPath and pass each found file to ProcessVideo
#
# NextDir <folder path>

NextDir()
{
	echo "Checking $1"
	for fn in "$1"/*;
	do
		echo "Found $fn"
		if [[ -f $fn ]]
		then
			echo "Video $fn"
			ProcessVideo "$fn"
		elif [[ -d $fn ]]
		then
			echo "Folder $fn"
			NextDir "$fn"
		fi
	done;
}

echo "Starting..."
NextDir "$StartPath"

```

**Comment by Erothas** [comment]
@gtTracy Thank you very much. I am not getting any time to try anything right now. But as soon as I do, I will. Many thanks once again.
