### ISSUE TITLE
Allow to add multiple folders to be searched/excluded

### ISSUE THREAD

**Issue by qarmin** [0x90d/videoduplicatefinder#255]
**Environment**
 - OS: Any

**Describe the solution you'd like**
Currently when I want to search in multiple folders in "Search Directories" or "Excluded Directories", I need manually add one by one. 
With multi selection would be possible to add multiple directories at once(at least from same folder).

**Comment by 0x90d** [comment]
This requires changes on Avalonia's FolderDialog as its lacking of such a feature. For reference https://github.com/AvaloniaUI/Avalonia/issues/7209

FYI: As workaround you could drag and drop folders onto it, this might be faster.

**Comment by jeffward01** [comment]
Just wanted to update this issue with the latest status. 

It appears avalonia has implemented this feature in July 2022: https://github.com/AvaloniaUI/Avalonia/pull/8303

I’m just posting this here for sake of keeping good records organized
