### ISSUE TITLE
Freeze when scanning directory with ~500 000 items

### ISSUE THREAD

**Issue by qarmin** [0x90d/videoduplicatefinder#256]
**Environment**
 - OS: Ubuntu 21.10

**Describe the bug**
When scanning my home folder `/home/rafal` which contains 579 961 which takes 79,6 GB, then app completely freeze with info "Please Wait, Enumerating files..."
This took ~20 minutes and after that time I just killed app.
In console there is no crash info or similar thing.

I'm not sure what exactly algorithm to find files use VDF, but looks that it is broken or very non effective.
In my app I use this algorithm which usually check such number of files in 5-20 seconds(Rust have access to low level OS things, so times in this app probably would be a little bigger)
- Add folders chosen by user to queue
- Take from queue first folder and check all of children
- If it is folder, add it to queue to check
- If it is file, check its extension, if is supported e.g. ".mp4" or ".avi" save its name to result collection, if not just ignore it
- Repeat until there is no folder to check

After 20 minutes, VDF.GUI process still takes 25% CPU(i7 4770 4/8 HT )

**Comment by 0x90d** [comment]
It uses [Directory.EnumerateFiles](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles?view=net-6.0) API which is actually extremely efficient. It can be slowed down by your security tool going crazy due to all the file accesses or if its a cloud drive or something.

**Comment by qarmin** [comment]
I don't have on disk any cloud files, nor any antivirus or similar tool which could do such thing.
I will try to find smaller folders which cause slowdowns, because maybe specific files cause this slowdown

**Comment by 0x90d** [comment]
I'm closing this. Either this is something on your end or its an issue with the .NET API I don't have any control over. 

As a note I've just ran it against my network archive with over 105,000 media files. File enumeration only took about 1 minute and 4 seconds and memory usage was at 115mb.
