### ISSUE TITLE
Throw out earlier folders which won't be scanned 

### ISSUE THREAD

**Issue by qarmin** [0x90d/videoduplicatefinder#257]
**Environment**
 - OS: Any

**Describe the solution you'd like**
When using as include directory `/home/ziemniak` and as excluded folder `/home` or `/home/ziemniak` it is 100 % sure than 0 files will be found, but still app check every file if is in excluded folder

**Comment by 0x90d** [comment]
When exactly did you dowloaded VDF? There has been a commit about include/exclude folders 7 days ago.

**Comment by qarmin** [comment]
I downloaded today latest version from https://github.com/0x90d/videoduplicatefinder/releases/tag/3.0.x
Looks that github actions not published latest version here

**Comment by 0x90d** [comment]
Yes it does you can check the commit hash. However I've just saw the logic is to check if its part of the include list first and if it is, its considered as valid. The check if its also part of the exclude list will be skipped.

Its a bug but a relatively minor one. I don't expect a user to be serious when adding a parent folder to the exclude list.
