### ISSUE TITLE
VDF extreme lag when resizing or moving the app window - affects other apps when open as well

### ISSUE THREAD

**Issue by bobsage123** [0x90d/videoduplicatefinder#258]
**Environment**
 - Windows 11

**Describe the bug**
This is a weird one, never seen before. But when I open VDF, trying to resize or move the window lags extremely badly, almost like it is going in slow motion. It also affects every other app window as well which then has the same behavior. The behavior stops on the other windows as soon as VDF is closed.
I am on the newest build.

**Expected behavior**
No lag

**Comment by 0x90d** [comment]
This is an Avalonia rendering issue. You cannot reproduce this inside of a VM but outside. I can produce the same experience on Avalonia's control gallery from Microsoft Store.

**Comment by 4rch0n** [comment]
Is it still an issue?
I think it was solved by https://github.com/0x90d/videoduplicatefinder/pull/263 
At least on my setup on windows 10 I have no similar issues at the moment.

**Comment by 0x90d** [comment]
Yes its still an issue. Moving the window on Windows 11 is really slow and rubberish.

**Comment by bobsage123** [comment]
> Yes its still an issue. Moving the window on Windows 11 is really slow and rubberish.

Does the issue occur on windows 10? I'm tempted to use a vm with 10 until it's fixed.

**Comment by 0x90d** [comment]
In a virtual machine you should have no issues. This seems to happen only when a dedicated GPU is used. I dont have Windows 10 installed on any system only in a VM, so I cannot tell if its an OS related issue.

**Comment by cooperdk** [comment]
I can verify that this is still an issue in Windows 11, non virtual.
Maybe ditch Avalonia if that is the cause.

According to this they should now use the new method which doesn't lag. Apparently it only happened/happens when using a blur/acrylic theme, so maybe just turn that off.

https://github.com/Wox-launcher/Wox/issues/2891

**Comment by 0x90d** [comment]
It's no longer an issue for me on Windows 11 22581.100

**Comment by bobsage123** [comment]
This is still a problem on the latest VDF build and Windows 22H2. (I'm not sure if it was working in 22H1 and reemerged in 22H2).
