### ISSUE TITLE
Option to ignore symlinked folders

### ISSUE THREAD

**Issue by fantesykikachu** [0x90d/videoduplicatefinder#259]
**Environment**
 - OS: Windows ( but this is true on other OSes and may require a different implementation)

**Describe the solution you'd like**
I believe this is a clarification of #121 

Say you have the folder structure:
top_folder\folder1\file.mp4
top_folder\folder2 -> folder1 (where folder2 is a directory symlink to folder 1)

If I then scan top_folder including subdirectories it will resolve,
top_folder\folder1\file.mp4 and top_folder\folder2\file.mp4
if I then delete either file, since there is only one file ( the other file is not even a symlink) then all copies are deleted.

It would be nice if in addition to the option to exclude hard links of there were also options for:
exclude symlink files, there is no delete problem if you select the symlink, but it still clutters up the results window.
exclude symlink directories, for the above reason.

**Comment by Maltragor** [comment]
When checking "Exclude Hardlinks", VDF adds `FileAttributes.ReparsePoint` to `enumerationOptions.AttributesToSkip` used by `Directory.EnumerateDirectories` and `Directory.EnumerateFiles` while adding new files to the database (`FileUtils.GetFilesRecursive`).

1) HardLink vs. SymLink vs. ReparsePoint vs. JunctionPoint ...
NTFS: My understanding is that SymLinks and JunctionPoints are different forms of ReparsePoints.
(In Linux the `FileAttributes.ReparsePoint` also works for SymLinks.)

2) VDF considers the "Exclude ***links" option only while adding new files. It does not consider the option while comparing the videos based on the database entries.
=> So if your database is empty and you check the option, SymLinks will be ignored. But if you have scanned the files one time without ignoring the links, checking the option afterwards will have no effect.

So on the one hand the naming of the exclude option is not suitable in my opinion.
And on the other hand the `InvalidEntry` (ScanEngine.cs) has to consider the option as well to filter the linked files.

**Comment by fantesykikachu** [comment]
So after trying again with a new smaller directory structure, I can not reproduce my problem so i guess it is on my end, therefore I am closing the issue.
