### ISSUE TITLE
Scanning Wrong Folder & Removed Files Showing up Again

### ISSUE THREAD

**Issue by Revan654** [0x90d/videoduplicatefinder#26]
**Environment**
 - OS: Windows 10(64 Bit) - Fall 2018

**Describe the bug**
- I have a few Folders excluded from the Scan and Yet it still show up as being Scanned and the files are being Added to the list.
- Files That I Deleted the Last round, are also Still showing Up. I tried clean database button as well. It Still shows up. 

These are usually content from additional drives not the main C:\ Drive. Like G:\ or I:\

**Comment by 0x90d** [comment]
Are you using the official releases or daily (i.e. self compiled)?

**Comment by Revan654** [comment]
> 
> 
> Are you using the official releases or daily (i.e. self compiled)?

Official Release, 4.7.2 SDK doesn't support netcore 3.0 yet since it's not officially supported by MS for public Projects.

**Comment by 0x90d** [comment]
I cannot reproduce the problem. Have you tried creating a new database and see if the problem happens again?
