### ISSUE TITLE
Windows 11 - Not Working

### ISSUE THREAD

**Issue by DrQuinn69** [0x90d/videoduplicatefinder#261]
I have been using 3.0 on Windows 10 without issue - best tool I have found, no competition so thank you for creating this, it is simply amazing!

On Windows 11 I am using the latest daily build (App-win-x64.zip) and FFmpeg & FFprobe (ffmpeg-master-latest-win64-gpl-shared.zip) nothing happens when I press start? The program opens, menus work, can configure items but nothing happens when I click Start. Checked my settings and everything looks good. Saved the log file but it is empty?

I apologize if I have missed something obvious as I am an older home user with no software/programming experience. Thank you for your help.

**Comment by 0x90d** [comment]
I'm using Windows 11 and it works fine here. Please double check your settings

**Comment by DrQuinn69** [comment]
I have been using VDF on Windows 10 for quite some time - no issues at all. I have tried Ver 3 and 2 on three different Windows 11 machines using same settings that work on Win 10 accessing files on a NAS. After pressing Start, nothing happens. Using Windows 11 Pro, Version 21H2, OS build 22000.376. From Windows explorer I have my NAS mapped and read/write to it from all 3 Win 11 machines. Not sure what is going on. Sorry for the troubles, I will keep plugging away and hopefully figure it out, can use an older Win 10 desktop in the meantime. If I figure it out I'll be sure to share. Thank you.
