### ISSUE TITLE
Designer throws exception

### ISSUE THREAD

**Issue by Stevecaboose** [0x90d/videoduplicatefinder#268]
I cloned the repo with a fresh windows 11 install and fresh VS 2022 install. I have installed the Avalon extension in VS 2022. I get this when trying to view the xaml in the designer:

``
20:32:52.004 [Information]  Avalonia Package initialized
20:33:21.995 [Information] 0 Starting previewer process for '"C:\Users\Steve\source\repos\videoduplicatefinder\VDF.GUI\bin\Debug\net6.0\VDF.GUI.dll"'
20:33:22.001 [Information] 11756 Started previewer process for '"C:\Users\Steve\source\repos\videoduplicatefinder\VDF.GUI\bin\Debug\net6.0\VDF.GUI.dll"'. Waiting for connection to be initialized.
20:33:22.165 [Information] 11756 Connection initialized
20:33:23.029 [Error] 11756 <= "Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object."
20:33:23.036 [Error] 11756 <= "   at VDF.GUI.ApplicationHelpers.get_MainWindow() in C:\Users\Steve\source\repos\videoduplicatefinder\VDF.GUI\ApplicationHelpers.cs:line 26"
20:33:23.047 [Error] 11756 <= "   at VDF.GUI.App.OnFrameworkInitializationCompleted() in C:\Users\Steve\source\repos\videoduplicatefinder\VDF.GUI\App.xaml.cs:line 46"
20:33:23.051 [Error] 11756 <= "   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312"
20:33:23.055 [Error] 11756 <= "   at Avalonia.Controls.AppBuilderBase`1.SetupWithoutStarting() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 167"
20:33:23.060 [Error] 11756 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer`1.ConfigureApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 154"
20:33:23.064 [Error] 11756 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 179"
20:33:23.068 [Error] 11756 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 47"
20:33:24.858 [Information]  Process exited
20:33:24.859 [Information]  Stopping previewer process
20:33:24.858 [Error]  Connection error
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<ReadExact>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<Reader>d__16.MoveNext()
   ``

I have tried to search this error but didnt come up with anything. I have tried other Avalon projects with no issues. Let me know if im missing anything. Thanks

**Comment by 0x90d** [comment]
In VS 2022 the designer don't work for me. Try commenting this line out

https://github.com/0x90d/videoduplicatefinder/blob/ab8160eebd28fc54fdc5a430db537420d0221fc0/VDF.GUI/App.xaml.cs#L46

**Comment by Stevecaboose** [comment]
That did fix it thank you. Is the UI for the most part already developed and thus doesn't need a designer?

**Comment by 0x90d** [comment]
Initially it was done in VS 19 where designer has worked. Now I'm doing changes in code and then run. The designer is only useful if you need to see the changes instantly.
