### ISSUE TITLE
Is there a light theme available?

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#270]
**Environment**
 - OS: macOS

**Describe the solution you'd like**
A light theme

I saw the code here https://github.com/0x90d/videoduplicatefinder/blob/74ff8855663bb225eac01f137b61b909c665c6b4/VDF.GUI/App.xaml
that specified `<FluentTheme Mode="Dark" />`

I thought when I used VDF 2.x, there was a light theme.

**Comment by 0x90d** [comment]
VDF 2 had a light theme, but not a dark theme. VDF 3 has only a dark theme. It could have a light theme since Avalonia supports it but it currently has hardcoded color values too, which needs to be changed to dynamic ones first.
