### ISSUE TITLE
If a ffmpeg command is not successful right away, it will run for several minutes

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#272]
**Environment**
 - OS: macOS

**Describe the bug**
I ran a scan that should have taken just a couple of seconds.  Instead, it ran for nearly 9 mins.  Upon looking at the log, I saw that a few ffmpeg commands failed to get the info it was looking for.  The problem is the ffmpeg command will run for several minutes before exiting.

I think that if a ffmpeg or ffprobe command doesn't finish with `x` number of seconds, we can assume the video is corrupt or some other issue is going on and bail on it and kill the process and move on.

I tried the same command from the below log with a non-corrupt video file, and it finished in 2.27 seconds.  The below command ran for 2.5 mins.

Log:
```
/opt/homebrew/bin/ffmpeg  -hide_banner -loglevel error -y -hwaccel auto -ss 00:03:14.5000000 -i "my_awesome_video.mp4" -t 1 -f rawvideo -pix_fmt gray -vframes 1 -s 16x16  "-"
[h264 @ 0x11b00c200] Missing reference picture, default is 2
[h264 @ 0x11b00c200] co located POCs unavailable
[h264 @ 0x11b00c200] hardware accelerator failed to decode picture
[h264 @ 0x11b008200] reference picture missing during reorder
    Last message repeated 1 times
[h264 @ 0x11b008200] Missing reference picture, default is 2
    Last message repeated 1 times
[h264 @ 0x15b87b800] mmco: unref short failure
[h264 @ 0x11b008200] hardware accelerator failed to decode picture
[h264 @ 0x15b87b800] hardware accelerator failed to decode picture
[h264 @ 0x15b883000] reference picture missing during reorder
[h264 @ 0x15b883000] Missing reference picture, default is 65604
[h264 @ 0x11b008800] mmco: unref short failure
[h264 @ 0x15b883000] hardware accelerator failed to decode picture
[h264 @ 0x11b008800] hardware accelerator failed to decode picture
[h264 @ 0x15b00e200] hardware accelerator failed to decode picture
[h264 @ 0x15b00c200] hardware accelerator failed to decode picture
[h264 @ 0x15b00c800] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred
[h264 @ 0x14b011c00] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred
[h264 @ 0x11b00c200] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred
[h264 @ 0x11b008200] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred
[h264 @ 0x15b87b800] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred
[h264 @ 0x15b883000] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred
[h264 @ 0x11b008800] hardware accelerator failed to decode picture
.
.
.
.
<Hundreds of more lines>
.
.
.
[h264 @ 0x12b821000] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred
[h264 @ 0x12b821600] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred
    Last message repeated 7 times
FFmpeg exited with: 69
```
`Executed in  146.71 secs`

**Expected behavior**
If a ffmpeg or ffprobe command is running for more than 3-5 seconds, we can assume it's not going to finish and kill the process and move on.

**Comment by newadventure079** [comment]
Log output and running time from when my dir had some videos that failed with ffmpeg
```
20:13:10 => Building file list...
20:13:10 => Found previously scanned files, importing...
20:13:10 => Previously scanned files imported. 275 files in 00:00:00.0110657
20:13:16 => Files in database: 275 (0 files added)
20:13:16 => Finished building file list in 00:00:06.1215362
20:13:16 => Gathering media info and buildings hashes...
20:13:22 => ERROR: Failed to retrieve graybytes from: video.mp4
FFmpeg exited with: 69
20:13:33 => ERROR: Failed to retrieve graybytes from: video1.mp4
FFmpeg exited with: 69
20:13:36 => ERROR: Failed to retrieve graybytes from: video2.mp4
FFmpeg exited with: 69
20:13:38 => ERROR: Failed to retrieve graybytes from: video3.mp4
FFmpeg exited with: 69
20:13:40 => ERROR: Failed to retrieve graybytes from: video4.mp4
FFmpeg exited with: 69
20:13:40 => ERROR: Failed to retrieve graybytes from: video5.mp4
FFmpeg exited with: 69
20:13:41 => ERROR: Failed to retrieve graybytes from: video6.mp4
FFmpeg exited with: 69
20:13:42 => ERROR: Failed to retrieve graybytes from: video7.mp4
FFmpeg exited with: 69
20:13:42 => ERROR: Failed to retrieve graybytes from: video8.mp4
FFmpeg exited with: 69
20:13:42 => ERROR: Failed to retrieve graybytes from: video9.mp4
FFmpeg exited with: 69
20:15:22 => ERROR: Failed to retrieve graybytes from: video10.mp4
FFmpeg exited with: 69
20:16:38 => ERROR: Failed to retrieve graybytes from: video11.mp4
FFmpeg exited with: 69
20:19:20 => ERROR: Failed to retrieve graybytes from: video12.mp4
FFmpeg exited with: 69
20:22:03 => ERROR: Failed to retrieve graybytes from: video13.mp4
FFmpeg exited with: 69
20:22:03 => Finished gathering and hashing in 00:08:46.9853702
20:22:03 => Save scanned files to disk (275 files).
20:22:03 => Scan for duplicates...
20:22:03 => Prepare list of items to compare...
20:22:03 => Scanning for duplicates in 259 files
20:22:03 => Finished scanning for duplicates in 00:00:00.0944056
20:22:03 => Highlighting best results...
20:22:03 => Scan done.
20:22:03 => Save scanned files to disk (275 files).
```

After videos were removed and ffmpeg didn't run for minutes at a time for each bad vid.  Database was cleared before this run.
```
21:33:53 => Building file list...
21:33:57 => Files in database: 259 (259 files added)
21:33:57 => Finished building file list in 00:00:04.1754685
21:33:57 => Gathering media info and buildings hashes...
21:35:01 => Finished gathering and hashing in 00:01:04.0804045
21:35:01 => Save scanned files to disk (259 files).
21:35:01 => Scan for duplicates...
21:35:01 => Prepare list of items to compare...
21:35:01 => Scanning for duplicates in 259 files
21:35:01 => Finished scanning for duplicates in 00:00:00.0396180
21:35:01 => Highlighting best results...
21:35:01 => Scan done.
21:35:01 => Save scanned files to disk (259 files).
```

**Comment by 0x90d** [comment]
I think `69` error code means conversation failed. Which ffmpeg version are you using? Regarding the timeout I don't believe its the correct way. Users can for example change the max degree of parallelism setting, this heavily affects of how many ffmpeg processes are spawned. There can also be a lot of other activity on the system. Setting such a timeout generates more issues than it solves. If you know the "corrupt" video files, just move them into a folder and exclude it from scan process.

**Comment by newadventure079** [comment]
```
ffmpeg --version
ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
```
I'm just saying if we see a thousand lines of `Error while decoding stream #0:0: Unknown error occurred
[h264 @ 0x11b00c200] hardware accelerator failed to decode picture`, ffmpeg is not going to return the info we need and we can kill it and move on

I dont know which videos ffmpeg can't parse until it runs for the first time and takes 10x as long to run.  The videos play fine and all that.  It's ffmpeg that can't get the info it needs from them

**Comment by 0x90d** [comment]
So you were using native ffmpeg binding? Which HW acceleration mode?

**Comment by newadventure079** [comment]
I dont know if I'm suing native ffmpeg binding.  I'm using the ffmpeg that is installed by homebrew.  Hardware acceleration mode is `auto`

**Comment by 0x90d** [comment]
In settings there is a checkbox to enable native ffmpeg binding. Is it on or off? I recommend to turn if off. Since you got a lot of "hardware accelerator failed" messages you should set HW acceleration mode to `none`. Let me know if both steps solves your problem.

**Comment by newadventure079** [comment]
native ffmpeg binding was off.  I set HW acceleration mode to `none` and now all but one of the errors are gone and now it finishes much faster.  Thanks for the help!

**Comment by jeffward01** [comment]
> In settings there is a checkbox to enable native ffmpeg binding. Is it on or off? I recommend to turn if off. Since you got a lot of "hardware accelerator failed" messages you should set HW acceleration mode to `none`. Let me know if both steps solves your problem.

I am just curious, why do you recommend that **Native FFMPEG binding** is turned off?

I have a Windows10 PC and am just curious why you recommend that
