### ISSUE TITLE
Excessive RAM usage while making thumbnails

### ISSUE THREAD

**Issue by Quantum00** [0x90d/videoduplicatefinder#273]
**Environment**
Windows 10 x64 Pro

**Describe the bug**
When the program finishes scanning and is in the process of making thumbnails it can exhaust all of your RAM (and start using pagefile) slowing and/or bugging every other app. This is probably worse the bigger the scanned directory is. This is happening right now on my 32gb ram pc. For reference my results are Total duplicates 447988, total duplicate groups 18625, Total Size 1.5TB. Latest version but this has been present since 3.x, not sure about 2.x.

**Expected behavior**
RAM used has to have a max % of the total? It shouldnt use it all up uncontrollably for sure.

**Comment by 0x90d** [comment]
447,988 duplicates are a lot. Uncheck Generate Preview Thumbnails in settings. Alternatively limit/lower the files it scans. Remove duplicates and then remove/raise the limit. There is no easy way to limit the memory usage of a .NET application. Not even an easy way to obtain how much memory it currently uses.

**Comment by andreipops** [comment]
i have added  a thumbnail cache which greatly reduces re scans of files. if interested im happy to add a pull request for it

**Comment by i-am-at0m** [comment]
> i have added  a thumbnail cache which greatly reduces re scans of files. if interested im happy to add a pull request for it

I know I would, for sure
