### ISSUE TITLE
Dialogs should block main window after opening

### ISSUE THREAD

**Issue by qarmin** [0x90d/videoduplicatefinder#278]
34f0806 Linux

When opening modal dialog e.g. clicking at Save to File or Load From File, then main window still is sensitive, which allow user to crate another dialog or change setting behind opened one.

https://user-images.githubusercontent.com/41945903/149650375-18dc1566-c429-434b-939e-33dea7bf9dbc.mp4

This video also show crash from https://github.com/0x90d/videoduplicatefinder/issues/277

**Comment by 0x90d** [comment]
I don't see exactly why this is a problem. But even if it would be, it should be reported to Avalonia.
