### ISSUE TITLE
App crashes when "Start is pressed", possibly too many files too enumerate

### ISSUE THREAD

**Issue by Sums123** [0x90d/videoduplicatefinder#282]
**Environment**
 - OS: Windows10
 
**Describe the bug**
Downloaded fresh install from latest daily build
Added folder, left all settings default
App crashes after I press Start

**Expected behavior**
Not a crash :)

Log:
16:05:57 => Building file list...

**Comment by Sums123** [comment]
2.0.8 works well when enumatering

**Comment by 0x90d** [comment]
Look into event viewer and post crash details

**Comment by Sums123** [comment]
Sorry, it's really strange it's working now, maybe because I restarted my PC
