### ISSUE TITLE
Help Menu / Help File

### ISSUE THREAD

**Issue by Onechristopher** [0x90d/videoduplicatefinder#287]
**Environment**
 - OS: [Any]

**Describe the solution you'd like**
Have a Help Button or Help File.  Give examples of custom selection and the parameters for each option. For example If I have duplicates on Drive D and Drive E, I want to keep the Duplicates on Drive E and select the Duplicates on Drive D. 

arg.ItemInfo.GroupId (Guid)
arg.ItemInfo.ImageList (List`1)
arg.ItemInfo.Path (String)  Example of String
arg.ItemInfo.SizeLong (Int64) Example of Int64
arg.ItemInfo.IsBestSize (Boolean)
arg.ItemInfo.Size (String) Example of String
arg.ItemInfo.Similarity (Single)
arg.ItemInfo.Folder (String) Example of String
arg.ItemInfo.Duration (TimeSpan)
arg.ItemInfo.IsBestDuration (Boolean)
arg.ItemInfo.FrameSize (String) Example of String
arg.ItemInfo.FrameSizeInt (Int32) Example of Int32
arg.ItemInfo.IsBestFrameSize (Boolean)
arg.ItemInfo.Format (String) Example of String
arg.ItemInfo.AudioFormat (String) Example of String
arg.ItemInfo.AudioChannel (String) Example of String
arg.ItemInfo.AudioSampleRate (Int32) Example of Int32
arg.ItemInfo.IsBestAudioSampleRate (Boolean)
arg.ItemInfo.BitRateKbs (Decimal)
arg.ItemInfo.IsBestBitRateKbs (Boolean)
arg.ItemInfo.Fps (Single)
arg.ItemInfo.IsBestFps (Boolean)
arg.ItemInfo.DateCreated (DateTime)
arg.ItemInfo.Flags (DuplicateFlags)
arg.ItemInfo.IsImage (Boolean)

**Comment by 0x90d** [comment]
Examples are given inside the expression builder window, below the text you copied. It requires some basic C# knowledge too. Its an advanced option for experienced users.

**Comment by zackcase20** [comment]
> Examples are given inside the expression builder window, below the text you copied. It requires some basic C# knowledge too. Its an advanced option for experienced users.

As someone who knows the basics of C#, the majority of those commands are a mystery to me. The few examples that you gave below the text are awesome, thank you for those. However, there should be an example for EVERY COMMAND. I shouldn't have to read your mind or be a CS grad to be able to copy paste commands.
