### ISSUE TITLE
Windows UI: deleting file removes wrong item from view

### ISSUE THREAD

**Issue by naxolotl** [0x90d/videoduplicatefinder#29]
**Environment**
 - OS: Windows / Linux

**Describe the bug**
 - have a duplicate group with at least 3 items
 - check the last one
 - Delete Selection -> To Recycle Bin
 - the correct file is deleted, but wrong one is removed from the UI

**Comment by 0x90d** [comment]
I've experienced the same but no idea why this happens. The code looks fine. Do you have any idea? Could that be something .NET Core preview-thing related?
