### ISSUE TITLE
The "Hardware Acceleration" combo box has no text if "none" is the initial value

### ISSUE THREAD

**Issue by CrendKing** [0x90d/videoduplicatefinder#292]
**Environment**
 - OS: Windows 11

**Describe the bug**
If the `HardwareAccelerationMode` value from the settings JSON is 0, when the app is loaded, the combo box dropdown is empty instead of showing its textual value ("none").

If it's any non-zero value, it works as expected.

**Expected behavior**
All values should show its value properly.

![VDF](https://user-images.githubusercontent.com/975235/151736026-46c4e837-9251-4a2d-a7cd-1849d46fc01b.jpg)

**Comment by CrendKing** [comment]
Not sure if this is a Avalonia bug.

**Comment by 0x90d** [comment]
Must be an Avalonia bug. If I remove the binding to the selected item and use `SelectedIndex="0"` instead its also empty.

**Comment by CrendKing** [comment]
Exactly. I don't know why the "custom commands" just below it can select the first item, given it's also a ComboBox.
