### ISSUE TITLE
Automatically closing out when finished scanning

### ISSUE THREAD

**Issue by ppsoong** [0x90d/videoduplicatefinder#293]
Sometimes when I run the program, it'll close itself out when it gets close to finishing or does finish. Then when I restart the program, I need to scan again to get the list of duplicates, which sometimes triggers the same issue and the application closes itself out.

Any ideas on how to avoid this? I don't get an error message or anything when the application quits.

Using Windows 10, VGF 3.0.

**Comment by 0x90d** [comment]
How many files to you scan and how much system memor you have? Also take a look at the event viewer, if its a crash it may contain useful details.

**Comment by ppsoong** [comment]
About 2m files, I've successfully scanned 1.7m so I thought it'd be fine. I have 64GB RAM.

Is there anything specific I should be looking for in Event Viewer? I don't see anything out of the ordinary or anything that could be the scanner.

**Comment by 0x90d** [comment]
If it would be a crash in managed code there would be two crash entries with one of it being a .NET crash log. If its a crash in unmanaged there would be one crash entry.

If you say there is none crash entry it means the application didn't crashed but got shut down. The almost only reason for this is that some other application has closed VDF and this is almost all of the time a security software like antivirus.

To be sure this is the case you can at least verify its not a memory issue by opening the task manager and check how much memory VDF uses at the end of the scan close before the crash. it might also be worth to run VDF on these 0.3m files that makes the difference only. So you can see if its a file-related issue.

Not much else I can do if its not a crash at all (no crash entry in event viewer).
