### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by dsrtusr88** [0x90d/videoduplicatefinder#295]
**Environment**
 - OS: Docker

**Describe the solution you'd like**
Has anyone created a stand-alone container for use in docker?

**Comment by piotrminkina** [comment]
I started my own project today https://github.com/piotrminkina/docker-videoduplicatefinder. I didn't know someone had already started work on it. If you still want to give it a try, run a container with bellow command.

```shell
docker volume create vdf_config
docker run \
  --name vdf \
  --rm \
  -e PUID=1000 \
  -e PGID=1000 \
  -e UMASK=002 \
  -e KEYBOARD=en-us-qwerty \
  -e TZ=Europe/Warsaw \
  -v vdf_config:/config/ \
  -v ~/Photos/:/Photos/ \
  -p 3000:3000 \
  piotrminkina/videoduplicatefinder:3.0.x
```

My project is closely based on https://hub.docker.com/r/linuxserver/digikam.

**Comment by 0x90d** [comment]
There is also https://github.com/jlesage/docker-video-duplicate-finder
