### ISSUE TITLE
Not using GPU when run with hardware accelleration set to use CUDA

### ISSUE THREAD

**Issue by cooperdk** [0x90d/videoduplicatefinder#296]
**Environment**
 - OS: Windows 11 x64

**Describe the bug**
The program is supposed to utilize the GPU when CUDA is selected in the settings area "Hardware accelleration".
It seems like it actually doesn't - at all.
I thought that the reason is that the FFMPEG binaries are compiled without CUDA, but they are 
(--enable-cuda-llvm in compilation options).

While running, the nVidia overlay reports 1-4 percent GPU utilization.

![image](https://user-images.githubusercontent.com/564150/152866492-a35130b3-8cfe-4586-85d5-4e8966e3b292.png)

I have a Geforce 1660 Ti.

**Expected behavior**
Utilization of GPU

**Comment by 0x90d** [comment]
And if you run the same commands on your ffmpeg version without VDF, does it uses more GPU then?

**Comment by cooperdk** [comment]
> And if you run the same commands on your ffmpeg version without VDF, does it uses more GPU then?

Yes, it even does use GPU when using the same binary for something else. I tried with your suggested FFMPEG which didn't change anything.

I then found out that if I set the hardware accelleration to "auto", this is what happens:

![image](https://user-images.githubusercontent.com/564150/152881093-f55a16ce-7c69-42c1-8449-609f60de9978.png)

Suddenly, it does use GPU. But I am not sure which accellerator is used.

**Comment by 0x90d** [comment]
Without using native binding, VDF just passes commands to ffmpeg. I honestly don't know why passing the command from VDF versus by yourself would cause any difference. But I don't see how I can help you. It seems to be ffmpeg related issue ignoring cuda for a reason I cannot tell you. You should probably ask the developers of ffmpeg instead.
