### ISSUE TITLE
Add option to ignore specific duplicates in future scans

### ISSUE THREAD

**Issue by 0x90d** [0x90d/videoduplicatefinder#3]

**Comment by nxrighthere** [comment]
Thanks for the great program, it helped me to find many duplicates in my collection of 4,000 video files without any problem! 🍻 

As for the issue, it would be great if this option will be implemented using an ignore list with stored checksums of files to track if they were changed or not for further re-scanning.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
