### ISSUE TITLE
Missing Thumbnail

### ISSUE THREAD

**Issue by Revan654** [0x90d/videoduplicatefinder#30]
**Environment**
 - Windows 10

**Describe the bug**
Thumbnail is missing on certain Videos, Which Previously worked (Same Video).

Video Format: MOV (aka QuickTime).

**Comment by 0x90d** [comment]
Is it always the same (single) video that misses the thumbnails?
What if you put this and a duplicate into a single folder and scan this folder only (with an empty database)
What do you mean with "previously"? Which version are you using at the moment and on which version it has worked?

**Comment by Revan654** [comment]
All the Previous versions created the thumbnail fine, So far it's always the same video. It was with a clean database.

I'm using the latest version.

**Comment by 0x90d** [comment]
Latest release version or latest commit (self compiled)?

**Comment by Revan654** [comment]
> 
> 
> Latest release version or latest commit (self compiled)?

Release, VS2017 doesn't officially support .netCore 3.0(Since it's still in Preview Stage).

**Comment by Revan654** [comment]
Getting following error on bunch of Files:

13:45:29	OS: Microsoft Windows 10.0.17763
13:47:24	Building file list...

13:48:08	Start scan
13:50:28	FFMpeg timeout. File: XXX
13:50:28	FFMpegException, file: XXX, reason: FFMpeg timeout. File: XXX (exit code: -2)
13:51:04	FFprobe error: An item with the same key has already been added. Key: comment, File: XXX
13:53:18	FFprobe error: Expected CurrentDepth (1) to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed. LineNumber: 1 | BytePositionInLine: 0., File: XXX

There also even larger Number of missing Thumbnails this time around, This includes h.264, wmv, flv, etc...

You might want to consider ditching ffmpeg and use a FrameServer a Long with .net's bitmap instead.

This Code might be Useful (It will need to be converted to C#).

Link: https://github.com/Revan654/Thumbnailer/blob/1b19bae7663ce1d4e82175aa893822925879e044/Thumbnails.vb#L99
