### ISSUE TITLE
Cannot find ffmpeg

### ISSUE THREAD

**Issue by AkumuNyaaaa** [0x90d/videoduplicatefinder#301]
Hi.

I got videoduplicatefinder and ffmpeg then I got stuck the instruction since I put ffmpeg into videoduplicatefinder and nothing results.
Will you help me, to do something for your file?

**Comment by 0x90d** [comment]
Because you deleted/ignored the issue template where you would have to provide the OS you are using, no. But you can find the instructions here as well: https://github.com/0x90d/videoduplicatefinder#requirements

**Comment by AkumuNyaaaa** [comment]
To be honest, I'm getting lazy and I was getting confused of these instruction?
