### ISSUE TITLE
mouse selection vs ticking and group selection

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#303]
**Environment**
 - OS: Windows 10 x64

**Describe the solution you'd like**
I think that selecting the images to delete (after scan) should be made only by mouse selection and/or by the auto selection menu (which does a good job most of the time based on size, quality). This has advantages which are primarily easier selection methods (hold shift + click or hold ctrl + click for picking one by one). Also the group selection method is basicaly not existent, so you have to go one by one right clicking over the groups.

Use scenario and why I ask this:

1. I make the scan, results are shown.
2. I use the auto selection by size and quality since it works ok and helps.
3. I start the checking manually to corroborate the selection is OK before deletion. Find some false positives and that the program still recognizes hardlink to files as duplicates.
4. I keep scrolling and find lots of recent galleries that are shown as false dups in different places. (big galleries)
5. I cannot resort to automatic selection again or filters since those will deselect my previous work of manually checking and I cannot select many groups at once because of the lack of selection methods. I have to switch to "full manual mode" and go right click ->selected group -> mark as "not a match"..  

If I could use the mouse to select like in windows (or linux, its the same afaik) I could easiliy select those false positives and tell the program to ignore them. 
Also bear in mind that the selection method should stop using ticking because this would confuse which one of the selection methods are being taken into account.

PS: unrelated but FFMPEG binding keeps crashing the app so I had to turn it off. Downloaded latest version from releases today before using the app.

**Comment by 0x90d** [comment]
The current advantage is that users can tick/select items and still do other stuff (for example double clicking to play the video or right click on a single item and open it in explorer/shell) while the selection is still retained. Selection only by mouse would break this. I'm aware of the confusion which selection is meant, because mouse selection is what a user knows the most. But I don't believe giving up the current advantage is worth it.

**Comment by masterofobzene** [comment]
Maybe a mixture? being able to tick items but using normal selection mechanics (+ ctrl, + SHIFT, etc) also giving the "blue selection"
It would have the best of both worlds IMO, you get easier selection mechanics  while also keeping ticking mechanics (sticky selection)

**Comment by 0x90d** [comment]
> till Shift + click to select all items between a range would be cool for faster selection.

You can do this already, Shift + click + pressing Space.

> And please don't forget groups! they are not selectable! this is IMO the most needed change.

Do you want to make a PR?

**Comment by Derducken** [comment]
@0x90d I tried doing that (Shift + clicking to select a range, then pressing space) and it only adds one checkmark on the last file clicked. Shouldn't the proper "behavior" be to add checkmarks to all highlighted files?

**Comment by jeffward01** [comment]
> @0x90d I tried doing that (Shift + clicking to select a range, then pressing space) and it only adds one checkmark on the last file clicked. Shouldn't the proper "behavior" be to add checkmarks to all highlighted files?

I just tested this, it worked for me just fine

**Comment by chuckgcs** [comment]
> 
To use the "(Shift + clicking to select a range, then pressing space)" feature to select a range; do it this way
* Left-click on the first selection of your range
* Hold down shift while you click on the last selection of your range
* RELEASE THE SHIFT KEY after clicking on the last selection in your range
* Press the space bar which should check all of the selected (blue) range
