### ISSUE TITLE
Possibility to integrate MediaInfo

### ISSUE THREAD

**Issue by Samhayne** [0x90d/videoduplicatefinder#305]
**Environment**
 - OS: Any

**Describe the solution you'd like**
First: Great tool! Really! 😊

VDF could be even more awesome with a shortcut for opening a video in mediainfo. 

I like to compare (very similar) duplicates in mediainfo and this always requires opening the explorer folder via context menu, finding the file, and opening it in mediainfo - same procedure for every duplicate.

**Comment by Maltragor** [comment]
There is an option to configure user define commands, see #248

This allows to override the default open/play action and the 'open in folder' action.
So if you can do without one of the two default actions, you could use this for opening the file in mediainfo.

_Furthermore there are the 'open multi' commands which are called as soon as at least two files are selected.
Of course you could also use them for other purposes.
So by selecting any other file besides the one you want to open and using the intermediate step with a shell script to call your program only with the first file name passed._

Shortcut: Pressing return while the thumbnails or the file name is selected will execute the corresponding command.

> opening the explorer folder via context menu, finding the file..
To improve the behavior the custom 'open in folder' command was intended in the first place. So for example in Linux in combination with a suitable file manager the command can be specified in such a way that the file manager marks the appropriate file directly when opening the folder.

**Comment by Samhayne** [comment]
Thanks for your reply @Maltragor !!
Wouldn‘t have figured it out without your explanation and the link provided.
Adding “c:\Program Files\MediaInfo\mediainfo.exe“ %f and selecting 2 video files (i.e. not ticking the checkbox but selecting two video entries while holding ctrl) and then chosing „Open in folder“ indeed worked out as mediainfo is able to open multiple files which you can then toggle from the top down menu on top of its window.

„Open Multiple“ + multiselect + Enter also works.

I hope I remember how it works two weeks from now - but in case I forget I at least can look it up here. :)
👍
