### ISSUE TITLE
I hope VDF can search the result list

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#308]
Thanks for you guys.

I hope VDF can find one specific video in result list.

As the result list is too long, it's hard to find specific video.

I hope VDF cand search the ressult list.

**Comment by 0x90d** [comment]
Check "Filter / Sort" then you can search for a video
![image](https://user-images.githubusercontent.com/46010672/160768662-48e27cdd-9c85-495a-91ec-157bf8c931ed.png)
