### ISSUE TITLE
Expression Builder should respect filtering on Scanning tab

### ISSUE THREAD

**Issue by thebrokenfacade** [0x90d/videoduplicatefinder#311]
**Environment**
 - OS: Any

**Describe the solution you'd like**
The expression builder should respect path and extension filtering done on the Scanner tab.

Say a scan is done at 95% similarity and there are 1000 duplicate groups. In the Scanner tab, I use the path filter to narrow down the results to only groups with items from a single directory at a time so that visual inspection is easier and can be broken up over several sessions. Then the expression builder is used to select only files whose name contains a specific string.

Here is a sample situation:

Scan 'dir' with 95% similarity
Scanner > Filter / Sort > Path: 'dir1'
Scanner > Select Custom... > 'arg.ItemInfo.Path.Contains("bname")'

dir/
->dir1/
--->aname1.jpg
--->aname2.jpg
--->bname1.jpg
->dir2/
--->bname1.png
--->bname2.png

I intuitively expect that only files from 'dir1' that match the string 'bname' would be selected, but VDF seems to select all files that match 'bname' even if they are not in 'dir1'. In this case I expect only 'bname1.jpg' to be selected, but 'bname1.jpg', 'bname1.png', and 'bname2.png' will be selected for deletion even though 'bname1.png' and 'bname2.png' are not even shown on the Scanner tab with the path filter applied. I have now unintentionally deleted 'bname1.png' and 'bname2.png'. Nice!

I hope this makes sense and is not too difficult to implement. Thanks!

**Comment by 0x90d** [comment]
Expression builder always runs against the entire scan results. Filter applies to the visual only. This by design. You can easily do what you want using the expression builder only. `arg.ItemInfo.Path.Contains("bname") && arg.ItemInfo.Path.Contains("dir1")`
