### ISSUE TITLE
false positive samples?

### ISSUE THREAD

**Issue by rezad1393** [0x90d/videoduplicatefinder#316]
**Environment**
linux x64

I use this app to find similar videos and when I set the number to 98% it works great.
but even with that number it finds videos that are NOT the same video but different but it give a very high number for them.
this happens with anime mostly. and not all anime.

is there a way for me to report these?
maybe their names and the episodes?

**Comment by 0x90d** [comment]
No, it is up to the user to filter them out. Increase thumbnail count might help. Or just blacklist them so they don't appear on every scan.
