### ISSUE TITLE
option request: ignore linked folder and files

### ISSUE THREAD

**Issue by rezad1393** [0x90d/videoduplicatefinder#317]
**Environment**
linux

I have files and folders that are linked (soft-linked) to another file or folder.
vdf finds this as 100% duplicate.
can you add a way for vdf to NOT analyze folders and files that are just links to others?

**Comment by 0x90d** [comment]
There is an option to exclude ReparsePoint. That's everything the .NET runtime offers at this moment. If that is not enough then something like that has to be added to the .NET runtime first before I can provide it.

**Comment by Maltragor** [comment]
The "exclude ReparsePoint" should work for so soft links, but you have to activate it before the first scan. So if you have already scanned without activating it, it's necessary to clear the database first. The option only prevents adding linked file to the database.

**Comment by rezad1393** [comment]
> The "exclude ReparsePoint" should work for so soft links, but you have to activate it before the first scan. So if you have already scanned without activating it, it's necessary to clear the database first. The option only prevents adding linked file to the database.

clear or delete?
