### ISSUE TITLE
Unable to find package SixLabors.ImageSharp with version (>= 2.1.3)

### ISSUE THREAD

**Issue by kattjevfel** [0x90d/videoduplicatefinder#321]
**Environment**
 - OS: Arch Linux

**Describe the bug**
Trying to build ca808db3be452c2f0e22447037bcc3654763fca7 gives me the following errors:
```
/home/katt/build/videoduplicatefinder/VDF.Core/VDF.Core.csproj : error NU1102: Unable to find package SixLabors.ImageSharp with version (>= 2.1.3) [/home/katt/build/videoduplicatefinder/VideoDuplicateFinder.sln]
/home/katt/build/videoduplicatefinder/VDF.Core/VDF.Core.csproj : error NU1102:   - Found 19 version(s) in nuget.org [ Nearest version: 2.1.2 ] [/home/katt/build/videoduplicatefinder/VideoDuplicateFinder.sln]
/home/katt/build/videoduplicatefinder/VDF.GUI/VDF.GUI.csproj : error NU1102: Unable to find package SixLabors.ImageSharp with version (>= 2.1.3) [/home/katt/build/videoduplicatefinder/VideoDuplicateFinder.sln]
/home/katt/build/videoduplicatefinder/VDF.GUI/VDF.GUI.csproj : error NU1102:   - Found 19 version(s) in nuget.org [ Nearest version: 2.1.2 ] [/home/katt/build/videoduplicatefinder/VideoDuplicateFinder.sln]
/home/katt/build/videoduplicatefinder/VDF.GUI/VDF.GUI.csproj : error NU1102:   - Found 0 version(s) in AvaloniaCI [/home/katt/build/videoduplicatefinder/VideoDuplicateFinder.sln]
```

The latest version of SixLabors.ImageSharp on nuget.org is 2.1.2, is this a typo?

EDIT: I see now that 2.1.3 was released 10 hours ago on GitHub, but hasn't made it to nuget yet. You're too fast! :P

**Expected behavior**
Being able to find the dependencies and build the application.

**Comment by Maltragor** [comment]
In the releases.yml there is the line:
https://github.com/0x90d/videoduplicatefinder/blob/ca808db3be452c2f0e22447037bcc3654763fca7/.github/workflows/releases.yml#L44

Since on my system `dotnet nuget list source` also lists the entry as a second package source, I probably had a similar issue some time ago and added the source.
