### ISSUE TITLE
Latest version (dowloaded today) doesn't detect dups in images

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#322]
**Environment**
 - OS: [Windows 10 x64]

**Describe the bug**
On a folder with dups, the program fails to find them even going as low as 86%. No file filters applied. Getting no results (0).

**Expected behavior**
AntiDupl.NET finds many dups (real dups) in the same folder while VDF fails to find any.
Talking about 76 vs 0.

**Comment by 0x90d** [comment]
Post screenshot of your settings and upload example files.

**Comment by newadventure079** [comment]
I'm seeing the same thing.  VDF is not detecting any dupes at all, when an older version is

**Comment by Deiwulf** [comment]
Same

**Comment by 0x90d** [comment]
Instead of posting "I have this issue too" you could have read my comment and uploading example files and screenshot of your settings.

Also see what the log file says about the files it misses. Also on VDF click on `Database` and then `Edit...` search for the files and verify it has nothing checked at the right 4 columns.

**Comment by 0x90d** [comment]
Try latest version and let me know if it fixed it. If not => https://github.com/0x90d/videoduplicatefinder/issues/322#issuecomment-1160035797

**Comment by Deiwulf** [comment]
Sadly don't have the previous sample any more, but it seems to catch 100% dupes correctly now. No crashes so far either.

**Comment by kattjevfel** [comment]
I'm running into this, and editing the database shows that every single picture has "HasThubmanilError" ticked. and I mean _evey, single, one_.

Here's one of many pictures that failed: https://too.lewd.se/52f914d69cd2_imgur_yWLGX6r.jpg but really, it happens to any picture.

Log has a ton of these (vscode counts 19999+):
```
11:14:07 => Exception, file: /mnt/jupiter/Temp/Camera/2022-03-28_16-24-49.jpg, reason: Method not found: 'Boolean SixLabors.ImageSharp.Image`1.TryGetSinglePixelSpan(System.Span`1<!0> ByRef)'., stacktrace    at VDF.Core.Utils.GrayBytesUtils.GetGrayScaleValues(Image original, Double darkProcent)
   at VDF.Core.ScanEngine.GetGrayBytesFromImage(FileEntry imageFile) in /home/katt/build/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 568
```

some of these too:
```
11:14:00 => Exception, file: /mnt/jupiter/Temp/c84e219.jpg, reason: Method not found: 'Boolean SixLabors.ImageSharp.Image`1.TryGetSinglePixelSpan(System.Span`1<!0> ByRef)'., stacktrace    at VDF.Core.Utils.GrayBytesUtils.GetGrayScaleValues(Image original, Double darkProcent)
   at VDF.Core.ScanEngine.GetGrayBytesFromImage(FileEntry imageFile) in /home/katt/build/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 552
```

I hope this helps.
