### ISSUE TITLE
Native ffmpeg binding only works if the ffmpeg files are placed in the root dir of VDF

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#323]
**Environment**
 - OS: macOS

**Describe the bug**
Native ffmpeg binding doesn't work if the ffmpeg files are in `bin` subdir
Native ffmpeg binding only works if the ffmpeg files are placed in the root dir of VDF
Instructions from readme:
`Extract ffmpeg and ffprobe into the same directory of VDF.GUI.dll. Or into a sub folder called bin`

**Expected behavior**
Native ffmpeg binding should work if the ffmpeg files are placed in a subdir named `bin`

**Comment by 0x90d** [comment]
Can you upload the ffmpeg files please? I only find static builds of ffmpeg for macOS.

**Comment by newadventure079** [comment]
I can only find static builds of ffmpeg for macOS too.  So I downloaded this https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.0-latest-win64-gpl-shared-5.0.zip instead. This is sort of related to #319

**Comment by 0x90d** [comment]
Very much related. This won't work. The ffmpeg binding I am using says that it needs ffmpeg installed via homebrew and it needs ffmpeg.RootPath set to the folder of ffmpeg installation. Unfortunately I dont know this folder. If you can figure it out, I will set.
