### ISSUE TITLE
VDF cannot be minimized

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#326]
**Environment**
 - OS: macOS

**Describe the bug**
![Untitled](https://user-images.githubusercontent.com/84156407/174502874-0f9dcc52-e73b-4d39-a208-601ab0864520.gif)

**Expected behavior**
VDF should be able to be minimized

**Comment by 0x90d** [comment]
Guess that's an Avalonia bug and should be reported here instead: https://github.com/AvaloniaUI/Avalonia/issues

**Comment by 0x90d** [comment]
Someone else has reported it allready so you can track this issue here to see when it gets fixed: https://github.com/AvaloniaUI/Avalonia/issues/8335
