### ISSUE TITLE
hardware acceleration value can revert back to null after an app restart

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#327]
**Environment**
 - OS: macOS

**Describe the bug**
The hardware acceleration value can revert back to a blank string after app restart

The Hardware Acceleration value is lost after a restart of the app.  That'd explain why no dupes would be found without my realizing that value got reverted by to null

First posted as a comment https://github.com/0x90d/videoduplicatefinder/issues/325#issuecomment-1159977705

![Screen Shot 2022-06-20 at 12 11 24 AM](https://user-images.githubusercontent.com/84156407/174536737-055ccfd9-3ccc-4bd5-b354-003160a076c1.jpg)

**Expected behavior**
Hardware Acceleration value is retained after a restart of the app

**Comment by 0x90d** [comment]
What are the steps to reproduce? Also this must be a visual only bug (I expect an Avalonia bug again) because its bound to an Enum which cannot be null.

**Comment by newadventure079** [comment]
Steps to reproduce:

- Open VDF
- Select a Hardware Acceleration value
- Close the app
- Open VDF
- Observe there is no value in the Hardware Acceleration dropdown

I exported the settings before and after the restart of the app and both times the value was `"HardwareAccelerationMode":0`

I only noticed this because if I dont have a hardware acceleration value set to `none` with native ffmpeg bindings on macOS, no dupes will be found.  So half the time I'm wondering why the app isn't working and then I stumbled upon the hardware acceleration value being reset back to null

**Comment by 0x90d** [comment]
`0` is `none`. I did a quick look and found couple of related issues reported at Avalonia that the initial selected item is not properly updated: https://github.com/AvaloniaUI/Avalonia/issues?page=2&q=is%3Aissue+is%3Aopen+combobox
