### ISSUE TITLE
Installation instructions for macOS are incorrect

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#328]
**Environment**
 - OS: macOS

**Describe the bug**
From #325

> For non-native mode that is using homebrew. For native mode that is also using homebrew but that is currently not supported on macOS in VDF because of the comment I linked to.

The macOS instructions should be updated in the readme then. readme says `After installing FFmpeg & Ffprobe (see above)`. Above tells them to go to ffmpeg.org and download it. The instructions should say to install it via homebrew

**Expected behavior**
Proper instructions for macOS

**Comment by newadventure079** [comment]
The instructions of 
```
Now open Terminal in VDF folder and give VDF.GUI executable rights `sudo chmod -R 755 VDF.GUI`. Now right click on `VDF.GUI` and choose to open with terminal.
```
 are still valid and will need to be performed.

The mac instructions should almost mirror the linux instructions

**Comment by astraeus-sithu** [comment]
@0x90d this app looks awesome and exactly what I've been looking for (finding similar movies, with different resolution), but I am not able to run it on MacOS Monterey v12.4 on apple silicon M1.

I did `brew install ffmpeg` and also tried putting the ffmpeg/ffprobe binaries in the same folder as VDI.GUI.dll
I tried chmod 755 and 777 to the VDI.GUI file
When I try `./VDF.GUI` it results in this error: `zsh: killed     ./VDF.GUI`
I've tried opening system preferences and 'allow anyway' in Security since it's from unidentified developer, but it doesn't seem to be openable from the terminal.

Thanks for your help!

**Comment by newadventure079** [comment]
Look at the Console for the logs.  It's probably related to #345

**Comment by astraeus-sithu** [comment]
@newadventure079 for some reason, I am not getting any error messages related to this in the Console.app in system.log or elsewhere. Agree it's probably related, and hope it gets resolved soon.

**Comment by RevENGE-code** [comment]
Has anyone been able to run it on m1 yet? I am faced the with same `zsh: killed     ./VDF.GUI` issue. I am able to run the intel version, but not the arm one.

**Comment by romanr** [comment]
> Has anyone been able to run it on m1 yet? I am faced the with same `zsh: killed ./VDF.GUI` issue. I am able to run the intel version, but not the arm one.
> 
> Edit: i ran `codesign -s - ./VDF.GUI`, then it worked

For me VDF.GUI is plain folder. What am I doing wrong?
```
codesign -s - ./VDF.GUI
./VDF.GUI: bundle format unrecognized, invalid, or unsuitable
```

**Comment by dennisrcao** [comment]
> The instructions of
> 
> ```
> Now open Terminal in VDF folder and give VDF.GUI executable rights `sudo chmod -R 755 VDF.GUI`. Now right click on `VDF.GUI` and choose to open with terminal.
> ```
> 
> are still valid and will need to be performed.
> 
> The mac instructions should almost mirror the linux instructions

I'm confused as to how to do this. First I installed ffmpeg successfully.
 Then in my terminal I cd'd into the "videoduplicatefinder" folder, then ran `sudo chmod -R 755 VDF.GUI` , but when I navigate to path videoduplicatefinder > VDF.GUI it is a folder - not something I can "open with terminal" or an executable.
