### ISSUE TITLE
Failed to execute process, unknown error number 86

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#330]
**Environment**
 - OS: macOS

**Describe the bug**
I downloaded `App-osx-x64.tar.gz`, extracted it and did `sudo chmod -R 755 VDF.GUI` and when I launch VDF.GUI in the terminal, I get the following error:

```
/Users/me/Downloads/outputFolder/VDF.GUI ; exit;
exec: Failed to execute process '/Users/me/Downloads/outputFolder/VDF.GUI', unknown error number 86

[Process completed]
```
I have a Mac Studio with an M1 Max

I think it was when I tried to launch VDF.GUI with sh or bash or some other method, I got:
```
/Users/me/Downloads/outputFolder/VDF.GUI: Bad CPU type in executable
```

**Expected behavior**
To be able to launch the app on macOS

**Comment by newadventure079** [comment]
I didn't have Rosetta 2 installed on my new computer. Normally you get a prompt but I guess that doesn't happen when you try to launch something that needs Rosetta via the command line

**Comment by kenny000001** [comment]
So how do you fix this
