### ISSUE TITLE
HOW DO I SELECT ALL ITEMS EXCEPT THE ONE WITH THE HIGHEST BIT RATE?

### ISSUE THREAD

**Issue by paulie202** [0x90d/videoduplicatefinder#336]
I am attempting to pick all items within a bunch of duplicate videos EXCEPT the one with the highest bit rate.

My attempts:

arg.ItemInfo.IsBestBitRateKbs (0)

arg.ItemInfo.IsBestBitRateKbs > 0

arg.ItemInfo.IsBestBitRateKbs = 0 

HELP

**Comment by 0x90d** [comment]
`arg.ItemInfo.IsBestBitRateKbs == false`
