### ISSUE TITLE
Interface tweaks

### ISSUE THREAD

**Issue by Derducken** [0x90d/videoduplicatefinder#337]
**Environment**
 - OS: All. Testing on Windows 10, but the suggestions below should apply to all versions when run on *any* a desktop environment.

**Describe the solution you'd like**
The app is awesome and I've been looking for ages for something like this that would actually work. Plus, it's also very usable, and relatively fast. So, kudos on a great job on everything. And yet, there's a little tweak that could make it even better: a little UI shuffling.

As it is, after you perform a search, if you also enable filters, you're "losing" around 1/5th to 1/4th of the screen's height for "UI elements".

I'm currently counting 5 bars:

1. Main menu ((Scanner, Settings, Log)
2. "Action buttons"
3. Selection & filtering & zooming
4. Path, Sort, Type
5. Bar on top of the list, describing the contents of each column.

So... Suggestion time.

1. Merge 1 + 2, and have the "action buttons" show after the menu. Use some whitespace and a vertical divider to show visually "they're not parts of the same thing".
2. Merge 3 + 4. Then, *hide them* "behind" a button on the first bar, called "Selection & Filtering", or something along those lines. Like Firefox's Bookmarks bar, the user could click on that button to insta-show/hide the Selection & Filtering bar.

As for the bar on top of the list, and the way information is presented, I think it doesn't help as much as it could when comparing videos. That's because the user's eyes have to "jump between different points" to check how the resolution, Bit Rate, etc. differ among clips. I believe it would help usability if each element was displayed on its own column. Ideally the user could choose which information to show, and where, but I know I'm asking too much :-)

This way the interface would look more compact and "leaner", the same actions, options, and information would still be available, and there'd be more space for at least one or two more entries in the main media list.

**Comment by 0x90d** [comment]
Thank you for the input and detailed suggestions!

While I'm currently working on some UI improvements I revisited this issue. But I think this is a bit outdated. Main menu are now tabs so I cannot merge them with action buttons. It also would be odd if actions are shown when you're browsing the settings. Selection and filter are one bar now. Don't make much sense to hide them with a button as you don't gain any extra (vertical) space.

With that said I'm closing the issue now but you're more than welcome to share ideas on the current / upcoming design.
