### ISSUE TITLE
Some files are not being included in the results

### ISSUE THREAD

**Issue by Kutabarie** [0x90d/videoduplicatefinder#338]
**Environment**
 - OS: Windows

**Describe the bug**
I was comparing the performance between the 3.0 and 2.0 versions, and I noticed that some of the files that were not showing any details in the 2.0 version (eg: 00:00:00 time, 0 fps, 0 kbps) were not being included in the results in the 3.0 version.

**Expected behavior**
The file should at least show up in the respective group even with no video information.

**Comment by 0x90d** [comment]
If the time is zero the file is not included in scan at all. Also the files you mention seem to be corrupted. You can try using ffmpeg to fix them
