### ISSUE TITLE
No Proccess Can Be Found for This Object (Program Crash)

### ISSUE THREAD

**Issue by Revan654** [0x90d/videoduplicatefinder#34]
<img width="1603" alt="untitled2" src="https://user-images.githubusercontent.com/38091898/53700074-a7362400-3dbc-11e9-910c-bcde810b222e.png">

It also looks like the UI is completely messed up, each control has a different size.

<img width="326" alt="untitled" src="https://user-images.githubusercontent.com/38091898/53700181-a356d180-3dbd-11e9-9880-22d05ce50cc5.png">

One Small Suggestion, You might want to ditch WinForm API and move to Win32 For Dialog Selection. 

For Folder there isn't one for win32(I have no idea why MS never included it) 

In that case You can build one from the ground up or use: https://github.com/caioproiete/ookii-dialogs-wpf

**Comment by 0x90d** [comment]
Different UI control size is a known .NET Core WPF bug, see https://github.com/dotnet/wpf/issues/334. Folder dialog has been added to .NET Core natively which is available in winforms and wpf, see https://github.com/dotnet/winforms/pull/57

Regarding the process issue there have been some changes in latest commit which might have already fixed this problem.

**Comment by Revan654** [comment]
>  dialog has been ad

If I'm reading it correctly your still using WinForm inside WPF. I was talking about native Win32 API. Since WinForm API & Win32 are two different APi's. Not sure why we need two of them. Nor why Folder API was never included with WPF in the first place.

As for the UI, 

Try adding the Following and see if it helps.

To App.config:

` <runtime>
    <AppContextSwitchOverrides value="Switch.System.Windows.DoNotScaleForDpiChanges=false" />
</runtime.`

To app.manifest File(Also Included Long Path, For Older Systems, Has to be added to source Code as well):

- dpiAwareness is the important one, Since dpiaware is already enabled by default with WPF.

`<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitor</dpiAwareness>
    </windowsSettings>
  </application>`

**Comment by crfloyd0932** [comment]
I get this same error if i try and do anything more than 1 thumbnail. tried deleting the db and settings xml and it still happens. if you leave it at 1 thumbnail, it works fine.

**Comment by nwgat** [comment]
am also getting this, using latest windows binary https://github.com/0x90d/videoduplicatefinder/releases/tag/2.0.6
