### ISSUE TITLE
Add an "ItemIsSelected: <boolean>" property to the JSON data produced by "Export Scan Results"

### ISSUE THREAD

**Issue by jamesonknutson** [0x90d/videoduplicatefinder#341]
**Environment**
 - OS: Windows

**Describe the solution you'd like**
I would like for the "Export Scan Results" function to include a boolean property indicating whether or not the entry is / was selected in the GUI at the time of the export being created.

I often use VDF to scan for duplicate entries, then I export the scan results of those duplicate entries and employ some programmatic actions later on from the data in the export. For example, I have a simple script that takes input of the exported scan JSON, identifies the best file in each group by my own custom logic, then determines what actions to take on all the files within that group. I personally choose to do this outside of the GUI itself because there are often additional actions that I have to take to fit this tool to my use case, for example finding other files that have references to a path of a duplicate, inferior file, and updating their reference to the superior file-- symbolic links would not work for this case due to some weird and non-standard behavior of other downstream applications that consume said files with references to duplicated files.

Having a simple `IsSelected: <boolean>` property included in the exported JSON data for each entry would allow me to manually use the GUI tool to find the best item in each group, select them, then export the JSON data, eliminating the need for me to try and write logic that determines which file is the best file in the group. The reason I don't want to have to write logic that determines the best file in the group is because there are many edge cases that I would have to account for that are better handled by manual human selection.

I can expand on my own personal use cases if needed.

**Comment by 0x90d** [comment]
Instead of using the export to file function you can simply save scan results to disk when closing VDF. It will write a backup.scanresults file. This is also just a JSON file, it should contain the checked state.

**Comment by 0x90d** [comment]
There is now an export / import scan results option.
