### ISSUE TITLE
ASP: Security policy would not allow process: 9724, /Applications/videoduplicatefinderarm64/VDF.GUI

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#345]
**Environment**
 - OS: macOS

**Describe the bug**
Download the `videoduplicatefinderarm64` package on an arm64 Mac
Run VDF.GUI
Terminal outputs:  `fish: Job 1, './VDF.GUI' terminated by signal SIGKILL (Forced quit)`
Mac System Logs show: 
```ASP: Security policy would not allow process: 9724, /Applications/videoduplicatefinderarm64/VDF.GUI```

**Expected behavior**
App launches with no crash

**Comment by 0x90d** [comment]
Either sign the application yourself or allow running unsigned applications on your mac.
