### ISSUE TITLE
Make "not-a-match" location/filename independent

### ISSUE THREAD

**Issue by uNderdog101** [0x90d/videoduplicatefinder#346]
**Environment**
 - OS: Any

**Describe the solution you'd like**
Currently, if you rename/move a file that is part of a "not-a-match" pair then that pairing is essentially moot, since the pair shows up as a match again if you run the same search after moving/renaming.

It would be great if the "not-a-match" could be based on something intrinsic to the file and not dependent on location,/filename, like an MD5 hash. That way you could move/rename the files to your hearts content without losing the "not-a-match".

A drawback might be that the "cleanup database" would now not search for files that are no longer there, but would need to check all files for hashes in the list and remove pairings in which either entry no longer exists.

**Comment by 0x90d** [comment]
Any kind of hash takes time to generate. It would have to generate such a hash for all files, this is not an option as VDF is designed to be fast. Also it is said that the not match function only works if the files in this match remains the same. As soon as a new file gets added, it will reappear.

So either move the files first or just mark them as not a match again.
