### ISSUE TITLE
[Feature Request] - Add various interfaces (CLI, API, SDK) to communicate with the VDF.Core module

### ISSUE THREAD

**Issue by jeffward01** [0x90d/videoduplicatefinder#348]
**Environment**
 - OS: Any

**Describe the solution you'd like**

**Intro**
This is a fantastic tool - big thank you to all the developers and contributors who participate and open up Issues. It is very cool of you!

**Request**

It would be **very** cool to see this code 'extracted' and made a bit more modular so that users can work with the code in various ways, including _(in no particular order)_:

* **1.)  API interface** 
    * A user can interact with the software from an HTTP api of sorts (Like many of you, I prefer a REST API in comparison to RPC)
 * **2.) RPC Interface**
    * This is 'classic' as many torrent clients have an RPC interface. I suggest this only because it seems to be favorable for the torrent clients, I am not sure why. Perhaps someone can enlighten me.  But this is a popular mode of interaction
 * **3.) CLI Interface**
    * For obvious reasons this would be very helpful
 * **4.) SDK C# interface:** 
     * Would be very cool to be able to extract this into a nuget package so it can be included in other libraries as the 'Core Module'
     * I understand that perhaps, the code would have to be modified to eliminating 'locking' or freezing. Converting the code to a more async - SDK friendly sort of behavior

**Comment by 0x90d** [comment]
For something like that the core module must be a separate github project you can reference to and ideally also a nuget package. I don't have plans for that and I may integrate the core into the GUI in the future.

**Comment by jeffward01** [comment]
Thats cool, this is something that is on my list of things to do and create a PR for (or new repo) I think this will be a very cool thing to have

**Comment by 0x90d** [comment]
> Please don't do that, there's not really anything to gain

Actually there is, it would allow me to publish as single executable (#161). Because right now the github action script fails when trying to publish as single file due to having two projects and I dont have the github skills to fix that otherwise. And it would get rid of having to duplicate each setting.

**Comment by 0x90d** [comment]
I don't have any plans nor time for this. Anything like that can be done via a fork if necessary.
