### ISSUE TITLE
.NET 7.0 support

### ISSUE THREAD

**Issue by kattjevfel** [0x90d/videoduplicatefinder#351]
**Environment**
 - OS: Arch Linux

**Describe the solution you'd like**
I'd like the ability to run this with .NET 7.0.

**Comment by 0x90d** [comment]
.NET 7 contains too many serious issues. You can download the source and compile it against .NET 7 SDK yourself.

**Comment by kattjevfel** [comment]
Even when compiling with .NET 7, it still seems to require NET 6, that is the issue here...
