### ISSUE TITLE
Larger Video File Size Shows as Red Instead of the Smaller File

### ISSUE THREAD

**Issue by Teflon98** [0x90d/videoduplicatefinder#352]
- OS: Windows

The larger value for Time, Resolution, Bit Rate, Audio Sample Rate is always shown as Green.  The Size parameter is opposite of this with with the smaller file size showing up as green and the larger file size showing up as red.

The larger file size should be Green and the smaller file size should show up as Red.  For videos a larger file size is generally associated with a better quality file.

BTW: This tool is AMAZING!

**Comment by 0x90d** [comment]
> a larger file size is generally associated with a better quality file

I cannot agree with that. VDF is supposed to save space on your hard drives. So, a smaller video file is better than a larger. Green/Red is also just a visual indicator that makes it easier to see if and how there are differences. Its up to the user to decide which to delete and which to keep for whatever reason.

**Comment by Teflon98** [comment]
Thanks for the quick response.

I hear what you're saying in regards to saving space on your hard drive.  I think I'm looking at the same goal from a different viewpoint:  I'm also looking at saving space by getting rid of duplicate files.  My goal isn't to get rid of the _biggest_ file: It's to get rid of what I consider the _least desirable_ file.

From reading what you wrote, I would suggest that it's a bit subjective on what the user may want to see as red or green.  To me, there's an inconsistency in that larger values are always green except for size.

Of course, thanks again for the quick response and the great software.
