### ISSUE TITLE
Swap Duplicate Filenames

### ISSUE THREAD

**Issue by Teflon98** [0x90d/videoduplicatefinder#353]
Windows

It would be super handy to be able to swap the filenames of the pair of duplicates.  As an example, if you found a duplicate pair but wanted to keep the better version of the file but use the name of the file you were going to delete.

When you right-click on the hash, there's a fly-out for Rename et al.  It would be great if this fly-out also had "Swap Filenames" as an option.  Of course, the extensions would be untouched.

**Comment by 0x90d** [comment]
How would that work when there are like 4 duplicates of a video? Which files get renamed to which other filenames?

**Comment by Teflon98** [comment]
I would suggest that it would only be available when there's only a pair of duplicates, or if there's more than a pair, when two of the files are checked.

**Comment by 0x90d** [comment]
For me this is a too specific request I don't believe many people will use. Quite similar to all these "Check duplicates that match XY". I'll leave this open so people can vote on it.
