### ISSUE TITLE
The Import of ".scanresults" file with thumbnails is missing. Or: How to import previously exported .scanresults file with thumbnails?

### ISSUE THREAD

**Issue by tokariu** [0x90d/videoduplicatefinder#356]
**Environment**
 - OS: Win
 - VDF v3.0

**Describe the bug**
After a long Scan I wanted to export the Scan results with thumbnails. I choose "Export Scan Results" -> "To File including thumbnails". I get a file like "myscan.scanresults" which obviously is large enough to include all the thumbnails.

Now if I want to have different scan sessions inbetween and want to resume on this scan, I want to import the .scanresults file to have the whole scan loaded including all the previously generated and saved thumbnails.

However, there is no "Import"-Function for .scanresults files (yet?)? I'm unable to reimport the previously exported file. Is the Import function missing?

When I hit Scan again, it loads the results instantly, but all the thumbnails are missing and it takes ages until it has all the thumbnails loaded again. I just want to re-import a previously made scan with all the duplicate results AND thumbnails in place.

**Expected behavior**
being able to import previously exported files.

**Comment by kattjevfel** [comment]
A workaround for this is to rename it to `backup.scanresults` and place it in the same directory as the main executable, then run VDF. This will make it load the file right away, but a return of a button (could've sworn there used to be one at least) would be for the best.
