### ISSUE TITLE
[ISSUE] Its scanning folders that I didn't want to scan

### ISSUE THREAD

**Issue by Shituation** [0x90d/videoduplicatefinder#357]
**Environment**
 - OS:  Windows 10

**Describe the bug**
I select only 2 folders to be scanned. In the middle of the scan, on status bar below, I start seeing the app is scanning other folders that doesn't have anything to do with the selected ones. 
Deleting the database each time is the only way to stop this.
I have NOT enabled "scan against entire database" nor "scan against non-existing files"

**Expected behavior**
The app should only scan against the intended folders like in versions before.

Using latest version 12/06/22

**Comment by Xplode85** [comment]
I see the exact same issue here, had to go back to an older version dated 2022.07.13

**Comment by Shituation** [comment]
how did you find an older version? can you share it? i replaced my older  working version

**Comment by Xplode85** [comment]
I had the old download saved on my HDD. I'm willing to share of course, do you have any ideas where i could upload it? It's too large to upload directly.

**Comment by Shituation** [comment]
https://www.zippyshare.com/

Please upload there if you are so kind, then share the link here. 
Thank you!

**Comment by RichD1011** [comment]
I have exactly the same issue, do you mind sending me the older version as well?

**Comment by RichD1011** [comment]
Since app development seems to have stopped... are there any good alternatives?

**Comment by Xplode85** [comment]
Sorry for the late reply, emails from here started going in my spam folder :(
Here's the files dated 2022.07.13, it's the original download file, not even unpacked or renamed.
https://www38.zippyshare.com/v/eJKfsj6h/file.html

**Comment by 0x90d** [comment]
This is just visual. All skipped files appear at the status bar too. It still only scans the files from your include list.

> Since app development seems to have stopped... 

It was holidays and this is a project mostly maintained by myself. I'm doing this in my free time without getting money for it. And I have a family and a full time job too. I'll work on it when I have time and I reply when I have time but both I am also doing only when I want to, this is what makes a free project a free project.

**Comment by Shituation** [comment]
> This is just visual. All skipped files appear at the status bar too. It still only scans the files from your include list.
So the program is somehow still reading files that I didn't want to scan, compares to my "include list" and discard them if they are not there? Correct me if I'm wrong but that is inconvenient anyway since there is no reason for the program to scan folders that I didn't tell it to scan.
