### ISSUE TITLE
version-3.0.x does't work on macOS 13.0.1 

### ISSUE THREAD

**Issue by 0driver** [0x90d/videoduplicatefinder#358]
**Environment**
-macOS-13.0.1-M2

**Describe the bug**
I download the package [App-osx-arm64.tar.gz] from releaese 3.0.x. 
And I installed ffmpeg by homebrew.
Also,I used [sudo chmod -R 777 VDF.GUI] to authorize.
BUT, when I double-click the VDF.GUI;  it shows like this:

[
/Users/username/Downloads/outputFolder/VDF.GUI ; exit;                           
username@macname ~ % /Users/username/Downloads/outputFolder/VDF.GUI ; exit;
zsh: killed     /Users/username/Downloads/outputFolder/VDF.GUI

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
]

I tried to lauch it on console with command  [./VDF.GUI],It showed a similar info:
[
zsh: killed     ./VDF.GUI
]

**Comment by Shituation** [comment]
you downloaded the ARM version. Try with the OSX version.

**Comment by 0driver** [comment]
> <img alt="@Shituation" width="40" height="40" src="https://avatars.githubusercontent.com/u/43975882?s=80&amp;u=318b7d96f1a0bf2ebe258e2295166b56e7acf728&amp;v=4">

Thank you very much,It works!
