### ISSUE TITLE
VDF is crashing when has no permissions to write

### ISSUE THREAD

**Issue by piotrminkina** [0x90d/videoduplicatefinder#360]
**Environment**
Linux

**Describe the bug**
VDF is crashing when has no permissions to write in installation directory. For example I installed VDF in _/opt/vdf/_ and changed owner to _root_. I have circumvented the problem with saving the _Settings.json_ and _log.txt_ file by creating symbolic links to where VDF has write permissions. Unfortunately, I don't think I can handle the situation where VDF wants to create a temporary _ScannedFiles_new.db_ file. In this case I receive an exception as in the screenshot below.

![Screenshot from 2022-12-31 03-40-38](https://user-images.githubusercontent.com/2574153/210122775-ac6bb615-5e37-4e07-ab40-75f1c435d6d2.png)

I would like to develop my [Docker image](https://github.com/piotrminkina/docker-videoduplicatefinder) with a VDF application, but this problem is blocking me. I have configured the _Custom Database Folder_ to the directory where VDF has write permissions, so writing the _ScannedFiles.db_ file works as expected.

**Expected behavior**
The VDF should not be dumping due to lack of write permissions. In my opinion, the _ScannedFiles_new.db_ file should be saved in the directory where the _ScannedFiles.db_ file is saved. In my case, exactly in the same directory as the _Custom Database Folder_ setting.

**Comment by 0x90d** [comment]
You can specify the database path by setting `CustomDatabaseFolder` in settings file or on settings page in UI.
