### ISSUE TITLE
Sometimes VDF selects lower quality video with unknown reason

### ISSUE THREAD

**Issue by piotrminkina** [0x90d/videoduplicatefinder#362]
**Environment**
Linux

**Describe the bug**
I use the _Select Lowest Duration / Quality_ option, huge thanks for this helpful feature! Sometimes (rarely) this function selects a lower quality video, which only differs in file size, FPS and bit rate. I cannot understand for what reason. 

Please see the screenshots below. I have marked in green the expected behaviour (the function correctly marked the lower quality video) and in red the incorrect behaviour (the function marked the better quality video).

| | |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2574153/210186610-34c35034-7f50-428c-a797-31b36e024e7f.png) | ![image](https://user-images.githubusercontent.com/2574153/210187172-acb6d405-e8d3-45ff-b301-845c9ee54219.png) |

I point out that the screenshot shows exactly the same recordings, but with different quality.

**Expected behavior**
I wish such situations did not occur.

**Comment by 0x90d** [comment]
The order is:

Duration
Resolution
FPS
Bitrate

On red one the FPS is smaller, so selection is correct.

**Comment by piotrminkina** [comment]
I understand that with the current implementation the behavior is correct, so this is not a bug. However is it possible to improve this implementation? In my case the difference in FPS values is marginal, while in the case of bit rates the difference is large.

**Comment by 0x90d** [comment]
For some people even marginal differences matters so I don't have plans to change that. But there is a high request on better custom selection improvements which then could be used for cases like this.
