### ISSUE TITLE
Negative selection? (path.doesnot.contain)

### ISSUE THREAD

**Issue by Shituation** [0x90d/videoduplicatefinder#365]
**Environment**
 - OS: WIN10 x64

Is it there any way to perform a "negative" file selection? (files that *doesn't* contain X in the filename, or bigger file size to name some examples). 

Why? because all the options right now select for example the "best" (less file size) files instead of "worse" (bigger file size) files; or files containing "X" string in the filename but not files NOT containing "X".

That would be OK if the selection was used to preserve those files instead of deleting them, but as things are now, we can only delete selected (makes sense).

Right now:
In this example I want to keep lower size files and delete higher size dupes.

What happens:
I can only select for deletion files that have the "best" file size (lower file size)

What I need:
Select files that has the worst size (bigger)

(using the standard "select lowest duration / quality" doesn't work because some bigger (unwanted) files have higher fps)

**Comment by 0x90d** [comment]
Custom select:

`arg.ItemInfo.Path.Contains("imageFolder") == false`

or

`!arg.ItemInfo.Path.Contains("imageFolder")`
