### ISSUE TITLE
[bug] Removing selected files from list, does weird stuff

### ISSUE THREAD

**Issue by BismutoGanymedes** [0x90d/videoduplicatefinder#366]
**Environment**
 - OS: Windows 10 x64 19044.2364

**Describe the bug**
A video is worth 1000 words:

https://user-images.githubusercontent.com/121880486/211371059-7061cfd9-9f71-4012-bb18-f83438b5a471.mp4

**Expected behavior**
Only the selected files show be removed from list.

**Comment by 0x90d** [comment]
It removes the selected files. Then it removes all groups with just 1 element. I don't see a bug, otherwise please add more text.

**Comment by BismutoGanymedes** [comment]
I was trying to remove the selected files (automatic selection) from list so I could only select and remove the "bad" files that could not be automaticaly filtered/selected otherwise because there is no "iteminfo.is.worstsize"

**Comment by Maltragor** [comment]
> A video is worth 1000 words:

You are right,.. Timestamp 0:035
:-P

Is that what you're about, just inverting the selection?
That would be for your example:
`!arg.ItemInfo.IsBestSize`
The `!` has the meaning of `not` .

**Comment by BismutoGanymedes** [comment]
> > A video is worth 1000 words:
> 
> You are right,.. Timestamp 0:035 :-P
> 
> Is that what you're about, just inverting the selection? That would be for your example: `!arg.ItemInfo.IsBestSize` The `!` has the meaning of `not` .

Do you really think people uses this software for normal images?... The whole dupes software movement is an effort to remove duplicates from collections, 95% of it being porn in all its flavours. I removed the video it since I got my answer.

**Comment by Maltragor** [comment]
I didn't want to express my astonishment about your intended use with my comment.
And since I do not contradict your theory, I use VDF also with 95% probability exactly for this ;-)

The comment was only meant to point out the only partially successful attempt to make the videos unrecognizable.
