### ISSUE TITLE
Crash when searching for duplicates on Windows

### ISSUE THREAD

**Issue by hyvamiesh** [0x90d/videoduplicatefinder#37]
**Environment**
 - OS: Windows 10 Home build 17763
 - Software version: 2.0.6 

**Describe the bug**
Crash when searching for duplicates. When closing error box, main window is stuck at "Enimerating input folders.

**Expected behavior**
Display found duplicates

**Screenshot of crash**
![crash](https://user-images.githubusercontent.com/2478912/55012301-e2102e00-4fef-11e9-9bc4-dce40c65dee6.PNG)

**Comment by 0x90d** [comment]
While the program is closed rename ScannedFiles.db to ScannedFiles_backup.db and try again.

**Comment by hyvamiesh** [comment]
I got a fresh install and it fixed the problem.. Guess it was a corrupt database. If you need further testing, I have the old installation backed up.
