### ISSUE TITLE
Please add integration with an external visual video comparator

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [0x90d/videoduplicatefinder#370]
**Environment**
 - OS: [e.g. Windows / Linux / Any]

**Describe the solution you'd like**
Adding configurable integration with an external video comparator tool like this fellow github repo: [video-compare](https://github.com/pixop/video-compare) would seem like a good idea. 
Disclaimer: I am in no way associated with that repo; Just a user of both software.

**Comment by 0x90d** [comment]
First of all third party integration is beyond the scope of this project. The only thing I can imagine is allowing to run an external software by providing specific arguments. Such like "the file path of all selected videos".

Specifically for the github project you linked I don't see it supports specifying a time stamp only passing file path. That means for the frames you see in VDF, you'd have to go there manually yourself.

**Comment by Maltragor** [comment]
It is possible to define a custom command for e.g. 'open multiple': #248
