### ISSUE TITLE
Windows: GUI transparent 

### ISSUE THREAD

**Issue by WurstCommander** [0x90d/videoduplicatefinder#371]
**Environment**
 - OS: Windows 10

**Describe the bug**
The recent release changed something with the GUI, it's now transparent.
Screenshot: https://imgur.com/KqQaHKu

I think it might be connected to this commit:
https://github.com/0x90d/videoduplicatefinder/commit/490c40cac7f19444344769ca205810382eef009c

I tried a "fresh" install in a new directory, same behavior.

**Comment by 0x90d** [comment]
it's avalonias fluent design + acrylic background: https://docs.avaloniaui.net/tutorials/music-store-app/creating-a-modern-looking-window

Looks like it doesn't work very well if what is behind the window is bright.

**Comment by reddyshyam** [comment]
> it's avalonias fluent design + acrylic background: https://docs.avaloniaui.net/tutorials/music-store-app/creating-a-modern-looking-window
> 
> Looks like it doesn't work very well if what is behind the window is bright.

Please revert back or give us an option to turn it off. It definitely doesnot work well for me. 😄

**Comment by reddyshyam** [comment]
Thanks @0x90d for the quick fix and release. 👍 I always prefer light mode and am glad I could switch to it now. 🙇‍♂️
