### ISSUE TITLE
Add button does not show up in macOS Monterey 

### ISSUE THREAD

**Issue by avatar-lavventura** [0x90d/videoduplicatefinder#372]
**Environment**
 - macOS Monterey Version 12.6.2

**Describe the bug**
Here as you can see the add button does not show up
<img width="1010" alt="Screen Shot 2023-01-21 at 19 01 28" src="https://user-images.githubusercontent.com/18537398/213875514-a469fed9-aa4f-40a2-a301-54109146dd07.png">

**Comment by 0x90d** [comment]
I cannot see, where should this "add button" be? There isnt and shouldn't be such button in this area.

**Comment by avatar-lavventura** [comment]
In the documentation image (
![](https://user-images.githubusercontent.com/46010672/129763067-8855a538-4a4f-4831-ac42-938eae9343bd.png)
) you can see the location of the `Add` button.

**Comment by 0x90d** [comment]
Image is outdated. You can find it if you click on "Settings" tab at the top left. Then at the bottom under "Search Directories"
