### ISSUE TITLE
Clean Install - Can't add directories - nothing happens

### ISSUE THREAD

**Issue by WurstCommander** [0x90d/videoduplicatefinder#373]
Sorry, that it's me again :-)

**Environment**
 - OS:Windows 10

**Describe the bug**
I had a bug that if I tried deleting files, VDF crashed (maybe another bug?)
Because I had an old database, I did a "clean install" in a new directory. 

Now I can't add directories, after selecting a directory it doesn't show up under "Search directories", doesn't matter which drive I choose. Nothing happens.

Besides that, if I click on "clean database" VDF crashes (my DB is empty, If I copy my old DB it's the same, it crashes)

**Expected behavior**
Directory would show up.

**Comment by 0x90d** [comment]
Without crash logs with stacktraces I cannot help you. You can possibly get them from the event viewer. As for the directories, where are they? Are they local folders? Network drives? Etc.

**Comment by WurstCommander** [comment]
Sadly, there are no crash logs from VDF.

I'm not doing anything special. Clean Install and choosing "D:\temp\" for instance, nothing happens.

**Comment by WurstCommander** [comment]
Video of Directory bug and Clean DB Crash
https://drive.google.com/file/d/1k7hDj8s0zE0tPTKW5h3pS6TnDFV28wce/view?usp=sharing

**Comment by 0x90d** [comment]
I've done some changes, builds are currently running. Please try when they're finished.

**Comment by WurstCommander** [comment]
Ok, thanks. VDF is really cool and I don't want so stress you. You do amazing work!

**Comment by 0x90d** [comment]
No worries, builds are done. Let me know

**Comment by WurstCommander** [comment]
Seems to work, I can add directories again and Clean Database doesn't crash the App anymore.

Thank you, I will post again if I find anything else. That was a very short check :-)
