### ISSUE TITLE
Thumbnails are too small

### ISSUE THREAD

**Issue by mkalmajid** [0x90d/videoduplicatefinder#374]
- OS: Windows

I want to start with saying that this program is amazing. It has saved me a lot of time going through my multiple file backups.

I find the thumbnails to be too small for comparison. Even though you have added the ability to preview thumbnails on hover and a slider for thumbnail size, all it does is zoom-in an already small picture. This forces me to open the files consecutively to compare them side-by-side anyways, so having a thumbnail with a larger default  resolution would help things a lot.

On this note, although I haven't programmed using C# before, I tried taking solving this issue into my own hands. I downloaded .NET SDK and cloned the project to VSCode and I was able to build it. Unfortunately, I get the following errors when I click on Scan button:

Exception thrown: 'Avalonia.Markup.Xaml.XamlLoadException' in Avalonia.Markup.Xaml.dll
Exception thrown: 'Avalonia.Markup.Xaml.XamlLoadException' in System.Private.CoreLib.dll

I tried googling what this means but I didn't find a solution. If someone could either help me resolve this exception, or if  try to solve the thumbnail issue themselves, that would be appreciated!

**Comment by 0x90d** [comment]
Thumbnails are that small because of memory usage. Some people might have thousands of duplicates. VDF loads all that images into memory. After seeing this issue #370, I plan to replace the "hover thumbnail" with a window that pulls new thumbnails with proper sizes.

**Comment by mkalmajid** [comment]
I believe that Instead of a slider for thumbnail size, There should be a drop-down in the settings with a set of thumbnail sizes the user can choose from so that users with better hardware can benefit from it.

In regards to the exception I have been getting, this seems to have been solved in the last commit. It looks like a bug came out of this though, since now when I try to scan it gives me an exception window that says "Cannot find FFmpeg. Please follow instructions on Github and restart VDF" despite not having the "Use native ffmpeg binding" option checked. This can be solved by actually using the setting in release version, but I have no idea how to solve it in debug mode.
