### ISSUE TITLE
`SIGTERM` and `SIGINT` signals not handled

### ISSUE THREAD

**Issue by jlesage** [0x90d/videoduplicatefinder#376]
**Environment**
 - OS: Linux

**Describe the bug**

When closing the application by sending a `SIGTERM` signal (e.g. via `kill <pid>`) or when starting the application in foreground from the command line and then pressing `ctrl+c` (effectively sending a `SIGINT` signal), the application doesn't terminate cleanly.  For example, settings are not saved.

**Expected behavior**

Upon receiving a `SIGTERM` or `SIGINT` signal, the application should perform a proper shutdown (by saving settings for example), like if the user manually closed the window.

**Comment by 0x90d** [comment]
Kill or terminate already implies by the term itself that the process HAS TO shutdown immediately. It is a hard kill, not a graceful. Doing that under Linux, as far as I know, is done for shell applications only, because you cannot close them otherwise. But VDF has a GUI and it's listening to the window closing event. If killing the application is not raising this event I suggest that you fill out a bug report on Avalonia: https://github.com/AvaloniaUI/Avalonia/issues

**Comment by jlesage** [comment]
Hello, thank you for your answer.

> Kill or terminate already implies by the term itself that the process HAS TO shutdown immediately. It is a hard kill, not a graceful.

Under Linux at least, `SIGTERM` *is* the way to request a graceful shutdown.  In fact the application can even ignore the signal.  A hard kill is done by sending a `SIGKILL` signal.

> Doing that under Linux, as far as I know, is done for shell applications only, because you cannot close them otherwise. 

For sure some GUI apps support graceful shutdown via signal (but I agree, not all of them).  However, there is a benefit to support graceful shutdown on `SIGTERM`.  In the situation where a Linux machine has to reboot, `SIGTERM` is sent to every processes.  This reboot could occur while the GUI is opened, maybe because an automatic update/upgrade of the system occurred.  Or maybe because the user rebooted the system without closing all its applications, expected them to be restored after.

> If killing the application is not raising this event I suggest that you fill out a bug report on Avalonia: https://github.com/AvaloniaUI/Avalonia/issues

I'm really not familiar with Avalonia , but I can try to see if this concern has already been raised at some point.
