### ISSUE TITLE
SaveScanResults() and Delay(100)

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#378]
While trying out PosixSignalRegistration (#377) I noticed the Delays and had wondered if that was really the best idea....

E.g.:
https://github.com/0x90d/videoduplicatefinder/blob/032a5c0ee1abc81b1daeda7d383ac3f3bf0302af/VDF.GUI/ViewModels/MainWindowVM.cs#L342-L343

and
https://github.com/0x90d/videoduplicatefinder/blob/032a5c0ee1abc81b1daeda7d383ac3f3bf0302af/VDF.GUI/Views/MainWindow.xaml.cs#L78-L92

From my point of view, the problem is that you have built a probably unintentional recursion:
Pressing the (X) => MainWindow_Closing() => ConfirmClose() => ApplicationHelpers.CurrentApplicationLifetime.Shutdown().
But Shutdown() triggers again the canceled MainWindow_Closing() ...
Without the Delay... yes, that won't end well....
But instead of manipulating the runtime behavior using Delays, my suggestion would be to simply prevent the recursion itself:
```C#
if (keepBackupFile = await ApplicationHelpers.MainWindowDataContext.SaveScanResults()) {
	Closing -= MainWindow_Closing;
	ApplicationHelpers.CurrentApplicationLifetime.Shutdown();
}
```
So before calling Shutdown() the already called MainWindow_Closing() event handler will be unregistered.

**Comment by 0x90d** [comment]
> if that was really the best idea

If you have a better one let me know. Otherwise as of now it is.
