### ISSUE TITLE
Incorrect selection for WMV, AVI, M2ts vs MP4 types

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#380]
### Environment
 - OS: Windows 11
 - VDF Version: 3.0

### Describe the bug
When "**Select Lowest Duration/Quality**" is selected, the file with the highest resolution is incorrectly selected when an MP4 is compared to (WMV, AVI, or M2ts).
See attached file [VDF_JSON_PartialResults.zip](https://github.com/0x90d/videoduplicatefinder/files/10523934/VDF_JSON_PartialResults.zip) for exported JSON list having details of the files in the **Group Item Details**.

**Group Item Details**
 - Group#1 (MP4 incorrectly selected)
Type:MP4, Duration:32:23, Res:576x432,  FrameSizeInt: , Format:h264, 20fps,865kbps, Audio:aac, Size:217.2MB
Type:WMV, Duration:32:22, Res:400x300, FrameSizeInt: , Format:wmv3, 25fps,800kbps, Audio:wmv2, Size:215.2MB

 - Group#2 (WMV incorrectly selected)
Type:WMV, Duration:1:05:19, Res:1280x720, FrameSizeInt:2000, Format:wmv3, 29.97003fps, 1500kbps, Audio:wmav2, Size:782.9MB
Type:MP4, Duration:1:05:19, Res:960x540, FrameSizeInt:1500 , Format:h264, 25fps, 1597kbps, Audio:aac, Size:809.4MB

 - Group#3 (MP4 incorrectly selected)
Type:MP4, Duration:24:50, Res:554x416, FrameSizeInt: 970, Format:h264, 29.97003fps, 372kbps, Audio:aac, Size:78.7MB
Type:AVI, Duration:24:49, Res:480x360, FrameSizeInt: 840, Format:mpeg4, 23.976fps,908kbps, Audio:mp3, Size:180.2MB

 - Group#4 (AVI incorrectly selected)
Type:AVI, Duration:17:57, Res:640x480, FrameSizeInt:1120, Format:mpeg4, 25fps, 2303kbps, Audio:mp3, Size:313.9MB
Type:MP4, Duration:17:57, Res:426x240, FrameSizeInt:666, Format:h264, 30fps, 281kbps, Audio:aac, Size:41.2MB

 - Group#5 (M2ts incorrectly selected)
Type:M2ts , Duration:10:20, Res:1920x1080, FrameSizeInt:3000, Format:h264, 25fps, 0kbps, Audio:aac, Size:206.2MB
Type:MP4, Duration:10:20, Res:1280x720, FrameSizeInt:2000, Format:h264, 25fps, 1055kbps, Audio:aac, Size:83.8MB

**File Type Summary**
 - M2ts sample quantity=200
About 90% of the M2ts comparisons results were correct. With the incorrect results, the M2ts with the higher resolution was selected.

 - WMV sample quantity=20
50% of the WMV comparisons results were correct. 9 incorrectly selected MP4, and one incorrectly selected WMV.

 - AVI sample quantity=3
Two AVI's were compared to MP4 and one was compared to an M2ts. Both AVI that compared to MP4 incorrectly selected the AVI files. The AVI to M2ts comparison gave the correct result.

See attached file [VDF_JSON_FullResults.zip](https://github.com/0x90d/videoduplicatefinder/files/10523942/VDF_JSON_FullResults.zip) listing all the files in this scan.

### VDF Settings:
<img width="617" alt="VDF_Misc_Settings" src="https://user-images.githubusercontent.com/47364845/215226374-ae5c1df3-5620-4a95-a60f-fcec0f4622df.png">
<img width="567" alt="VDF_Files_Settings" src="https://user-images.githubusercontent.com/47364845/215226375-5ee69e4d-0eda-44b9-8060-31ea889fb7ad.png">

### Expected behavior
File with lower resolution should be selected regardless of the file type.

**Comment by 0x90d** [comment]
Can you make a screenshot of the whole group please and mark the file that is supposed to get (not) selected? See #367

**Comment by David-Maisonave** [comment]
Sorry, but I deleted the duplicate files. However, I saved all the JSON file details to this attached file [VDF_JSON_PartialResults.zip](https://github.com/0x90d/videoduplicatefinder/files/10523934/VDF_JSON_PartialResults.zip).

I'm attaching a new updated version of the JSON file in which it clearly separates the groups, and before the start of each group it states which file type was incorrectly selected. See following attached file: [VDF_JSON_PartialResults_Pretty.zip](https://github.com/0x90d/videoduplicatefinder/files/10527983/VDF_JSON_PartialResults_Pretty.zip)

**Comment by 0x90d** [comment]
The file format has absolutely no impact on selection. You can see how VDF does the selection in the code. A screenshot is more helpful as a bunch of text. But better would be some example video files which can reproduce the issue. As you already deleted the files there is no chance for us to reproduce it. So I'm closing this issue.
