### ISSUE TITLE
When filter is deselected, the list remains filtered by PATH field content

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#381]
**Environment**
 - OS: Windows 11
 - VDF Version: 3.0
 - 
**Describe the bug**
Select filter, and enter a value in the **Path** field. Now deselect the Filter option. The list remains filtered.
The only way to remove the filter is by selecting filter again, and clearing the Path field.

**Expected behavior**
When Filter is deselected, filtering should be removed from the list, and the full list should be displayed.

**Comment by 0x90d** [comment]
Toggling filter just show/hide the filter options. it doesn't mean to turn filter on/off.
