### ISSUE TITLE
Multiple Enhancement (dbClk Path, copy-filename, Cmdline options, Real Delete, Export Filtered list, More Select Opt, Exp Build Histor, ....)

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#382]
**Environment**
 - OS: Windows

**Describe the solution you'd like**
This is a great program and a really good GUI. There's a few things that would make it even better (IMHO).

 - Add double clicking function under the path column, which calls the "Open in Folder" function.
 - For the path column, add "Copy filename to clipboard" option to the context menu option.
 - When a grid item is selected and user enters c-ctrl, copy the grid text to clipboard (except thumbnail).
 - Add command line options so that users can use windows scheduler to run a scan periodically, and automatically clean the file system. The command line option should include a search directories option, a selection option, an action option, and a scan mode option.
   - Search Directories option: **Path** (followed by a comma separated file paths) 
   - Selection option: SelLowDurQuality, SelOld, SelNew, KeepSmall, KeepFirst, SelectCustom,SelectCustomAll
   - Action option: **Delete**, **Copy**, **Move**, **Export**
   - Scan Mode option: MinPercent, DurDiff, MinSize, MaxSize
   - Other Options:
     - IncludeSubDir
     - IncludeImg
     - DbFolder
     - EntireDB
     - IgnoreBlack
     - IgnoreWhite
     - IgnoreReadOnly
     - ExcludeReparse
     - ExtendLog
     - AutoBkUpResults
     - PathContains
     - PathNotContain
     - MaxParallel
     - SaveLog
 - When "Delete Permanently" is selected while the ctrl key is press, delete the files instead of  sending files to recycle bin. Or have separate option for Move-to-Recycle and Permanently Delete.
 - Option to have files which have been deleted, to be removed from the list.
 - Option to not display "Are you sure???" verification prompt.
 - Add option to export filtered list.
 - Custom Select is a great option, but not all users are programmers. I recommend adding the following options:
   - **Select smallest file size**
   - **Select largest file size**
   - **Select shortest name**
   - **Select longest name**
 - Change the expression field in Expression Builder to a combo field, and have the combo field list previous entered values. Or add another window listing previous entered values.
 - Add restart button under Appearance menu, which restarts the program.

**I'm a C++/C# programmer, and I can help with some of these changes.**

**Comment by 0x90d** [comment]
> * Add command line options so that users can use windows scheduler to run a scan periodically, and automatically clean the file system. The command line option should include a search directories option, a selection option, an action option, and a scan mode option.

This is not planned. VDF is a GUI only project.

> * Option to not display "Are you sure???" verification prompt.

This is not planned either.

> * Add option to export filtered list.

Do you know a way to get filtered items without running the same filter options in code again?

> * Add restart button under Appearance menu, which restarts the program.

For which purpose?

**Comment by David-Maisonave** [comment]
> For which purpose?
The Appearance menu states in the bottom "Restart VDF to apply changes". It would be helpful if there was a button to restart VDF. This item is not that important.

I do see the command line option as an important feature. There are many GUI tools which have command line options.
I'll fork the project, and add it on the fork.

**Comment by David-Maisonave** [comment]
Another feature I would like to see is the ability to hide columns. I usually don't need the last three columns. If these columns could be hidden, that would give more space for the path.
