### ISSUE TITLE
Windows Reparse Point

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#384]
### Environment
 - OS: Windows 11
 - VDF Ver: 3.0

### Describe the bug
Not getting expected behavior when scanning reparse points.
#### Summary of three main issues.
1. Some reparse points duplicates are ignored (not detected) when the "Exclude Reparse Points" option is **deselected**.
2. Some reparse points are **NOT** ignored when the "Exclude Reparse Points" option is **selected**.
3. After changing the "Exclude Reparse Points" option, a new scan does not reflect the change until triggering "Clear Database".

#### Details:
1. With the reparse point option **deselected**, the following reparse points duplicates are **NOT** detected:
    - Symbolic links created by [Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) (**Not Expected Behavior**)
    - Hard links created by [Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) (**Not Expected Behavior**)
2. With the reparse point option **selected**, the following reparse points duplicates are incorrectly detected:
    - Hard links created by mklink (mklink /H ReparsePoint.mp4 Original.mp4) (**Not Expected Behavior**)
3. After selecting "Exclude Reparse Points" a new scan on the same folder still displays reparse points.
    **Steps to reproduce issue:**
    - **Deselect** "Exclude Reparse Points" and scan a folder having reparse points. 
    - **Select** "Exclude Reparse Points" and scan the folder again.  
      - The reparse points still show up in the results. (**Not Expected Behavior**)
    - Select "Clean Database" and scan again. 
      - The reparse points still remain in the results.  (**Not Expected Behavior**)
    - Select "Clear Database" and scan again. 
      - Now the reparse points are removed from the results. (**Expected Behavior**)
    - Again **Deselect** "Exclude Reparse Points" and scan a folder having reparse points.
      - Reparse points are back on the results without having to clear the database.  (**Expected Behavior**)

#### Working Reparse points
 - The below listed reparse points give **expected behavior**. RP duplicates are detected when "Exclude Reparse Point" is deselected. RP duplicates are ignored when the option is selected.
   - Symbolic link files created by mklink (mklink ReparsePoint.mp4 Original.mp4)
   - Symbolic link files created by [SymlinkCreator](https://github.com/arnobpl/SymlinkCreator)
   - Junction points (directories) created by [Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html), mklink, and SymlinkCreator
   - Symbolic link directories created by Link Shell Extension, mklink, and SymlinkCreator

### Expected behavior
1. When "**Exclude Reparse Point**" is deselected, VDF should be able to find duplicate video that are either symbolic links or hard links created by [Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) (**Not Expected Behavior**)
2. When "**Exclude Reparse Point**" is selected, VDF should ignore duplicate videos that are hard links created by mklink using command  (mklink /H ReparsePoint.mp4 Original.mp4).
3. When "**Exclude Reparse Point**" option is selected, the results of a new scan should exclude any reparse points.

**Comment by 0x90d** [comment]
Reparse points are only handled when files are getting added to the database. It relies on .NET to detect them.
https://github.com/0x90d/videoduplicatefinder/blob/b4e3ff786e7bef4563e0e903df074ffc151d984a/VDF.Core/Utils/FileUtils.cs#L57-L58

If .NET doesn't detect them please check if they're getting detected with latest .NET 7 (or .NET 8 nightly build) and if not fill out an issue on .NET repo https://github.com/dotnet/runtime/issues VDF uses .NET 6.

As for 3, this is not a bug as I explained in first sentence. But it could get changed.

**Comment by David-Maisonave** [comment]
> As for 3, this is not a bug as I explained in first sentence. But it could get changed.

I see it as a bug, because when you perform the opposite test it works without having to clear the database. If it perform the same way in both directions, then you could say it's expected behavior. But it doesn't.

**Comment by David-Maisonave** [comment]
### Item#1
Disregard issue #1. I can no longer reproduce this after I changed the video content and updated Link Shell Extension to the latest version.

### Item#2
Issue#2 is a general issue with Hard Links which is reproducible with mklink,  Link Shell Extension, and SymlinkCreator. Hard links do not get the ReparsePoint attribute set.
Moreover, solving this is more complicated then I thought.  Excluding the file in GetFilesRecursive would not be the right approach.
To determine if a file is a hard link, you have to call GetFileInformationByHandle. However, there's no way to tell if you're dealing with the original file, or the new hard link file. That's because once you create a hard link of a file, both the original and the new hard link are flagged as hard links.
I think the easiest approach would be to do the hard link check right before including 2 files in a group, and only do the hard link check if the file has the same file size, video length and frame size. In other words, if they looks exactly the same, then check if they're part of the same hard links.

Can you please point me in the right direction in the code where the files are getting added to a group before displaying the results?

### Item#3
I'm trying to figure out if the "Rescan" should be where this should get address.  What is the difference between selecting the "Scan" option and the "Rescan" option?

**Comment by 0x90d** [comment]
Rescan skips file enumeration. If hard links don't set file attribute, they're not supported in VDF.

**Comment by David-Maisonave** [comment]
> Rescan skips file enumeration. If hard links don't set file attribute, they're not supported in VDF.

I want to modify my own version of the program, to add support for this feature.
Can you please point me in the right direction in the code where the files are getting added to a group before displaying the results?

What is the difference between clicking Scan and clicking Rescan?

**Comment by David-Maisonave** [comment]
I think I found the part I need to change to support Hard Links.
VDF.Core\ScanEngine.cs:461 in function ScanForDuplicates right before the **if (isDuplicate)**.
I'm going to add another **if (isDuplicate)** that will check if the files are part of the same hard links, and if so, set **isDuplicate** to false.

After I finish implementing it, are you sure you don't want me to create a pull request to put it into the main code?

**Comment by David-Maisonave** [comment]
I've already finish implementing the code for the hard links, and the code also fixes item#3, so that even symbolic links results reflects the reparse point option without having to clear the database.
