### ISSUE TITLE
Add Identical option to Filter options

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#385]
**Environment**
 - OS: Any

**Describe the solution you'd like**
On the Filter menu, add a combo box that has the following items to select from:
 - Any
 - Identical Match
 - Different (Not Identical)

Also add option so actions do NOT apply to filtered out items.

"**Any**" would be the default value and result in no filtering. **Identical match** would only display groups having identical files (same file size, video length, resolution, format, fps, and bit rate). **Different** would only display groups that have files that are not identical.

If VDF has this option, this would be a temporary workaround for the Hard Links issue.

**Comment by 0x90d** [comment]
> Also add option so actions do NOT apply to filtered out items.

This isn't possible unless there is a way to obtain only filtered items (except of running same filter conditions in code again). I don't know such a way.

**Comment by David-Maisonave** [comment]
> This isn't possible unless there is a way to obtain only filtered items (except of running same filter conditions in code again). I don't know such a way.

I just tested an implementation which addresses this.  I added the following code in function VDF.GUI.ViewModels.DeleteInternal, after the MessageBoxButtons.Yes check.
``

			if (!string.IsNullOrEmpty(FilterByPath) || FileType.Value != FileTypeFilter.All) {
				string FilterByPath_lwr = FilterByPath.ToLower();
				HashSet<System.Guid> IncludedGroups = new HashSet<System.Guid>();
				for (var i = Duplicates.Count - 1; i >= 0; i--) {
					if (FileType.Value != FileTypeFilter.All) {
						if (FileType.Value == FileTypeFilter.Images && !Duplicates[i].ItemInfo.IsImage)
							continue;
						if (FileType.Value == FileTypeFilter.Videos && Duplicates[i].ItemInfo.IsImage)
							continue;
					}
					if (string.IsNullOrEmpty(FilterByPath) || Duplicates[i].ItemInfo.Path.ToLower().Contains(FilterByPath_lwr))
						IncludedGroups.Add(Duplicates[i].ItemInfo.GroupId);
				}
				for (var i = Duplicates.Count - 1; i >= 0; i--) {
					if (!IncludedGroups.Contains(Duplicates[i].ItemInfo.GroupId))
						Duplicates[i].Checked = false;
				}
			}

``

**Comment by 0x90d** [comment]
This is what I was talking about. You are basically running the same filter conditions on the list again. This split up the filter logic into two places that needs to be maintained. Ideally the `DataGridCollectionView` has a property that contains all the filtered items but that isn't the case.

**Comment by David-Maisonave** [comment]
> Ideally the DataGridCollectionView has a property that contains all the filtered items but that isn't the case.

According to the [DataGridCollectionView](https://reference.avaloniaui.net/api/Avalonia.Collections/DataGridCollectionView/) online documentation, the [GetItemAt](https://reference.avaloniaui.net/api/Avalonia.Collections/DataGridCollectionView/1C60C45B) member function returns the filtered items.
- Retrieve item at the given zero-based index in this DataGridCollectionView, after the source collection is **filtered**, **sorted**, and paged. 

Also [ItemCount](https://reference.avaloniaui.net/api/Avalonia.Collections/DataGridCollectionView/3F76F288) returns the number of items after filter is applied.
