### ISSUE TITLE
Can't run on OSX Ventura 13.1

### ISSUE THREAD

**Issue by RyanMcCarl** [0x90d/videoduplicatefinder#389]
**Environment**
 - OS: OSX Ventura 13.1

**Describe the bug**
I've installed FFmpeg via Homebrew as well as the .NET installation recommended in the error message, but I still can't run the program due to a security error:

`Failed to load ~/bin/VDF/libhostfxr.dylib, error: dlopen(~/bin/VDF/libhostfxr.dylib, 0x0001): tried: '~/bin/VDF/libhostfxr.dylib' (code signature in <884FE940-7E05-3FC9-9B21-A362097D4A00> '~/bin/VDF/libhostfxr.dylib' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS~/bin/VDF/libhostfxr.dylib' (no such file), '~/bin/VDF/libhostfxr.dylib' (code signature in <884FE940-7E05-3FC9-9B21-A362097D4A00> '~/bin/VDF/libhostfxr.dylib' not valid for use in process: library load disallowed by system policy)
The library libhostfxr.dylib was found, but loading it from ~/bin/VDF/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366`

**Comment by 0x90d** [comment]
There are two releases for mac. One for x86 machines and one for arm64 alias M1. Make sure you download the correct one. Otherwise check your "system policies".

**Comment by 0x90d** [comment]
Updated instructions: https://github.com/0x90d/videoduplicatefinder#macos-user
