### ISSUE TITLE
Select an entry when click it anywhere

### ISSUE THREAD

**Issue by caoli5288** [0x90d/videoduplicatefinder#39]
**Environment**
Windows 10

**Describe the solution you'd like**
Want to select an entry when you click it anywhere, rather than the checking box on the left.

Every time I confirm a video, I need to look at the information on the right and then move to the far left to click, which is painful.

In addition, want the selected entry to remain highlighted.

**Comment by 0x90d** [comment]
There are different behaviors between the selection by clicking on it, and the selection by ticking the check box. A click-everywhere-to-check cannot be added. Latest appveyor build got bigger checkboxes which makes it easier to check.
