### ISSUE TITLE
VDF doesn't show progress information without resizing it first.

### ISSUE THREAD

**Issue by RevENGE-code** [0x90d/videoduplicatefinder#391]
**Environment**
 - OS: macOS Ventura (13.2)
 - Screen: 3024 × 1964, 14" Mac

**Describe the bug**
When running VDF.GUI, progress information doesn't show, without first resizing the Window on mac.
How the window looks like without resizing the window:
<img width="1132" alt="Bildschirm­foto 2023-02-02 um 20 18 51" src="https://user-images.githubusercontent.com/54822494/216429803-09145ded-3071-40c9-8a48-81ae089b9f9f.png">

How it looks after resizing it:
<img width="1132" alt="Bildschirm­foto 2023-02-02 um 20 19 22" src="https://user-images.githubusercontent.com/54822494/216429945-2435e2d1-0345-4e7d-9c88-3fc6add97708.png">
Also, this behavior isn't influenced by not having run a scan yet or the opposite.
 
**Expected behavior**
I expect VDF to show integral information, without first having to change its size (height or width).

**Comment by 0x90d** [comment]
Sounds and looks like an Avalonia issue. M1 or x86 mac?

**Comment by RevENGE-code** [comment]
> Sounds and looks like an Avalonia issue. M1 or x86 mac?

M1 Pro
