### ISSUE TITLE
Detection Logic?

### ISSUE THREAD

**Issue by dsrtusr88** [0x90d/videoduplicatefinder#395]
How does VDF actually detect a dupe?

My use case:
- I have a large library of scenes and episodes as well as many movies that may contain the scenes or episodes as the whole movie or a compilation.
- I would like to use VDF to analyze my library and tell me where all of these overlaps exist and then tell me details of the overlap. 
- Scenario: I have 4 episodes of 1080p and 1 movie that contains all 4 episodes as 720p.  VDF detects a duplicate group and shows me where in the movie each of the scenes are located.  I assess that I have all of the content at higher resolution in the individual episodes.  The 720p movie is of less value to me, so I can safely delete it and retain the episodes

**Comment by 0x90d** [comment]
It takes thumbnails on fixed positions (percentage of the video duration) and compares at each other. VDF won't find duplicates when video duration difference is too far.

**Comment by dsrtusr88** [comment]
@0x90d how does that compare with https://www.video-comparer.com/product-features.php which can do some of that?  The software linked is fine on small libraries, but definitely struggles with scale where VDF doesn't.
