### ISSUE TITLE
Directories containing the `#` character are not handled correctly

### ISSUE THREAD

**Issue by jlesage** [0x90d/videoduplicatefinder#398]
**Environment**
 - OS: Linux

**Describe the bug**
Adding a folder under `Search Directories` that contains the `#` character is not handled correctly:
  - Display of the folder name stops at the `#` character.
  - Scan of such folder does not work.

**Expected behavior**
VDF should properly handle directories containing a `#` character.

**Comment by 0x90d** [comment]
I cannot reproduce it:
![image](https://user-images.githubusercontent.com/46010672/218445103-d37d4115-5b00-4ff4-859e-2bd18ef0f5dc.png)

Even if I could its extremely likely an Avalonia issue.

**Comment by jlesage** [comment]
@0x90d, the test you did was on Linux or Windows ?

**Comment by jlesage** [comment]
I have been able to reproduce on a "standard" Ubuntu 20.04 LTS installation.

**Comment by 0x90d** [comment]
Test was done on Linux (Ubuntu)
