### ISSUE TITLE
Dont use binaryformatter

### ISSUE THREAD

**Issue by 0x90d** [0x90d/videoduplicatefinder#4]
Not really versioning friendly

**Comment by Revan654** [comment]
I know this is a bit old, Wouldn't it be easier just to use a hashtable and then serialize the datastream? or Maybe use Serialization Safe Method?

I use hashtable with datastream with my smaller apps and it works with both Winform and WPF. 

Serialization Safe is only used when I deal with massive amount of setting data.

You can also use a formsettting as well(I think your old 1.0 version used this).
