### ISSUE TITLE
selection methods doesn't work

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#402]
**Environment**
 - OS:  Windows 10 x64
Using latest version downloaded today.

Selection methods in "select custom" doesn't work.
The "path" option hangs the whole program.
The "select" button (to execute) doesn't do anything.

**Comment by 0x90d** [comment]
Why do you create another issue with same content? The recent commit has fixed it. If not, provide more information and not just copy the same text.
