### ISSUE TITLE
Video integrity check features

### ISSUE THREAD

**Issue by LordKenmou** [0x90d/videoduplicatefinder#404]
Before I de-duped videos, I needed to verify the integrity of video first because videos were rescured from a broken flash storage.
Following was helped to verify videos in my case. I think they will help for other VDF users.

1. Integrity check using ffmpeg feature. [I used this nice script with modified output](https://gist.github.com/Desani/129be27da7d735d7c75192ec1aa96c65#file-scanmedia-md)
  Use case: de-dupe incompletely downloaded or copied videos
2. Hash comparison
  Use case: make it easy to de-dupe exact matches

Thanks,

**Comment by 0x90d** [comment]
> 1. Integrity check

I think such a feature is out of scope.

> 2. Hash comparison

Why would that be useful? You can already get 100% matches in VDF only if you want. Besides, generating hashes of files especially large files can be time consuming and there are already a lot of tools out there doing this.
