### ISSUE TITLE
Add support for ffmpeg version 6.0

### ISSUE THREAD

**Issue by King555a** [0x90d/videoduplicatefinder#406]
**Environment**
 - OS: Windows 10 22H2 x64

**Describe the bug**
I just updated VDF to the latest version and also ffmpeg. Version 6.0 of ffmpeg was released today. When I click the scan button and have "Use native ffmpeg binding" active, I get this error message:

![vdf](https://user-images.githubusercontent.com/126968427/222910823-00890d86-aca7-41c8-a7a2-17b99a5c0b15.png)

The scan is not started.

**Expected behavior**
Starting the scan. According to the readme of this repository, I should use the "latest" version. The filenames of the exe files have not changed, so it should work (in my opinion).

These are the new files:

![ffmpeg](https://user-images.githubusercontent.com/126968427/222910880-53b38958-e1d1-4407-9032-2b2025eff8da.png)

**Comment by 0x90d** [comment]
From the readme:

If you want to use native ffmpeg binding for much faster speed you must download the **5.0** stable shared version.

**Comment by 0x90d** [comment]
It changed the filenames. Like avcodec has the `-60` ending now. Latest package is for the case where you don't use native binding. Thus the additional sentence about native binding.
