### ISSUE TITLE
VDF doesn't detect duplicate video that is shorter

### ISSUE THREAD

**Issue by RevENGE-code** [0x90d/videoduplicatefinder#408]
**Environment**
- OS: macOS Ventura Version 13.3 (22E252)
- Latest VDF Daily Build

<img width="4280" alt="Failed to find duplicate but shorter video" src="https://user-images.githubusercontent.com/54822494/230324420-f3a33529-047b-4c12-960a-935e255cfb74.png">

Videos that aren't detected:
https://user-images.githubusercontent.com/54822494/230320952-658288d6-13ef-41be-ad27-87ee23d1f8a8.mp4
https://user-images.githubusercontent.com/54822494/230321165-2e2e397f-97a7-4ae8-bcc4-186e8697d03e.mp4

Log:
<img width="890" alt="Bildschirmfoto 2023-04-06 um 10 49 24" src="https://user-images.githubusercontent.com/54822494/230325377-e15fa699-7580-45ba-bc74-90af790f6786.png">

**Describe the bug**
VDF doesn't detect duplicate video that is shorter

**Expected behavior**
detect duplicate videos

**Comment by alrepin** [comment]
I have also Expected this feature..

**Comment by 0x90d** [comment]
This is by design. Thumbnails are generated based on percentage of duration. For 1 thumbnail its 50% of video duration. And at this position, these two videos (aka two frames) are not identical. You can have VDF detect these two if you lower your percentage value in settings.

**Comment by RevENGE-code** [comment]
Hey 0x90d, 

I've tried doing what you said, but I am still unable to get it detected. Is there anything else I can do ?
<img width="2388" alt="still no reults" src="https://user-images.githubusercontent.com/54822494/230597262-ff645206-b5dd-4b49-a135-0c3fc9ade759.png">
