### ISSUE TITLE
Missing label for SelectedCustomCommandValue

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#410]
**Environment**
 - OS: Windows 11
 - Using code tip from date 12Apr2023 1100hrs

**Describe the bug**
On Settings->Misc view, there's a field under the "**Custom Commands**" combo field, which is not labeled. In the source code, this field is associated with SelectedCustomCommandValue.
I suspect this might be an obsolete field which should be removed from the view.

**Expected behavior**
The field should have a label just like the other fields in that column. Or if the field is obsolete, it should be removed.

Can you please confirm if this field is needed, because I like to remove it from my custom copy of the source code if it's no longer in use.
Thanks

**Comment by Maltragor** [comment]
With the **Custom Commands** you can replace existing commands or extend them.
At the moment you can define your own commands for four different opening actions. 

![image](https://user-images.githubusercontent.com/36803696/231900259-45413067-6c0d-44b8-91da-bd26348906c5.png)

To make the configuration a bit more compact (in principle, the existing approach could be extended to more commands), there is not a separate edit field + label for each command. Instead you select in the first drop down list which command you want to edit and enter the corresponding command in the edit field below. (The tool tip contains an example for this). 
Each action listed in the drop down list can be assigned its own command in this way.
Therefore both fields are needed :-)

More info s.  #248
