### ISSUE TITLE
Add version number to title

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#411]
**Environment**
 - OS: Windows 
 - 12Apr2023 Tip

**Describe the solution you'd like**
Request that the program version is added to the program title. It's common practice so users can easily see which version they're using.

Change **VDF.GUI\Views\MainWindow.xaml** at line number 18.
Title="Video Duplicate Finder **3.0** - Cross-platform"

**Comment by 0x90d** [comment]
Now as there are only nightly builds, `3.0` isn't a useful indicator. It should rather have the commit hash instead but I don't know how to do that.

**Comment by 0x90d** [comment]
Github action, here is the workflow file https://github.com/0x90d/videoduplicatefinder/actions/runs/4385991460/workflow

**Comment by David-Maisonave** [comment]
After making some changes to my version of the [releases.yml](https://github.com/David-Maisonave/MediaFileDuplicateFinder/blob/master/.github/workflows/releases.yml) file, and a few changes to the program, I was able to get a version that includes the build date. I first tested this out locally on my machine by modifying the command line in releases.yml.

dotnet publish -c Release -v q --self-contained -r "${{ matrix.target }}" **--property:version=1.30.2023.0418**

The version has a max number length of 4, so the date is formatted in x.x.YEAR.MoDt.
If you're interested I can provide more details, or you can look at [releases.yml](https://github.com/David-Maisonave/MediaFileDuplicateFinder/blob/master/.github/workflows/releases.yml) and do a diff.

Although my releases.yml gets build and package gets compressed, it fails at the publish step with error 403, which is a permission error. Do you know how to set the permissions?
Where did you get the releases.yml script from?
I notice you have -o argument on your script, and that's not supported in dotnet anymore.  Are you still able to built your script?
