### ISSUE TITLE
Add Incremental Scan option

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#412]
**Environment**
 - OS: [Any]

**Describe the solution you'd like**
Add scan option for incremental scanning, where it only scans for any file changes made since the last scan, and then updates the results.

Using **ReadDirectoryChangesW** type API's, the program doesn't have to scan through all the files to compare time stamps, and instead it uses the file system journal to get a list of files which have been changed, deleted, or added since a specified time.

I found a cross platform equivalent to ReadDirectoryChangesW, called [fswatch](https://github.com/emcrisostomo/fswatch).

**Comment by 0x90d** [comment]
Library you mention is not a C# library. Unless you are going to make a PR this isn't really helpful. Is this just about making the file enumeration a little bit faster?
