### ISSUE TITLE
Scan results export to json failed

### ISSUE THREAD

**Issue by ChosenDango** [0x90d/videoduplicatefinder#413]
**Environment**
 - OS: Windows

**Describe the bug**
I get this error when exporting scan results to a json file, 
![image](https://user-images.githubusercontent.com/79312289/232648233-2cd4fa1b-036d-4549-9c4b-c94cd0f3bfaf.png)
![image](https://user-images.githubusercontent.com/79312289/232648329-5fc1e493-fb98-4d6e-9b23-cfe95d9f4987.png)
![image](https://user-images.githubusercontent.com/79312289/232649347-666f0329-e593-402c-8295-fdf6e1fc096d.png)
![image](https://user-images.githubusercontent.com/79312289/232649393-ecabde35-a387-4ca9-9317-b713c44505ed.png)

The json file gets created with scan results

**Expected behavior**
Scan results get exported to json file without error being thrown.

**Comment by 0x90d** [comment]
I cannot reproduce. Please provide files / scan results where it happens.
