### ISSUE TITLE
[Bug]: Custom Commands setting isn't remembered

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#417]
**Environment**
 - OS: [any]

## Describe the bug
The "**Custom Commands**" option is not working. 
- When selected combo item is changed to "**OpenItem**", there's no difference in behavior when double clicking the file.
- When the application is closed, the changed selection is not saved, and so when the application is reopened, the combo box goes back to the default selection "**OpenItemInFolder**".

## Expected behavior
- After changing selection, duplicating the file should result in the selected custom command.
- When closing the application, the combo setting should be saved, so on the next open session, combo setting reflects changed value.

**Comment by 0x90d** [comment]
> * there's no difference in behavior when double clicking the file.

There is. Open custom is applying to all selected items. Double clicking is only for a single item.

**Comment by David-Maisonave** [comment]
> There is. Open custom is applying to all selected items. Double clicking is only for a single item.

I don't understand. How is a user able to execute the custom command?
Can you please provide details?

**Comment by Maltragor** [comment]
Again, see #410 and #248

The combo box containing "OpenItem", "OpenItemInFolder", ... is not an configurable option itself.
For all Items in the combo box you can define an independent action.
The combo box is only used to select which action you want to modify next and does not change the behavior of any action. (And so it is not saved)

Example:
You want to define an custom command that replaces the open command.
=> Select "OpenItem"
=> Define the command in the edit box below.
(For demonstration under linux e.g.  `notify-send %f` _- tested with the current build_)

If you want to define additional commands for other actions, select an other action e.g. "OpenMultiple" an write your command in the edit box below.
=> The edit box always contains the command for the currently selected action. And this commands are the configuration and will be stored.

**Comment by Maltragor** [comment]
> double clicking the file

Double click on thumbnail executes the "OpenItem", double click on filename executes "OpenItemInFolder".
Alternatively pressing return while the active cell of the table is the thumbnail will execute the "OpenItem". If a cell in the path column is the active cell, pressing return will execute "OpenItemInFolder".
If no custom commands are defined for this two actions, VDF uses the build in commands.
The "OpenMultiple" / "OpenMultipleInFolder" is only supported by custom commands and is called when more then one row is selected.
