### ISSUE TITLE
[Bug]: Program (VDF.GUI.exe) does not start up from Windows File Explorer

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#419]
**Environment**
 - OS: [Windows 11]

**Describe the bug**
- I downloaded the latest version today of videoduplicatefinder, to check if the Custom Commands issues exist in the latest version, but when I tried running it from Windows File Explorer, it failed to run.  When I double click "**VDF.GUI.exe**" nothing happens, and I don't see anything listed in Windows EventViewer. I even tried **Run-As-Administrator**, but I got the same results. Nothing!
- I can run it if I start it from the DOS prompt. From the DOS prompt it runs as a regular user and as admin user.
- I thought this might be an issue with my computer, but I have an older version of videoduplicatefinder dated from 20-Apr-2023, and it runs from File Explorer with no problem. This leads me to believe it's not a My-Computer issue, and it's not a Windows 11 issue.
- I also created a shortcut to my desktop for both version.  The new version fails to launch from the shortcut, and the older version runs just fine.

**Expected behavior**
- It should be able to start from File Explorer just like the slightly older version.
- Shortcut to **VDF.GUI.exe** should work.

**Comment by 0x90d** [comment]
Try again, when it fails open event viewer and post me the crash details (the .NET crash details)

**Comment by David-Maisonave** [comment]
As I stated in the question, I don't see anything in event viewer.
I noted the time, and started VDF.GUI.exe.  Nothing happens. When I look at Event Viewer, nothing is logged in that time frame.
I just started it again at 11:30PM, and I closed and reopened Event Viewer to make sure it has the latest events.
<img width="470" alt="EventViewerSnapshot" src="https://github.com/0x90d/videoduplicatefinder/assets/47364845/aa68f972-b249-40e3-9e20-609b705e20c7">

Is there a different tree-node I should be looking at in Event Viewer?

**Comment by 0x90d** [comment]
Important notes, especially crashes are usually in "Custom Views". However if nothing is in the event viewer, the program hasn't crashed. Nothing for me to do. Instead it likely got closed, by another software, likely your security software.

**Comment by David-Maisonave** [comment]
>>Instead it likely got closed, by another software, likely your security software.
A security software would also close the program if called from DOS prompt.

I was hoping this was reproducible on your end.

I'll close this out, unless I can get more information.
