### ISSUE TITLE
More than one thumbnail causing attached error

### ISSUE THREAD

**Issue by reddyshyam** [0x90d/videoduplicatefinder#42]
Windows 10 64 bit pro 1903 (18362.53)

1 thumbnail works flawlessly but if I set 2 or more, attached error throws up.

![Screenshot_20190423_182859](https://user-images.githubusercontent.com/12392746/56582931-0282d680-65f6-11e9-96d9-908938ab52fa.png)

**Comment by crfloyd0932** [comment]
this was resolved in the 2nd to latest build. you will need to download the latest source code and run the build.bat file. the current "release" doesn't include the fix for this.

**Comment by reddyshyam** [comment]
Thanks @emdx71 for getting back. I am not able to build on my windows machine. Can I know the prerequisites please? Previously tried to install dotnet and dependencies but ended by with conflicts and not able to compile.
