### ISSUE TITLE
[Feature Request]: Add a view option to main view that would optionally display the search directory.

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#420]
**Environment**
 - OS: [Any]

**Describe the solution you'd like**
The first time I tried VideoDuplicateFinder, I was really confused as to how to get started, since the search directory option was in a separate view, and it's under Misc at the bottom of that view. The Search-Directories option should not be under miscellaneous, because you really can't do much without using this option. Miscellaneous options are options that are NOT important to the main function of a program.  
I believe some new users would give up trying to figure out how to use the program.

I recommend adding an option similar to the Sort/Filter option, which when selected would hide or display the search directory fields. The option should be enabled by default, so new users can immediately see how to add the folders.
<img width="447" alt="DirectoriesOption" src="https://user-images.githubusercontent.com/47364845/236919066-a60af8f2-6480-42e8-8391-c16b64015273.png">

If the user wants the additional screen real-estate, they can disable the view via a checkbox.
<img width="435" alt="DirectoriesOption_Disabled" src="https://user-images.githubusercontent.com/47364845/236919408-27f31ddf-5987-4ccd-a990-2e73282e8651.png">

To consume less toolbar space, you can put the Filter/Sort option and the Directories option under a **View** drop-down that would list both options like I did.
When I implemented this, I didn't even have to change the original settings, and changing the values in the Misc view automatically changes in the main view, and V.S.

If you replace the checkbox with three [RadioButton ](https://docs.avaloniaui.net/docs/controls/buttons/radiobutton) it will automatically deselect the other options, so the Directories option is not displayed on top of the Sort/Filter option.
<img width="419" alt="RadioButtonOption" src="https://user-images.githubusercontent.com/47364845/236938512-d9989f82-9694-4443-8283-e673d3f41979.png">

Example Radio Buttons Code
```
<MenuItem>
	<MenuItem.Header>
		<StackPanel Orientation="Horizontal">
			<TextBlock
				Margin="5,0,0,0"
				VerticalAlignment="Center"
				Text="View" />
			<Path
				Margin="4,2,0,0"
				VerticalAlignment="Center"
				Data="M 0 0 L 6 6 L 12 0 Z"
				Fill="{DynamicResource SystemBaseHighColor}" />
		</StackPanel>
	</MenuItem.Header>
	<RadioButton IsChecked="{Binding ElementName=GridDirectories, Path=IsVisible}" GroupName="View Group" Content="Directories"/>
	<RadioButton IsChecked="{Binding  ElementName=GridFilter, Path=IsVisible}" GroupName="View Group" Content="Filter / Sort"/>
	<RadioButton GroupName="View Group" Content="None"/>
</MenuItem>
```

**Comment by 0x90d** [comment]
It was on main page. People complained it took too much space so it was moved to settings page. It doesn't make sense to split up settings on different page. If you start a scan without specifying search directories you'll get a message.
