### ISSUE TITLE
[Feature Request]: Add support for audio comparison

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#421]
**Environment**
 - OS: [Any]

**Describe the solution you'd like**
From what I can tell, ffmpeg supports audio comparison.
I like to see audio comparison support added to VDF.

**Comment by 0x90d** [comment]
From what I can tell, VDF already compares audio. I like to see more details about what exactly you want and how VDF benefits from it.

**Comment by David-Maisonave** [comment]
> From what I can tell, VDF already compares audio.

Sorry. I see now how my question could be misunderstood.
I'm referring to audio **file** comparisons and not to the audio within a video file.
Audio files like mp3, wav, wma, mp2, m4a, etc....
This would help users find duplicate audio/music files which could be in different formats, file types, or slightly different duration.

FileUtils.cs has VideoExtensions and ImageExtensions. I'm requesting to add AudioExtensions.
Example:
```
public static readonly string[] AudioExtensions = {
	".aac",
	".aiff",
	".amr",
	".flac",
	".m4a",
	".m4b",
	".mp2",
	".mp3",
	// ".mpeg", // Need to figure out a way to programmatically differentiate between Video and Audio
	".ogg",
	".voc",
	".wav",
	".wma"
};
```
And adding the supporting code that would go with this.

**Comment by David-Maisonave** [comment]
FYI:
I originally thought VDF already supported audio file comparisons, and I created a collections of audio files to test it. When it didn't show up in the results is when I realize it was not supported.
If you're interested in implementing this feature, you can use the following attached file which includes a small set of audio files.
[AudioTestFiles.zip](https://github.com/0x90d/videoduplicatefinder/files/11447947/AudioTestFiles.zip)

**Comment by 0x90d** [comment]
VDF is a duplicate finder for (mostly) videos because at the time this project was published, nothing like this have exist for free. Image support only exist because of low implementation costs. I dont have any plans for comparing audio (or any other kind of) files. There might be better tools for this already.
