### ISSUE TITLE
[Enhancement]: (Possible user error/bug) - thumbnails so small that image content is indistinguishable

### ISSUE THREAD

**Issue by Foxxsayy** [0x90d/videoduplicatefinder#424]
## Environment
 - OS: Windows 11
 - 
## Describe desired feature
I have just found videoduplicatefinder and run a search, and it seems great other than I can't _see_ anything in the thumbnails well enough to tell what they are. I'm not sure if this is just how it is or I missed a setting somewhere.

As you can tell from the included snapshot, the video does appear to be the same, but I have no way of telling what the heck it is. It is entirely impossible to distinguish whether this is a duplicate or an alternate or, in some cases, even a very, very similar video. 

I would like to be able to be able to clearly see the frames to distinguish whether I should keep a video. If the images are being loaded into RAM, perhaps a temporary folder for screenshots could be used instead?

### What issue does it solve?

Solves issue of not being able to see anything beyond vague blurs, allows ability to distinguish between alternates and true duplicates.

### Snapshots
Optionally add images which can help describe the feature.

**Comment by 0x90d** [comment]
You can zoom thumbnails, use slider at the top right. If you need high quality thumbnails right click on an item -> selected group -> compare fullsize thumbnails

**Comment by Foxxsayy** [comment]
> You can zoom thumbnails, use slider at the top right. If you need high quality thumbnails right click on an item -> selected group -> compare fullsize thumbnails

Thanks, I totally missed that feature. (It would still be handy to be able to see them in the normal preview.)

Unfortunately, the only thing that's happening when I select that option is it's popping up with a grayed out box.
![image](https://github.com/0x90d/videoduplicatefinder/assets/98929636/7dd29cb2-fbf7-4816-a6e0-17b7b85d7df7)

**Comment by 0x90d** [comment]
It would be but only in your scenario. In another scenarios where either the thumbnails are pretty clear to distinguish or in cases where you got thousands of entries, high quality images are a problem.

Have you clicked on an image / filename at the left of this window?

Depending on the location / videos etc. it could also take some time before the images are shown. You might also try it with a different group to see if its not specific videos causing this behavior.
