### ISSUE TITLE
[Bug]: Native FfMpeg binding

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#425]
## Environment
 - OS: [Windows]

## Describe the bug
 - The readme page still shows 5.0 requirement for binding, even though 6.0 share works.
   - I recommend specifying  that **gpl**-shared is required, because it doesn't work with **lgpl**-shared.
 - I ran a test using both FFMpeg 5.0 and 6.0 on Windows which gave unexpected results.
   - Native mode only had about a 10% improvement, and missed duplicates.
   - The 10% performance difference could be due to the more accurate logic being performed by the non-native mode.

## Snapshots
- 5.0 FfMpeg binaries
  -<img width="470" alt="NativeFfmpegPerformance_5 0" src="https://github.com/David-Maisonave/MediaFileDuplicateFinder/assets/47364845/3d06c1ee-0b81-454a-8676-06f4afc59f7e">
- 6.0 FfMpeg binaries
  -<img width="469" alt="NativeFfmpegPerformance_6 0" src="https://github.com/David-Maisonave/MediaFileDuplicateFinder/assets/47364845/09f946f1-141e-425d-ba8c-92ebfe98db51">

## Expected Behavior
- The non-native mode should find the same amount of duplicates.
- The **ToolTip** text for this option should be changed from "This is MUCH(!!) faster" to "This is faster". Also consider mentioning accuracy issues.

**Comment by 0x90d** [comment]
> * The non-native mode should find the same amount of duplicates.

This ain't possible as I have no control over ffmpeg changes. For example one release of them could stop working with a specific video control and render screen black giving different results in VS.

You can submit a PR to update the readme page if you want.
