### ISSUE TITLE
[Bug]: weird naming with mixed persian and english characters in filename

### ISSUE THREAD

**Issue by rezad1393** [0x90d/videoduplicatefinder#426]
## Environment
 - OS: linux

## Describe the bug
 - A clear and concise description of the bug.
 - What happen, and what did you expect to happen?
 - What are the steps to reproduce issue?

I am trying to clean up duplicates in youtube videos I downloaded with jdownloader.
the address of files is this:
/mnt/multimedia/watching-list/فیلمفارسی/
the two files it finds are:

"Topoli - فیلم تپلی (FilmFarsi - فیلمفارسی) 360p 25fps VP9 AAC128-2020.08.18-1h_57m_26s (VxKnqahB5Jg).mkv"
"فیلم قدیمی - ‫تپلی با شرکت همایون، مرتضی عقیلی، زری خوشکام ۱۳۵۱   Topoli‬‎ (FilmFarsi - فیلمفارسی) 360p 25fps VP9 AAC128-2019.08.19-1h_57m_26s (Q4MiGUUf9pE).mkv"
as you can see the names have english and persian words in them. 
and the resolution part of the video which is part of filename is 360p in english.

but in videoduplicatefinder app the name is shown as 

![2023-06-02_21-23](https://github.com/0x90d/videoduplicatefinder/assets/7523164/578266ed-bcf3-4164-8221-12fd75b5ea64)

the 360p is shown as ۳۶۰p in persian.

**Comment by 0x90d** [comment]
VDF uses Avalonia as UI framework so this would be an Avalonia issue: https://github.com/AvaloniaUI/Avalonia/issues

**Comment by rezad1393** [comment]
should I report it there or do you as the developer report it?
