### ISSUE TITLE
[Help]: cannot find shared FFmpeg libraries

### ISSUE THREAD

**Issue by keeepman** [0x90d/videoduplicatefinder#427]
## Environment
 - OS: Windows11

## Question
I placed the bin folder in the downloaded FFMPEg-5.0-full_build-shared in the same folder as vdf.gui.dll, and configured the windows environment variable PATH. ffmpeg can run normally in the windows terminal, but open VDF.GUI. The message cannot be found, so I am not sure how to arrange the ffmpeg folder so that the program can find it

**Comment by 0x90d** [comment]
Make sure you use the GPL version: https://github.com/BtbN/FFmpeg-Builds/releases

**Comment by keeepman** [comment]
> 确保使用 GPL 版本：https://github.com/BtbN/FFmpeg-Builds/releases

Hello, I downloaded `ffmpeg-n5.1.3-14-ge5b5dd6653-win64-gpl-shared-5.1.zip` from this address according to your suggestion. I also set the environment variable PATH and put the bin folder in the same folder as vdf.gui.dll. The startup still can't find  ffmpeg libraries

**Comment by Jakob6174** [comment]
Hey try [ffmpeg-n6.0-latest-win64-gpl-shared-6.0.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.0-latest-win64-gpl-shared-6.0.zip)
That should work. You don't need to add it to PATH

**Comment by 0x90d** [comment]
I guess using 6.0 has solved the issue?
