### ISSUE TITLE
[Help]: How does VDF actually compare video files?

### ISSUE THREAD

**Issue by Foxxsayy** [0x90d/videoduplicatefinder#431]
Apologies if I missed a readme somewhere, but I noticed this tooltip was wondering how VDF actually compares video files?
![image](https://github.com/0x90d/videoduplicatefinder/assets/98929636/01af6534-2e47-4ffa-bb9e-d611ddd98ead)

I assume it's got to be more than solely comparing X number of snapshots, so how does VDF actually do comparisons, and how does the number of thumbnails generated play into that?

**Comment by 0x90d** [comment]
Each thumbnail gets converted into graybyte values which VDF then compares and see if the similarity is above the value you set. The more number of thumbnails per video, the less false positives you will get.

**Comment by Foxxsayy** [comment]
Thanks 👍
