### ISSUE TITLE
[Help]: I want to erase an old large file!!

### ISSUE THREAD

**Issue by gehenna3702** [0x90d/videoduplicatefinder#433]
## Environment
 - OS: [e.g. Windows / Linux / MacOS ]
window

## Question
A clear and concise detailed question.

The video file size is too large.

so

I did a resize.

I want to erase an old large file.

But I can only select a small file, so I need some help.

There seems to be a custom setting, but I can't quite figure out how to do it.

What should I do..

I NEED HELP!!!!!!

thank you!

## Snapshots
Optionally, include snapshots to help clarify the question.

**Comment by 0x90d** [comment]
I don't really know what you are trying to say. Can you provide a screenshot?

**Comment by gehenna3702** [comment]
![2023-07-06 14 47 41](https://github.com/0x90d/videoduplicatefinder/assets/77250986/1441db81-3c91-45ee-bf86-767dbe136fef)


So... I want an invert selection function! Current function clears low capacity. But I want to clear high capacity.

**Comment by gehenna3702** [comment]
I solved it by reading this article.

Someone asked before.

https://github.com/0x90d/videoduplicatefinder/issues/366

in answer

!arg.ItemInfo.IsBestSize
The !has the meaning of not.

This part was difficult... (I have no knowledge in this area).

!item.IsBestSize

It was really difficult. It felt like my head was about to explode.

I barely found it.

Command to clear high capacity.

Thank you!!

This program is the best duplicate video remover!!
