### ISSUE TITLE
[Bug]: must install .NET desktop runtime

### ISSUE THREAD

**Issue by penguinpatrol** [0x90d/videoduplicatefinder#434]
Environment
 - OS: Windows 
 
Describe the bug
constant error window saying i must install .NET desktop runtime even though i have installed the version it says its on? and clicking the "yes" button does nothing,
 
![image](https://github.com/0x90d/videoduplicatefinder/assets/117539617/0e7cd807-74b0-4e83-a876-4e18eb26dd95)

**Comment by 0x90d** [comment]
Have you extract all files to a folder before ran it? What is your windows version? Bitness?

**Comment by penguinpatrol** [comment]
i dont know what i did, but i did a clean reinstall and it seems to work now?
