### ISSUE TITLE
[Help]: Why does VDF 2.0 find more duplicates than 3.0?

### ISSUE THREAD

**Issue by mkalmajid** [0x90d/videoduplicatefinder#437]
## Environment
 - OS: Windows

## Question
I tried running both version 2.0 and 3.0 in the same folder for multiple folders, and 2.0 would almost always find more duplicates than 3.0, why is that the case? I tried tweaking the settings in both versions, and surprisingly 2.0 could find more duplicates on an even higher percentage than 3.0, which makes it difficult for version 3.0 to find the same duplicates without running into false-positives.

I would honestly prefer to have the 2.0 algorithm over the 3.0 program for its functionalities but i'm aware i'm asking for too much. I'm just wondering why the upgraded version seems to perform worse than its predecessor.

**Comment by 0x90d** [comment]
Can you provide example files which 2.0 detects but 3.0 does not?

**Comment by 0x90d** [comment]
> Yes, I've encountered that too. For some images, even if I adjust the similarity, I can only find it in 2.0

Can you provide example files which 2.0 detects but 3.0 does not?

**Comment by 0x90d** [comment]
I'm afraid that without media files to reproduce I cannot say much about it. It could be a bug or it could also be just a confusion as 3.0 has a lot more settings. Thus you will get different results by nature. Depending on the settings the results can be better or more worse.

**Comment by 0x90d** [comment]
I'm closing it as nobody provided example files.
