### ISSUE TITLE
[Bug]: "custom selection" is broken

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#439]
## Environment
 - OS: Windows 10 x64

This section of the program never worked. No help or examples are given to the user to try.
A word being part of the path won't trigger any selection. The "Path does NOT contain" part does what it wants to do instead what its being told to, for me it selects files when left empty, and when adding a word it doesn't do anything.

**Comment by 0x90d** [comment]
Next, the "path does not contain" is actually a list and if the list is empty, it doesn't do anything. So I have no idea what you mean with "when left empty". And if you add a word and its only a part of the path you must surround it with `*` for example. Which it also says right at the bottom of the list.

If you still have issues post screenshots or anything that shows me a specific situation.

**Comment by 0x90d** [comment]
Works as expected:

https://github.com/0x90d/videoduplicatefinder/assets/46010672/bc615dce-e4dd-421b-9960-393f9510078d
