### ISSUE TITLE
Adding things back

### ISSUE THREAD

**Issue by thevetteguy** [0x90d/videoduplicatefinder#44]
Can you add the 'Zoom' feature back?  I have a 4K monitor and everything is pretty small.  Also, having colored bars splitting up each set of matches made it easier to decide what to keep.

Also, the sorting seems to be gone.  In the old version I was able to sort by size so the largest was always the last item listed … made it easy to click down the list.

BTW .. I tried to add this as a 'pull request' but I could not get the system to let me create a new one .. even after creating an account here.

**Comment by 0x90d** [comment]
Added with latest commit, not into a compiled release yet.
