### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by UredNuubjuz** [0x90d/videoduplicatefinder#441]
## Environment
 - OS: Windows 10 home

## Question
I am not sure if its allready doing that but can it compare Images to Videos? Not just Images to Images and Videos to Videos. Lets say you have a bunch of Movies on your Storage. you take a Screenshot from one of your Movies but you dont remember which Movie it was. Can this Program find Images belonging to certain Movies or videos?
I have thousands of Thumbnails that belong to some original Media File.

If this does not exist as of now, i would be happy if it could be implemented in the Future.

**Comment by 0x90d** [comment]
No it doesn't / cannot and there are no plans for such a feature.
