### ISSUE TITLE
[Help]: What does "Scan against entire database" mean?

### ISSUE THREAD

**Issue by King555a** [0x90d/videoduplicatefinder#444]
## Environment
 - OS: Windows 10 22H2 x64

## Question
There is a setting called "Scan against entire database". What does this mean, what does it do? I mean, the program should _always_ compare a file with every file in the database, shouldn't it? Or has it another meaning?

## Snapshots
![scandb](https://github.com/0x90d/videoduplicatefinder/assets/126968427/b701d2d3-4dff-4352-be07-9b6293b4bc2a)

**Comment by 0x90d** [comment]
If you mouse hover, the tooltip has an explanation. This option is important if you are going to change the "include directories". If checked, it will also scan against database files which are NOT part of these directories. If unchecked it only scans the directories you have in your list.
