### ISSUE TITLE
[Bug]: 3 files are always detected as malware (false-positives, of course)

### ISSUE THREAD

**Issue by King555a** [0x90d/videoduplicatefinder#445]
## Environment
 - OS: Windows 10 22H2 x64

## Describe the bug
Since several versions, I think it's since VDF was upgraded to .NET 7, my anti-virus software (Norton 360 from Symantec) detects these files as viruses every time I extract a new version to my hard drive: VDF.Core.dll, VDF.GUI.dll, VDF.GUI.exe (although today for the first time the EXE was not detected).

I know this is not a real "bug", but maybe there is some setting or work-around which makes the compiled files less "suspicious".

At least I just wanted to let you know that this may be a problem on some computers.

## Snapshots
![norton](https://github.com/0x90d/videoduplicatefinder/assets/126968427/22cc7e48-94b8-4aa3-9193-d42c65807542)

**Comment by 0x90d** [comment]
Not much I can do. It doesn't even detect any threat, it only thinks its "suspicious". I know this answer sounds very unhelpful but unfortunately its a problem of Norton (or any other AV) that they generate false reports and its up to them to fix their detection engine.
