### ISSUE TITLE
[Help]: Manual

### ISSUE THREAD

**Issue by KamuiX** [0x90d/videoduplicatefinder#446]
## Environment
 - OS: Any

## Question
Is there any manual available for the software?  I start using VDF 2 days ago and seems to work good and the speed is awesome. Although I am afraid that there are more features that I can use but there are "hidden" inside these non descriptive settings (Like search for an episode inside a bigger video file that includes many episodes concatenated)

Thanks

**Comment by 0x90d** [comment]
Currently there is no manual. But most settings have a tooltip giving more information. Anything specific you need help with?

**Comment by KamuiX** [comment]
Seems I moved my mouse so quickly all the time that I haven't got the chance to see a tooltip popup. Thanks

Maybe my only question is about "Duration Difference"

If I understand correctly if this value is on 20% then a 5mins video will be compared to all 4mins up to 6mins videos. But I suppose this is not the case because this value goes up to 100% meaning a 5mins video can be compared to a 0min up to 10mins....and of course there are videos that play for 2-3-4 hours. 

Is this a limitation or am I getting this setting wrong?

**Comment by 0x90d** [comment]
Your understanding is correct. However you likely won't get any matches by comparing a 5 minute video against a 2 hour video by how VDF detect duplicates. Even 20% are very optimistic.

**Comment by KamuiX** [comment]
Great great thanks @0x90d! I suppose there is no reason to open a "Feature request" as this limitation is something the team working on it or it's just impossible to implement because of how VDF algorithm works.

**Comment by KamuiX** [comment]
Great great thanks @0x90d! I suppose there is no reason to open a "Feature request" as this limitation is something the team working on it or it's just impossible to implement because of how VDF algorithm works.

**Comment by KamuiX** [comment]
Great great thanks @0x90d! I suppose there is no reason to open a "Feature request" as this limitation is something the team working on it or it's just impossible to implement because of how VDF algorithm works.
