### ISSUE TITLE
How do you run this [Help]: 

### ISSUE THREAD

**Issue by tpoba4** [0x90d/videoduplicatefinder#449]
## Environment
 - OS: [e.g. Windows / Linux / MacOS ]

Win

## Question
A clear and concise detailed question.

I've installed FFmpeg, add the variable, install git, and cloned the rep, but I don't know what command I should execute to get the GUI.

## Snapshots
Optionally, include snapshots to help clarify the question.

**Comment by reddyshyam** [comment]
Hi @tpoba4,

Please download latest release ([App-win-x64.zip](https://github.com/0x90d/videoduplicatefinder/releases/download/3.0.x/App-win-x64.zip)) from https://github.com/0x90d/videoduplicatefinder/releases/tag/3.0.x

Extract to a folder, drop ffmpeg libraries (ffprobe.exe, ffplay.exe, ffmpeg.exe) downloaded from https://ffmpeg.zeranoe.com/builds/

After the above, double click VDF.GUI.exe and you should see the UI. Hope this helps.

Everything is clearly explained on homepage https://github.com/0x90d/videoduplicatefinder.

**Comment by 0x90d** [comment]
As you were speaking about just running the GUI I assume that @reddyshyam instructions already solved your issue. If not please reopen.

**Comment by tpoba4** [comment]
Hi guys, 

apologies for the delay. Just wanted to confirm that your solutions worked.

The app is super fast compared to the previous one I've used (video comparer).

Again, thanks heaps for the help!
