### ISSUE TITLE
What is the video comparison algorithm?

### ISSUE THREAD

**Issue by xnoreq** [0x90d/videoduplicatefinder#45]
I assume you create thumbnails at some positions in the video and compare those.

- What's the size/resolution/color palette of the thumbnails?
- What algorithm is used to compare thumbnails?
- What happens if multiple thumbnails are made? Is one thumbnail match against any other video's thumbnail enough to classify as duplicate?
- What's the distribution of the timestamps?
- How does it deal with duplicates that have a few seconds offset from each other?
- How does it deal with split/joined videos (consider a single file vs. split by disk for example)?

Thanks.

**Comment by 0x90d** [comment]
1. 16x16, grayscaled or mjpeg
2. Custom version of comparing grayscaled images while allowing a percentage difference
3. All thumbnails must match
4.  video length * (1 / ( thumbnailcount + 1))
5. No match
6. No match

For performance reasons it doesn't deal with last two situations. The amount of performance drop is no argument to deal with rare situations like these. Although I'm not holding anyone back to submit a PR to add this as an optional feature.
