### ISSUE TITLE
[Enhancement]: Update project dependencies

### ISSUE THREAD

**Issue by felipe19930** [0x90d/videoduplicatefinder#454]
## Describe desired feature
The project currently relies on a preview version of Avalonia, so I think the project as whole would benefit greatly from this upgrade, since there's been [*a lot of bug fixes*](https://github.com/AvaloniaUI/Avalonia/compare/11.0.0-preview4...11.0.4) between `11.0.0-preview4` and `11.0.4` (the current, latest version).

I tried doing the upgrade myself, and I succeeded to some extent (lol), but due to lack of C# experience I got stuck on these three compiler errors that for the life of me I do not know how to fix... :sweat_smile: 

### What issue does it solve?
Just bugs in general. But I have nothing specific in mind.

**Comment by felipe19930** [comment]
Okay, I believe to have finally succeeded. I'm currently testing for regressions/incompatibilities, but so far everything seems in order!

The list of changes is actually not *that* extensive, so I think an experienced C# developer would be able to migrate to this new version Avalonia very quickly.

In any case, if you're not interestind in this right now, just let me know and I'll open a pull request with my changes. Just keep in mind that I'm not a C# dev, so the code quality might not be up to your standards. :)

**Comment by 0x90d** [comment]
I tried updating it and facing once again a lot of breaking changes and I wouldn't be surprised if there is no documentation about that. At least I couldn't find it.

Feel free to make a PR
