### ISSUE TITLE
[Help]: Scan returns 0kbs bitrate on some files

### ISSUE THREAD

**Issue by FabulousTiger** [0x90d/videoduplicatefinder#455]
## Environment
 - OS: Windows 11

## Question
When I run a scan a lot of the files return with 0kb bitrate but a quick opening of file properties or a mediainfo. It would show the correct bitrate.
I have tried with and without hardware acceleration in case some weird issue there. Did not change. I had to go into each file with 0kb and verify its bitrate to make sure I didn't delete the wrong one. I have 3 more libraries to do this on and would appreciate any help. The files are on a smb share if that has anything to do with it.

## Snapshots
https://i.imgur.com/u3zAd9a.png
## Including settings if it would help
https://i.imgur.com/GYQOUvv.png
https://i.imgur.com/yBwFaSf.png

**Comment by 0x90d** [comment]
Run ffprobe you're using on these files and see if it reports 0kbs bitrate as well. If so it's either invalid metadata of the file or a bug in ffprobe.

The best would be if you could share a sample file.

**Comment by FabulousTiger** [comment]
I ran a few files through ffprobe, and they all gave me bitrate. The problem file did have a few pgssub streams it couldn't find codec parameters for.

> [matroska,webm @ 0000020c9d0609c0] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

 But that's okay in my book. Unless that is what caused it to not give me the bitrate readout in the app.

I can try it in a Linux VM later to see if it works there. If it does that i guess solves the issue for me I guess tho I won't have GPU acceleration, but that won't matter if it works :D But if you have any other thoughts I would appreciate it.

**Comment by 0x90d** [comment]
There was a recent commit that fixes reading bitrate if its a high number. You can try the latest version of VDF. You may want to delete the specific files from database first. LMK

**Comment by FabulousTiger** [comment]
Tried it, on a Linux vm now too with the newest VDF and deleted database 5o make sure there were no old info when I retried. Still 0kb on alot of files. But it still helped me gather same or almost same file and just manually checking bitrates. And delete the non preferred ones.

**Comment by 0x90d** [comment]
Can you tell me the bitrate or provide me with ffprobe output of the files where VDF failed?
