### ISSUE TITLE
[Bug]: [dotnet-sdk-8.0.100-rc.1.23415.7] videoduplicatefinder fail to import Scan Result with System.InvalidOperationException

### ISSUE THREAD

**Issue by Junjun-zhao** [0x90d/videoduplicatefinder#456]
## Environment
**Application Name**: videoduplicatefinder
**OS**： Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-8.0.100-rc.1.23415.7

## Describe the bug
When run this application with .NET 8 RC1 build, it failed to import the scan results.  This issue is an expected breaking change from .NET8, please refer to the breaking change issue https://github.com/dotnet/docs/issues/37041 for the recommended action. 

In additional, you can refer to the https://github.com/dotnet/runtime/issues/91048 for more details of this issue.

## Snapshots

![videoduplicatefinder](https://github.com/0x90d/videoduplicatefinder/assets/83067197/a63d62ac-609b-416e-a012-c0cc42c29250)

**Comment by 0x90d** [comment]
Thank you
