### ISSUE TITLE
[Help]:  How do I know which type of hardware acceleration I should use?

### ISSUE THREAD

**Issue by EldrinSMP** [0x90d/videoduplicatefinder#459]
## Environment
 - OS: Windows 11 PRO

## Question
When using native FFMPG binding, you have to directly specify what type of hardware acceleration to use, instead of setting it to "Auto". How do I know which one of the hardware acceleration types are compatible with my hardware?  The only one that I am familiar with is CUDA, and I do know that my system is compatible with it (checked the hardware compatibility on the NVIDIA website). Also, if my system IS compatible with more than one type, is there any way to test which is the most efficient / speeds up the scans the most?  I appreciate any help you guys can give.

**Comment by 0x90d** [comment]
Hardware acceleration is based on ffmpeg. Maybe this helps you: https://trac.ffmpeg.org/wiki/HWAccelIntro#PlatformAPIAvailability scroll down for a detailed description of each HW type.
