### ISSUE TITLE
An exe build

### ISSUE THREAD

**Issue by nokarukuta** [0x90d/videoduplicatefinder#46]
Hi, can you add a compiled version for windows? Or instructions on how to do it for people with no programming experience

**Comment by 0x90d** [comment]
You can find a compiled version right here https://github.com/0x90d/videoduplicatefinder/releases click on "Assets" and then choose the windows build

![image](https://user-images.githubusercontent.com/46010672/60399380-2234fe80-9b53-11e9-9648-bd5cc72cb536.png)
