### ISSUE TITLE
[Bug]: VDF Closes

### ISSUE THREAD

**Issue by bonifaciukdev** [0x90d/videoduplicatefinder#460]
## Environment
 - OS: Windows

## Describe the bug
 - VDF closes.
 - Expected to have results shown in window from completed search or during search.
 - Attempt to search files and occasionally happens. The cause might be from using larger data.

## Snapshots
[Optionally, include snapshots showing the issue.](https://gofile.io/d/Y6m0Sg)

**Comment by 0x90d** [comment]
Try and deactivate "Generate preview images" in VDF settings. Otherwise please provide crash log from event viewer.
