### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by RoroRoze** [0x90d/videoduplicatefinder#461]
## Environment
Windows 10

## Question
- What is the name of the default database? When no custom database folder is selected
I know it is in the same folder but which file ? 

- What does the database store inside (What is it used for)? 
If I scan one HDD and then unplug it, and plug another HDD and scan it, will it find the duplicate from the unplugged HDD ? (Assuming the first scan did save the video info of the first HDD in the database)

**Comment by 0x90d** [comment]
> * What is the name of the default database

ScannedFiles.db

> * What does the database store inside (What is it used for)?

Information about the file and gray bytes it uses for duplicate detection so it doesn't have to fetch it on every scan.

> * If I scan one HDD and then unplug it, and plug another HDD and scan it, will it find the duplicate from the unplugged HDD

Assuming that it got all the necessary information from your first scan and you enabled 'Check against entire database' and also 'Scan against non-existing files', then yes.
