### ISSUE TITLE
[Bug]: Select Lowest Duration/Quality

### ISSUE THREAD

**Issue by chchia** [0x90d/videoduplicatefinder#462]
## Environment
 - OS: Windows 11

## Describe the bug
Using latest daily build, if using Selection for Select Lowest Duration/Quality, it select the one with higher quality even tough duration is same.

## Snapshots
![image](https://github.com/0x90d/videoduplicatefinder/assets/1291771/0c5c808a-9ec5-4a10-8672-8545416cca17)

**Comment by 0x90d** [comment]
This is expected behavior, the order is:

1. Duration
2. Resolution
3. FPS
4. Bitrate
5. etc.

The FPS of your first video is less than the second video. Thus it got selected.
