### ISSUE TITLE
[Bug]: "Scan against entire database" not working correctly??

### ISSUE THREAD

**Issue by evildemonx** [0x90d/videoduplicatefinder#463]
Currently using 3.0.x

Attempting scan on the selected folder with "scan against entire database" **unchecked**. However, it appears the program is comparing the selected folder content against the previously scanned results.

Unsure if this is the intent of the function, else, is there a way to ignore previous scan database/history?

**Comment by 0x90d** [comment]
Does the content of the previously scanned results show up as duplicates in VDF? Or are you just referring to the bottom status bar?

**Comment by evildemonx** [comment]
thanks for taking the time.
I'm referring to the bottom status bar
