### ISSUE TITLE
[Help]: what is "failed to retrieve graybytes" and "duration difference" in setting? dont understand

### ISSUE THREAD

**Issue by JerryPong0410** [0x90d/videoduplicatefinder#466]
## Environment
 - OS: [e.g. Windows / Linux / MacOS ]

## Question
A clear and concise detailed question.

## Snapshots
Optionally, include snapshots to help clarify the question.

**Comment by 0x90d** [comment]
Graybytes are retrieved from media files and used for checking against duplicates. If it fails to retrieve, the media file is excluded from scan.

Mouse hover settings options and you will get a description of the feature.
