### ISSUE TITLE
[Enhancement]:  Show original photos

### ISSUE THREAD

**Issue by lupengji** [0x90d/videoduplicatefinder#467]
## Environment
 - OS: [e.g. Windows / Linux / MacOS ]

## Describe desired feature
When the mouse is moved to the scanned photo, the original photo is displayed through a pop-up box for easy visibility of details

### What issue does it solve?
Thumbnail too small to see details clearly

**Comment by 0x90d** [comment]
Right click -> selected group -> compare fullsize thumbnails
