### ISSUE TITLE
[Enhancement]: Finding compared to database

### ISSUE THREAD

**Issue by requireyan** [0x90d/videoduplicatefinder#469]
## Describe desired feature
Show files on the harddrive compared to database.
("in database" checkmark)

First time you scan the file it is added to database, next time you scan the file it will show as duplicate.

### What issue does it solve?
Got a new batch of files, I want to delete files that have previously been scanned. Thus cleaning the drive from the files found in database.

**Comment by 0x90d** [comment]
I'm sorry but I dont understand what you are asking for. Can you rephrase please?
