### ISSUE TITLE
[Help]: ffmpeg confusion

### ISSUE THREAD

**Issue by sirtvib** [0x90d/videoduplicatefinder#470]
OS: Windows

I'm sure I'm messing something up because I'm not too familiar with advanced files and code and everything, but I have ffmpeg.exe and ffprobe.exe in the same folder as vdf.gui.dll but it says it cannot find the shared libraries. I've tried a bunch of combinations with what goes in what folder and bin folders but I can't seem to get it right.

**Comment by anon90000** [comment]
The instructions aren't very good.

**Comment by JamesPous** [comment]
You copied your ffmpeg files to the wrong folder!
This is the reason why VideoDuplicateFinder may not work correctly.

**Try the following steps:**

1. Download the ffmpeg shared version (!) 6.1 for windows from the following official website or link.
[ffmpeg-release-full-shared.7z](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z)

2. Open the archiv with 7zip
3. Extract the files to a temporary folder (e.g. C:\tmp\)
4. Open Windows Explorer and look into the extracted folder (e.g. C:\tmp)
5. You can see a ffmpeg-6.1-full_build-shared folder
6. Open the folder and open the subfolder 'bin'
7. Mark all files within the folder 'bin' (11 files)

![Clipboard01](https://github.com/0x90d/videoduplicatefinder/assets/85449576/1431c72a-903a-452e-9fcc-effe9c62cacc)

8. Copy the marked files to the 'bin' folder within your 'VideoDuplicateFinder' folder
9. Start VideoDuplicateFinder and everything works fine!
