### ISSUE TITLE
[Help]: If I manipulate the program after completing the duplicate scan of the file, the program suddenly turns off.

### ISSUE THREAD

**Issue by blackaloe** [0x90d/videoduplicatefinder#472]
## Environment
 - OS: Windows 

## Question
I think the meaning may change because of the use of a translator. Please understand.
It duplicates a file with a capacity of about 8 terabytes and then suddenly turns off without any symptoms while using the program.

## Snapshots
Optionally, include snapshots to help clarify the question.

**Comment by 0x90d** [comment]
Provide crash details from windows event viewer
