### ISSUE TITLE
[Help]: How do I start the application on Ubuntu?

### ISSUE THREAD

**Issue by JohannesWiesner** [0x90d/videoduplicatefinder#475]
## Environment
 - OS: Ubuntu 22.04

## Question
I installed everything [as described](https://github.com/0x90d/videoduplicatefinder?tab=readme-ov-file#linux-user):

```
sudo apt-get update
sudo apt-get install ffmpeg
```

then git cloned https://github.com/0x90d/videoduplicatefinder.git and `cd`d into repo. But how exactly do I start the application?

`$ ./VDF.GUI` gives me `bash: ./VDF.GUI: Ist ein Verzeichnis` (VFG.GUI is a directory)

**Comment by kattjevfel** [comment]
The instructions assumes you to download the pre-compiled version from the releases: https://github.com/0x90d/videoduplicatefinder/releases/tag/3.0.x

You'll want App-linux-x64.tar.gz from there.

**Comment by JohannesWiesner** [comment]
Aaah, got it thanks!
