### ISSUE TITLE
[Help]: Expression Builder

### ISSUE THREAD

**Issue by V-i-K-M** [0x90d/videoduplicatefinder#476]
## Environment
 - OS: [e.g. Windows / Linux / MacOS ]
Windows 11

## Question
Hello,
i want to use the Expression Builder to Select the Duplicates with the worst Quality.

How can i select the worst quality with this Expression: item.IsBestFrameSize or item.IsBestFps
Because if i use it like this it selects of course the Best Frame Size or BestFps wich i want to keep.

**Comment by Maltragor** [comment]
You can negate expressions by putting a `!` in front of it.
For example `!item.IsBestFps` will selects all files except those with the best fps.
It should be noted that "not the best" does not mean "the worst". (If one of three files is the best in something, then the other two are "not the best". But you won't find out which one is the worst).

It is possible to combine expressions or group them by using `()` but be aware of the Boolean algebra, e.g. De Morgan's laws.
`!expression1 || !expression2`  = `!(expression1 && expression2)`.
The order of operations for Boolean algebra, from highest to lowest priority is NOT (`!`), then AND (`&&`), then OR (`||`).
So `expression1 || expression2 && expression3` implicitly means  `expression1 || (expression2 && expression3)` like `x+y*z = x+(y*z) `
