### ISSUE TITLE
Scan times have increased significantly, being 4-5 times slower than before.[Help]: 

### ISSUE THREAD

**Issue by xiaodong594** [0x90d/videoduplicatefinder#477]
## Environment
 windows 11

## Question
I am using version 3.0, and it only took about 30 minutes to scan 2T of content. I don’t know what went wrong. Maybe it’s due to automatic Windows updates, I’m not sure. It now takes 2 hours and 30 minutes to scan 1T of content. The scanning time has increased significantly and is 4-5 times slower than before. I downloaded the latest software version and updated the latest ffmepg and ffprobe files. I can scan normally, but it is very slow and the situation has not improved.

## Snapshots
Optionally, include snapshots to help clarify the question.

**Comment by 0x90d** [comment]
Did you updated VDF and THEN it takes longer to scan? Or does it suddenly takes longer to scan with the SAME vdf version? Note that scan time can easily get changed due to background activity (software, HDD).
