### ISSUE TITLE
[Enhancement]: Add the ability to automatically move or copy the duplicates into their own subfolder for manual / later checking

### ISSUE THREAD

**Issue by Kazer67** [0x90d/videoduplicatefinder#478]
## Environment
 - OS: Linux (Pop!_OS)

## Describe desired feature
In the settings, adding the ability to automatically move the duplicates into their own folder after the scan for manual checking (either to a specified destination in the settings or by creating a folder using the duplicate's ID at the root of the scanned folder).

### What issue does it solve?
When there's a lot of videos with many duplicates, it would allow to put all of those duplicate in their own folder for manual checking to choose which one to keep (for example, the same video may just have a change in the watermark and it's not always visible just by the thumbnail).

Currently, I have to select the duplicates, move them manually with a right click > Selected Item > Move To Folder. This feature would automate that process.

**Comment by 0x90d** [comment]
I do not plan to automatically move / copy or delete any files because this can easily cause unwanted file system changes in which people would come to me and complain. The responsibility has to remain on the users themselves.
