### ISSUE TITLE
[Bug]: Huge group being wrongfully detected

### ISSUE THREAD

**Issue by tordenflesk** [0x90d/videoduplicatefinder#479]
## Environment
 - OS: Windows
 - ffmpeg 6.1.1

## Describe the bug
On every scan, ~25% of scanned files get detected as duplicates. Often lumped into 1 or 2 large groups.
There "might" sometimes be actual duplicates there... sometimes...

## Snapshots

![image](https://github.com/0x90d/videoduplicatefinder/assets/2136727/e1f76d8b-d436-4b11-8eef-f8a113af3fe3)

**Comment by 0x90d** [comment]
Increase thumbnail count, increase percentage. In general modify scan settings to get better results.
