### ISSUE TITLE
[Help]: Selecting duplicate help

### ISSUE THREAD

**Issue by SnapCrackerJack** [0x90d/videoduplicatefinder#480]
I typically delete duplicates by just choosing select lowest duration/quality.  But now i want to delete duplicates according to what drive they are in, how do I do this?  Also, the select newest or oldest button doesn't do anything, unless I'm doing it wrong.

**Comment by 0x90d** [comment]
> Also, the select newest or oldest button doesn't do anything, unless I'm doing it wrong.

Maybe but its hard to tell if you have added that less information to your issue.

> how do I do this?

Select - Custom - Expression Builder: `item.Path.StartsWith("C:\\")` change `C` to whatever drive letter you want. If you want to add more concrete path please use double `\\` instead of `\` like in my example
