### ISSUE TITLE
[Bug]: Cannot delete images with log "Failed to delete file [...] reason: SHFileOperation returned: 78...

### ISSUE THREAD

**Issue by spellcasterbr** [0x90d/videoduplicatefinder#482]
## Environment
 - OS: Windows 11

## Describe the bug
Hi everyone! 

First of all, I would like to thank all the developers for this excellent piece of software. It is really helpful!

My only problem is that I can't delete fotos through the app. When I select "Delete Selection" --> "Delete from disk" (or even "delete permanently"), it doesn't actually delete the files.

The problem remains even when I execute "VDF.GUI.exe" as an administrator.

The log shows the following message: 

`18:53:09 => Failed to delete file 'D:\Porta Treco\Imagens\201001-ferias camboriu\fotos pai\26012010895.jpg', reason: SHFileOperation returned: 78, Stacktrace    at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 936`

I'm currently using version 3.0.x (daily build for Windows x64).

Thanks everyone in advance.

**Comment by 0x90d** [comment]
`0x78` error code means `DE_ACCESSDENIEDSRC | 0x78 | Security settings denied access to the source.` So VDF can read the file but not write (delete). Check your security/access settings
