### ISSUE TITLE
[Bug]: Cannot find FFmpeg executable

### ISSUE THREAD

**Issue by 9563067** [0x90d/videoduplicatefinder#484]
## Environment
 - OS: [e.g. Windows / Linux / MacOS ]
win11
## Describe the bug
 - A clear and concise description of the bug.
 - What happen, and what did you expect to happen?
 - What are the steps to reproduce issue?

Search Directories have already been selected,When I click scan in scnner, an error appears as shown in the figure.

"Cannot find FFmpeg executable. The easiest solution is to download ffmpeg and place it in
VDF 'bin' folder. Otherwise please follow instructions on Github and restart VDF"

I followed the error prompts to operate again, download FFmpeg, the problem did not solve, so here for help
## Snapshots
Optionally, include snapshots showing the issue.
![1](https://github.com/0x90d/videoduplicatefinder/assets/62778100/ee915b7f-f943-4399-84e0-d18a1a442121)

**Comment by reddyshyam** [comment]
Hi @9563067 

Below are the instructions

FFmpeg & FFprobe:
Windows user:
Get latest package from https://ffmpeg.org/download.html I recommend the full (GPL) shared version. If you want to use native ffmpeg binding you must use the shared version.

Extract ffmpeg and ffprobe into the same directory of VDF.GUI.dll (basically where you have extracted the zip file). Or make sure it can be found in PATH system environment variable

In essence below 3 files should be in the same folder as the extracted content.
ffprobe.exe
ffplay.exe
ffmpeg.exe

Hope this helps.
