### ISSUE TITLE
[Help]: Failure to retrieve data

### ISSUE THREAD

**Issue by xvrqweuo** [0x90d/videoduplicatefinder#486]
## Environment

OS: Windows 10

## Describe the bug

Ran a scan of a folder and noticed that only images were being scanned for duplicates, not videos themselves.

Every video in the folder was met with a "Failure to retrieve media info". Any idea on why this might be happening?

## Snapshots
![image](https://github.com/0x90d/videoduplicatefinder/assets/161072808/b79c9a9b-48b1-4076-adf7-aa46e93a74d7)
![image](https://github.com/0x90d/videoduplicatefinder/assets/161072808/187b4549-e204-4f9f-93c0-ebed40a87c4d)

**Comment by 0x90d** [comment]
Run ffprobe with the command in the log file in a terminal and ffprobe will tell you what's the issue
