### ISSUE TITLE
[Bug]: Cannot delete any element from selection

### ISSUE THREAD

**Issue by Guarmanda** [0x90d/videoduplicatefinder#491]
## Environment
 - OS: Windows

## Describe the bug
 - When deleting selection, nothing is deleted.
 - Thousands of errors in logs: Failed to delete file 'X:\downloads2\received_231432095424260.mp4', reason: SHFileOperation returned: 20, Stacktrace    at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 936

Since we cannot export selection, the software is then totally useless

workaround: exit application and save result, make a python script to scan results, delete all checked files

## Snapshots
Last version (january 14 2023) 3.X

**Comment by 0x90d** [comment]
0x20 means "ERROR_SHARING_VIOLATION The process cannot access the file because it is being used by another process." Try and disable thumbnail generation
