### ISSUE TITLE
[Bug]: The "custom selection" is WRONG

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#496]
## Environment
 - OS: Windows 10

## Describe the bug
See video

## Snapshots

https://github.com/0x90d/videoduplicatefinder/assets/94469116/a94e6bc6-5c72-46a7-b32e-e8d89da69503

**Comment by 0x90d** [comment]
It works fine. If its a part in the middle of the path you must surround it with stars: `*NEWFOLDER*`
