### ISSUE TITLE
[Bug] [WIN]:  FFMPEG not detected neither on PATH env.ariable or locally pasted ffmpeg exes. 

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#498]
## Environment
 - OS: Windows 10

## Describe the bug
FFMPEG not detected neither on PATH enviroment variable or locally pasted ffmpeg complete bin folder (as entire ".\bin" folder and files directly on the root of the program, tried both)

It seems the program fails to see windows enviroment variables.

**Comment by 0x90d** [comment]
Do you use HW acceleration in VDF? If so it needs to be a specific ffmpeg version.

**Comment by Guarmanda** [comment]
Yep ffmpeg 7 isn't working with vdfgui

**Comment by Louis24** [comment]
> Do you use HW acceleration in VDF? If so it needs to be a specific ffmpeg version.

the key is find the nearly version to the date of yours :p

**Comment by Wado729** [comment]
> > Do you use HW acceleration in VDF? If so it needs to be a specific ffmpeg version.
> 
> the key is find the nearly version to the date of yours :p

Thank you!  This comment helped me.  If you are using the August 8th version, you have to use the FFMPEG version ffmpeg-n7.0.1-221-g0ab20b5788-win64-gpl-shared-7.0
