### ISSUE TITLE
VCRuntime140.dll is missing

### ISSUE THREAD

**Issue by rd1** [0x90d/videoduplicatefinder#50]
Hello There,

i'm having a problem loading VFD, it seems this needs a VC++ update i don't have installed on my freshly installed Windows 10 x64.

Here is a screenshot of the error i get when launching the exe:
![Annotation 2019-08-13 022023](https://user-images.githubusercontent.com/1567489/62919601-2f0f5980-bd71-11e9-81ea-5e87b4e09b57.png)

I found this possible update : https://www.microsoft.com/en-us/download/details.aspx?id=52685

We have to choose between the 32bit (x86) or the 64bit (x64) or just install both if you have a 64bit (x64) based system. 

HTH

**Comment by Revan654** [comment]
> 
> 
> Hello There,
> 
> i'm having a problem loading VFD, it seems this needs a VC++ update i don't have installed on my freshly installed Windows 10 x64.
> 
> Here is a screenshot of the error i get when launching the exe:
> ![Annotation 2019-08-13 022023](https://user-images.githubusercontent.com/1567489/62919601-2f0f5980-bd71-11e9-81ea-5e87b4e09b57.png)
> 
> I found this possible update : https://www.microsoft.com/en-us/download/details.aspx?id=52685
> 
> We have to choose between the 32bit (x86) or the 64bit (x64) or just install both if you have a 64bit (x64) based system.

It's because your system is looking for  VCruntime140.dll. Windows 10 only comes installed with 4.7 Framework. Where this program uses .netCore 3 and Core uses VCruntime140_cor3.dll.

Just need to install .Netcore 3.0 Runtime : [https://dotnet.microsoft.com/download/dotnet-core/3.0](url)
