### ISSUE TITLE
[Help]: Engaging CUDA cores on Linux

### ISSUE THREAD

**Issue by EldrinSMP** [0x90d/videoduplicatefinder#501]
## Environment
 - OS: Arch Linux

## Question
I am attempting to run VDF on Arch Linux. Drivers and CUDA toolkit are correctly installed but when running a scan my database I am seeing zero engagement of the NVIDIA GPU. 

## Snapshots
NVIDIA SMI, scan in progress but no usage of the NVIDIA Core. 
[![NVIDIA-SMI.png](https://i.postimg.cc/sxQZdmrh/NVIDIA-SMI.png)](https://postimg.cc/Zvmq6r0b)

Settings for VDF (I know the percentages / thumbnails are bad, but they work for my database)
[![Screenshot-20240423-130028.png](https://i.postimg.cc/rsVtn4VB/Screenshot-20240423-130028.png)](https://postimg.cc/qhFRgzCw)

**Comment by 0x90d** [comment]
Perhaps this would be a better question to ffmpeg developers. Have you tried running ffmpeg with HW acceleration on your linux machine and whether it uses the GPU?
