### ISSUE TITLE
[Help]: ERROR: Graybytes Too Dark.

### ISSUE THREAD

**Issue by darrenlimch** [0x90d/videoduplicatefinder#502]
## Environment
 - OS: Windows

## Question
I have a Synology NAS, mounted as local drive in my Windows. Then use the app to scan for duplicate video, but get this error.
May i know how to fix this?
Thanks in advanced.

## Snapshots
![image](https://github.com/0x90d/videoduplicatefinder/assets/40466880/220d5e48-dc70-4933-b1b9-f75d42091200)
![image](https://github.com/0x90d/videoduplicatefinder/assets/40466880/2486a5f2-f64e-4af6-8e67-e35a9c9862ba)

**Comment by 0x90d** [comment]
Gray bytes too dark means that it likely got a black frame. In this case it cannot be used for duplicate check, it would only produce false reports. I dont know if your videos have black frames in it. Try increasing the thumbnail amount.

About failing to retrieve graybytes you should enable extended logging then you get the ffmpeg output which is telling you in log why it has failed.

**Comment by darrenlimch** [comment]
Wow~ 
THanks alot, this tools really helps me ALOT. Im accidentally created way too many duplicate when backup my phone to NAS
THanks again yea for the help
