### ISSUE TITLE
[Bug]: Custom Selection is not working well

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#503]
BUG was already posted here and closed: 
https://github.com/0x90d/videoduplicatefinder/issues/496

## Environment
 - OS: Windows 10

https://github.com/0x90d/videoduplicatefinder/assets/94469116/cd51b816-300c-4374-a706-0d8c027150ef

If the video seems confusing: Look at how I surround the word "Downloads" (which is part of the path that I left visible in the blur) in * but still, nothing gets selected.

PS. yes, its porn.

**Comment by 0x90d** [comment]
I made a commit, please try latest version once its built.
