### ISSUE TITLE
[Help]: blank window, no text displayed

### ISSUE THREAD

**Issue by maenpaa24** [0x90d/videoduplicatefinder#505]
## Environment
Arch linux with gnome latest kernel and gnome version.

## Question
No text is displayed when the app is opened. Tried both the binary from the release section at github and the package from the arch linux AUR repository. I have also tried to change the resolution or from X to wayland. Nothing worked. I guess the arch installation lacks a font but I do not know which one.

## Snapshots
![Screenshot from 2024-05-06 21-18-51](https://github.com/0x90d/videoduplicatefinder/assets/19935414/e463a783-2267-4b88-8687-4a6c13f570a6)

**Comment by 0x90d** [comment]
Try this: https://github.com/AvaloniaUI/Avalonia/issues/4427#issuecomment-669173654
