### ISSUE TITLE
[Bug]: Scan Failed 

### ISSUE THREAD

**Issue by Topspap** [0x90d/videoduplicatefinder#506]
## Environment
 - OS: Windows 10
 - VDF: App-win-x64 3.0.X   but same error in previous version

## Describe the bug
When performing scan sometimes VDF Crash and Close, the next time i open it is shows the "screenshot below"
What does this failed message mean and how to solve it? 

## Snapshots
![error](https://github.com/0x90d/videoduplicatefinder/assets/30016184/55e3512e-a78c-4153-8873-a487131f478e)

**Comment by 0x90d** [comment]
> What does this failed message mean and how to solve it?

When VDF finishes scan it creates a backup of the scan results. Next time you open VDF it tries to load this backup. In your case loading the backup has failed since its corrupted. There is no action required, next time you successfully scan it's gone.

**Comment by Topspap** [comment]
so there is no description of the crash reason !!

**Comment by 0x90d** [comment]
There is, in the event viewer of windows. But you only asked about the message in your screenshot.

**Comment by Topspap** [comment]
yeah cause I thought the message is the crash reason.
Can you explain further, where to look in Event Viewer ? 
Thanks...

**Comment by 0x90d** [comment]
Event viewer -> Custom views -> Administrative Events. Then in the event list look for "Error" type of events that matches the time of the crash. The "Source" should be ".NET Runtime".
