### ISSUE TITLE
[Help]: Please include the updated "bin" folder with version 3.0.x

### ISSUE THREAD

**Issue by 03302024** [0x90d/videoduplicatefinder#507]
## Environment
 - OS: Windows 11

## Question
Version 2.0.8 comes with many files in the "bin" folder. Version 3.0.x does not come with those extra files. I got version 3.0.x working by copying the "bin" folder over from version 2.0.8. However, the files in "bin" folder seem to be too old as they are from 2019. 

Can you please include the updated "bin" folder with version 3.0.x?

**Comment by 0x90d** [comment]
https://github.com/0x90d/videoduplicatefinder?tab=readme-ov-file#windows-user
