### ISSUE TITLE
[Bug]: Crashed unexpectedly and lost one day of work since there was no autosave of selected files

### ISSUE THREAD

**Issue by gambuzino-wonder** [0x90d/videoduplicatefinder#508]
## Environment
 - OS: Windows

## Describe the bug
 - A clear and concise description of the bug.
 Lost all my selected files and 1 day of work due to this
 - What happen, and what did you expect to happen?
 Was expecting that the program didn't crash, close by itself and lost all my work
 - What are the steps to reproduce issue?
 Made a scan that almost one 1hour to all the videos.
 Then choose mantain the quality version. It was selecting many that should no be deleted. So I was reviewing all the 3000 groups to uncheck the ones to preserve. When I was almost reaching the end to delete the program crash, closed the window and lost all my work of selecting precisely what to delete. One day of my life that can't be recovered due to the lack of a auto-save function.
 
## Snapshots
![image](https://github.com/0x90d/videoduplicatefinder/assets/154762449/1ae1c3ab-cb8c-4b7d-9afb-91793e67c0a6)

**Comment by 0x90d** [comment]
Provide a stacktace from windows event viewer

**Comment by Topspap** [comment]
• Yes it would be nice to save the ticked files and save then come back and continue.
• Regarding the "choose mantain the quality version. It was selecting many that should no be deleted. So I was reviewing all the 3000":
yes, I noticed that the app consider some still photos and gif as similar when the photo is the same as the  first frame of gif, and even mark the gif to be deleted as it is larger in size. 
a solution could be to not compare gif to still image
