### ISSUE TITLE
[Bug]: ffmpeg 7.0.1 (stable shared build) does not work with native ffmpeg binding - version detection problem

### ISSUE THREAD

**Issue by JamesPous** [0x90d/videoduplicatefinder#511]
## Environment
 - OS: [Windows 10 64bit latest updates ]

## Describe the bug
- I have installed your program in a directory
- I copied the ffmpeg 7.0.1 shared library to the bin folder in videoduplicatefinder folder
- Start videoduplicatefinder and used the setting native ffmpeg binding in settings menu
- ffmpeg 7.0.1 does not get detected an program does not start the search job
- You can download ffmpeg from your program, but the website is missing and use the ffmpeg 6 build

ffmpeg 7.0 shared library build works fine! No problems. Only version 7.0.1 does not get detected.

**Comment by Guarmanda** [comment]
Same, but even 7.0 wouldn't work: I have files in path, in app folder, in a bin subfolder, nothing works

**Comment by JamesPous** [comment]
In the sourcecode I can see, that VDF 3.x use a ffmpeg.Autogen library, which has the ffmpeg 6.x version.
I am not a experienced developer, but I could be that VDF need an update of the DLL to handle ffmpeg 7.x.
Here is the library sourcecode.

https://github.com/Ruslan-B/FFmpeg.AutoGen

**Comment by 0x90d** [comment]
> ould be that VDF need an update of the DLL to handle ffmpeg 7.x.

Exactly. Native ffmpeg binding only works with supported ffmpeg versions.

**Comment by 0x90d** [comment]
Fixed in latest commit
