### ISSUE TITLE
[Enhancement]: don't kill symlinked files by default

### ISSUE THREAD

**Issue by dankamongmen** [0x90d/videoduplicatefinder#512]
## Environment
Linux

## Describe desired feature
I had about 70T of movies in a single directory, along with a forest of symlinks breaking them down into directories for directors and actors. I ran VDF over the weekend, and came back to 97% of my files having been deleted, leaving only a shadow world of invalid symlinks pointing into a void. This made me very sad.

In the event where two file hashes match, it makes no sense that one could be smaller than the other and yet truly be a duplicate. Such files should probably never be destroyed, or the ability to remove them ought be hidden behind some option. Certainly this default behavior is undesirable.

### What issue does it solve?
Heartbreak.

**Comment by 0x90d** [comment]
VDF NEVER deletes your files on its own. People requested this but for exactly this reason I've never added it. If your files have been deleted then either by you or by something else.

**Comment by dankamongmen** [comment]
I'm not angry at you, fellow open source developer. Just trying to improve things. Perhaps I am indeed confused.

Yes, I of course had to click "remove listed files". I'm not suggesting that it removed files entirely without my input.

I'm saying that this was literally thousands of files. Many of the ones removed were indeed lower-resolution duplicates, and needed to be removed. But the ones which were symlinked were not, and ought not have been on a list created with default options.

**Comment by 0x90d** [comment]
You are responsible for validating the results. If you don't do this and hit delete and then loosing files you don't want to loose than this is your fault. I don't see what I can do here for you or what exactly you're trying to suggest with this issue.

**Comment by dankamongmen** [comment]
it is not feasible to verify a list of thousands of videos. at that point, i would do things by hand rather than running your application.

i'm well aware of the option. and the default is stupid. there is no time i want to remove the target of the link and keep the now enshittified link when i'm running a program intended to remove lower-quality copies of videos. but i will not argue with you. have a nice day.

**Comment by 0x90d** [comment]
> it is not feasible to verify a list of thousands of videos

If there are many false reports then you need to adjust your settings. There are plenty of ways to do that. More thumbnails, higher percentage. Exclude white/black frames. Exclude symbol links and so on.
