### ISSUE TITLE
[Bug]: very high ram when using native ffmpeg binding

### ISSUE THREAD

**Issue by rezad1393** [0x90d/videoduplicatefinder#513]
## Environment
linux

## Describe the bug
selected the native ffmpeg in options
run the scan on a video directory
get very high ram usage, so much that it eats all the ram and hangs system until OS terminates it.

**Comment by 0x90d** [comment]
Then you got too many duplicates. Uncheck preview thumbnail generation. Lower the amount of thumbnails and increase the percentage.

**Comment by rezad1393** [comment]
I thought that was the issue but my duplicates are not many and when I use the non-native one that ram issue doesnt happen.

**Comment by rezad1393** [comment]
any folder that has enough videos this happens,
I see some ffmpeg errors on video about error 69 that I dont see on non native.

**Comment by rezad1393** [comment]
I removed the config file and readded the native option and it seems to have fixed it.
I have no idea what cause that as I have selected the same old options again.
