### ISSUE TITLE
[Enhancement]: .webp & .jpg support

### ISSUE THREAD

**Issue by MrTheenD** [0x90d/videoduplicatefinder#514]
## Environment
 - OS: Windows 11

## Describe desired feature
Ability to scan .webp & .jpg files using VDF to find duplicates.

### What issue does it solve?
Includes ability to scan more files with added support to mentioned file types.

### Snapshots
![Screenshot 2024-06-13 103539](https://github.com/0x90d/videoduplicatefinder/assets/44969286/6af236a7-9454-435d-a837-b2d68270f36e)

**Comment by 0x90d** [comment]
JPG is already supported https://github.com/0x90d/videoduplicatefinder/blob/1d93ac090f842fb49cd36ed741729aad58e81b0a/VDF.Core/Utils/FileUtils.cs#L23

webp isn't supported by .NET runtime and not by ImageSharp (at least the version VDF uses). So I cannot add support. Feel free to open issues on .NET runtime and ImageSharp repos
