### ISSUE TITLE
[Help]:  support for vulkan and opencl for HWaccel in ffmpeg

### ISSUE THREAD

**Issue by rezad1393** [0x90d/videoduplicatefinder#515]
## Environment
linux

## Question
is there a way to enable vulkan or opencl in HWAccell in ffmpeg? 
in the https://trac.ffmpeg.org/wiki/HWAccelIntro#PlatformAPIAvailability  those two are fully supported (as donated with Y)  linux and windows for all 3 gpu companies.

**Comment by 0x90d** [comment]
Should be possible: https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/e129a3128b570e26f4c934cecbb9c00bab3c5dc4/FFmpeg.AutoGen/generated/Enums.g.cs#L978-L993

**Comment by rezad1393** [comment]
another bug is that when I restart the app this mode (none,vulkan,....) are not shown in the option menu. the option menu is empty.

**Comment by rezad1393** [comment]
also I get error of not finding ffmpeg.
