### ISSUE TITLE
[Bug]: Update ImageSharp to support webp

### ISSUE THREAD

**Issue by kattjevfel** [0x90d/videoduplicatefinder#516]
## Environment
 - OS: Linux

## Describe the bug
ImageSharp 2+ supports webp but cd0f2959f218f57fed82f57a0d57c467440c501c reverted it to 1.0.4.

I made a contribution a long time ago adding support for webp but around the same time ImageSharp was downgraded so it no longer works and all webps are imported as black squares. About since then (just under 2 years ago now) I've reverted this commit and everything still works perfectly, making me wonder why this was ever reverted in the first place.

So, given that VDF works perfectly with newer versions of ImageSharp and is even improved by it, can it please be updated?

**Comment by 0x90d** [comment]
> given that VDF works perfectly with newer versions of ImageSharp

ImageSharp 2.1.8 and latest 3.1.4 for example the following APIs (which VDF uses) no longer exist:

TryGetSinglePixelSpan
GetPixelRowSpan

This is why it stays on 1.0.4.

**Comment by kattjevfel** [comment]
I actually just reverted your revert, and it has worked for 2 years now.

**Comment by 0x90d** [comment]
Feel free to make a PR

**Comment by kattjevfel** [comment]
https://github.com/0x90d/videoduplicatefinder/pull/517
