### ISSUE TITLE
[Help]: Cannot find shared ffmpeg libraries (Ubuntu 22.04)

### ISSUE THREAD

**Issue by gtTracy** [0x90d/videoduplicatefinder#519]
## Environment
 Linux - Ubuntu 22.04
 VDF 3.x

## Describe the bug
Cleared VDF folder of all files and downloaded latest daily build (from 6/18/24, I believe). 

FFMPEG is properly installed:

tracy@tracy-HP17:~$ which ffmpeg
/usr/bin/ffmpeg
tracy@tracy-HP17:~$ ffprobe file
ffprobe version 6.1-1build2~22.04 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)

However, starting VDF.GUI, then attempting to Scan files with setting for "Use native Ffmpeg binding" fails, with message: Cannot find shared FFmpeg libraries. Either uncheck 'Use native ffmpeg binding' in settings or please follow instructions on Github and restart VDF

The location of ffmpeg is in the path:

PATH=/home/tracy/.local/bin:/home/tracy/.local/bin:/home/tracy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/tracy/.dotnet/tools

I'm not sure what else to check or change...

**Comment by 0x90d** [comment]
Use ffmpeg 7.x

**Comment by gtTracy** [comment]
Might be worth a quick update to the Readme to indicate a minimum version of FFMPEG. The Linux section just gives instructions to install from the distro - which in the case of Ubuntu 22.04 gives FFMPEG v 6.x.

I'll try upgrading to a later version and see if that helps.

**Comment by gtTracy** [comment]
So far, I have been unable to install FFMPEG 7 - there are no install targets for any current version of Ubuntu (since FFMPEG was released about the same time as the most recent version of Ubuntu), and trying to compile the latest FFMPEG gives me dependency errors (I'm currently looking for ways to resolve those - I may end up having to upgrade to 24.04 to be able to do that, but that process is a bit more involved than simply installing or compiling a newer version of FFMPEG). So, for the moment, I am stymied in so far as using the native bindings for FFMPEG - and the other way is painfully slow....

Any other ideas while I'm poking at this?

**Comment by 0x90d** [comment]
Wait until there are ffmpeg 7 builds for your linux distribution. Or download the source and downgrade ffmpeg binding nuget package and then build and use that.
