### ISSUE TITLE
Set the interval between Thumbnails

### ISSUE THREAD

**Issue by yami-no-tusbas** [0x90d/videoduplicatefinder#52]
**Environment**
 - OS: Any

**Describe the solution you'd like**
Some times, the duplicate finder seems to fail because all the image it get, are from the same "intro" Like for some animes, it detecte all episodes as duplicate, just because they have the same 1 minute 30 seconds introduction.

**Solution**

A way to edit the "interval" between thumbnail capture manualy.

**Comment by rd1** [comment]
same here.

Win10 x64

**Comment by emdx71** [comment]
I may have found a way around this. While organizing i was renaming files and it looks like when the file that just shows the intro and has a time stamp of 00:00:00 gets renamed, for some reason ffmpeg will then process the file and it no longer shows up as just the intro. YMMV but it just renaming helped me find 35 files the scanner missed the first time. something as simple as a . or a space should be enough to do it. . It might also fix the gray artifact screengrab as well. no idea why this works though

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2

**Comment by 0x90d** [comment]
Discussion moved here #85
