### ISSUE TITLE
[Help]: Is there a way to change all the paths in ScannedFiles.db

### ISSUE THREAD

**Issue by ps245** [0x90d/videoduplicatefinder#521]
## Environment
 - OS: Linux

## Question
If I did a scan on one PC and the mount  point was in one location, is there an easy way to update the path in the database (maybe even externally) to a new location?

for example if i scanned as `/media/alice/disk` but then I wanted to use the same scanned files databse on a different computer with a different username maybe `/media/bob/disk`. All the contents under ../disk are the same. It should be easy to change alice to bob in the database.

**Comment by 0x90d** [comment]
There is no way to edit all path at once. You can either edit them one by one by clicking on `Database -> Edit...` or perhaps using a hex editor on `ScannedFiles.db`. If you're familiar with C# you could also download the source and add some lines that changes all paths for you.
