### ISSUE TITLE
[Bug]: Keeps crashing

### ISSUE THREAD

**Issue by samt108** [0x90d/videoduplicatefinder#522]
## Environment
 - OS: Windows

## Describe the bug
 - A clear and concise description of the bug: VDF crashes while searching for duplicates. When I re-open the project, it opens with an aditional popup containing the error message below.
 - What are the steps to reproduce issue? Searching some folders on my computer. I'm not sure which folder or file triggers it because it just crashes.

Side note: You should really make the error text selectable so I can copy paste it instead of screenshotting.

## Snapshots
![image](https://github.com/0x90d/videoduplicatefinder/assets/31720841/234447a4-949c-473d-bd40-46f4c12483af)

**Comment by 0x90d** [comment]
I need the stacktrace (crash details) from the windows event viewer.

**Comment by samt108** [comment]
How can I get that?

**Comment by 0x90d** [comment]
Event viewer -> Custom views -> Administrative Events. Then in the event list look for "Error" type of events that matches the time of the crash. The "Source" should be ".NET Runtime".

**Comment by 0x90d** [comment]
One of your files has an invalid file name. Rename the file and it no longer crashes
