### ISSUE TITLE
[Bug]: Big group of false matches [NSFW images linked]

### ISSUE THREAD

**Issue by samt108** [0x90d/videoduplicatefinder#524]
## Environment
 - OS: Windows

## Describe the bug
When I run the program on a large group of files, there's always inevitably a big group of false matches.

Overall the program works great, thank you so much for making and maintaining it!

## Snapshots
For example (nsfw): https://gyazo.com/8ebe29a502ebc9e69921a512289f031e

**Comment by 0x90d** [comment]
You can mark this group as "not a match" when you right click on it. To avoid false detections you must tweak your scan settings. Higher percentage, more thumbnails etc.
