### ISSUE TITLE
[Bug]: Settings menu - Hardware acceleration will not get saved (e.g. cuda)

### ISSUE THREAD

**Issue by JamesPous** [0x90d/videoduplicatefinder#527]
## Environment
 - OS: Windows 10 64bit - latest updates

## Describe the bug
I started Videoduplicatefinder (latest daily build) and used the nativ ffmpeg binding with version 7.0.1 (stable version).
If I choose a hardware acceleration e.g. cuda (nvidia graphic card installed - latest driver),
Videoduplicatefinder will not save this setting! I used the save setting button and tested it also with admin rights.
Videoduplicatefinder will lost this setting, if I close the program and will start it again.
CUDA Acceleration works without errors, if I will choose it again.

## Snapshots
Here is a screenshot of my used settings:
![vdf3-beta](https://github.com/user-attachments/assets/c5046f93-1848-43aa-a43f-99ab446d99a3)

**Comment by Wrestor** [comment]
As far as I know, this is a cosmetic bug, "Settings.json" reports your selected `HardwareAccelerationMode`. I use a mac and therefore use videotoolbox AKA "7" as reported in it.

**Comment by JamesPous** [comment]
You are right. In the settings.json is it saved. 6 stands for 'cuda'. I see a small GPU usage of 1-10 percent during a VDF scan. So cuda is used for comparison.
