### ISSUE TITLE
[Enhancement]: Update to ImageSharp 3.1.5 to patch Out-of-bounds Write vulnerability

### ISSUE THREAD

**Issue by INeedTogepi** [0x90d/videoduplicatefinder#528]
## Environment
 - OS: Linux

## Describe desired feature
Someone should update this repo to use ImageSharp 3.1.5.

### What issue does it solve?
It will include the patch for an Out-of-bounds Write vulnerability that is currently part of ImageSharp 3.1.4. See more info here: https://github.com/advisories/GHSA-63p8-c4ww-9cg7

**Comment by 0x90d** [comment]
Done
