### ISSUE TITLE
[Help]: Can't find duplicate in same folder

### ISSUE THREAD

**Issue by vdb1975** [0x90d/videoduplicatefinder#532]
## Environment
 - OS: [e.g. Windows / Linux / MacOS ]
Windows

## Question
A clear and concise detailed question.
I've had 2 same video in a folder and VDF couldn't find them. To simplify, I put them in the same folder alone and tried different option but it never came back as duplicate even with 8 thumnails gerated, 80% difference and 20% on duration.
I've checked manually and duration was the same, just the codec rate and so the size

## Snapshots
Optionally, include snapshots to help clarify the question.

**Comment by 0x90d** [comment]
Please provide example video files so I can reproduce it
