### ISSUE TITLE
[Bug]: Cannot find shared FFmpeg libraries. Would you like to open the download page?

### ISSUE THREAD

**Issue by Louis24** [0x90d/videoduplicatefinder#533]
## Environment
 - OS: - Win11

## Describe the bug
When you report a crash provide the stacktrace. For windows users: Open the event viewer of Windows and look for a crash with type ".NET Runtime". For linux or macos users: Run the app from terminal, when it crashes the stacktrace is written to terminal. A crash report without stacktrace might get closed without additional comment.

I have tried the every version

and put in the env path, folder, everytime it pops up this error!!

## Snapshots
Optionally, include snapshots showing the issue.

**Comment by 0x90d** [comment]
https://github.com/0x90d/videoduplicatefinder/issues/498
