### ISSUE TITLE
[Enhancement]: Save thumbnails

### ISSUE THREAD

**Issue by tommyhome** [0x90d/videoduplicatefinder#537]
## Describe desired feature
I have an insane amount of files with lots of duplicates/potential duplicates, and would like an option for the preview thumbnails to be saved and reused since it takes a fair bit of time to create them when finding duplicates. 
I understand it will take up space, thats why I want an option for it.

### What issue does it solve?
Makes the experience of the app faster by reusing thumbnails rather than generating them each time over and over.
As it is right now I have to wait up to an hour each time for all the thumbnails to be created after the scan is complete.
With a insane amout of files you have to scan part of your collection at a time and find duplicates and repeat the process adding more of the files over and over, which makes the process even slower.

**Comment by 0x90d** [comment]
After scan you can export results including thumbnails at the top right and later import them.

**Comment by tommyhome** [comment]
the application tends to stop responding and crash while trying to save when having a huge result set, and it takes 10GB+ of ram to have it in memory instead of just saving them. 

And trying to remove anything from such a huge result set tends to crash the application. If it would have saved them, then it wouldn't have to have it all in memory, which would probably will make the the application almost as fast with a huge result set as a small one.

an hour was kind of short, my largest collection needs hours and hours to generate those preview images.

so, right now I'm just using this app for smaller stuff.

**Comment by 0x90d** [comment]
It can take much memory if you have a large list as it has to generate a thumbnail for each entry. In such case either perform a scan with generating thumbnails unchecked or split up the search directories into smaller chunks until your list becomes small enough.

There is not much VDF can do about this.
