### ISSUE TITLE
[Help]: Expression Builder Usage?

### ISSUE THREAD

**Issue by TurnOffNOD** [0x90d/videoduplicatefinder#538]
## Environment
 - OS: Windows
 - Version: latest daily build

## Question
When I am using Expression Builder, I read the integrated help message:
![2024-10-03_183111](https://github.com/user-attachments/assets/2b3f9128-1092-4950-b890-2d04184daed4)

As we can see, it lists available variable items.

However, there is still something unclear, for example, among the listed items, there is `item.Path (String)` and nothing further, but at the examples below, there is a line showing `Example: item.Path.Contains("imageFolder")`, a new item `item.Path.Contains` shows up.

Is there a more detail and clear help message available?

**Comment by 0x90d** [comment]
It uses C# syntax. `Path` is a `string` and `Contains` is a C# method which is accessible on strings. See https://learn.microsoft.com/en-us/dotnet/api/system.string.contains?view=net-8.0 and https://learn.microsoft.com/en-us/dotnet/api/system.string?view=net-8.0#methods for a full list.

**Comment by TurnOffNOD** [comment]
> It uses C# syntax. `Path` is a `string` and `Contains` is a C# method which is accessible on strings. See https://learn.microsoft.com/en-us/dotnet/api/system.string.contains?view=net-8.0 and https://learn.microsoft.com/en-us/dotnet/api/system.string?view=net-8.0#methods for a full list.

Oh, I see. And what is the difference between `item.Path` and `item.Folder`?

**Comment by 0x90d** [comment]
Path is the full path including the file name. Folder is the full path of the folder excluding the file name.

**Comment by TurnOffNOD** [comment]
> Path is the full path including the file name. Folder is the full path of the folder excluding the file name.

Thanks for replying.
