### ISSUE TITLE
Show resolution on image matches

### ISSUE THREAD

**Issue by sBrecht** [0x90d/videoduplicatefinder#54]
**Environment**
 - OS: Windows

**Describe the solution you'd like**
Would be great if the tool would show image resolution.  Often when deciding which I want to keep I am looking for the higher resolution image.  This would be handy for video too I assume though I haven't tried that functionality yet.  Otherwise excellent tool!

**Comment by enveeed** [comment]
Video already includes the resolution in the listing, only images are missing it. I highly support this suggestion. :)

**Comment by 0x90d** [comment]
The windows version already shows the resolution of images in latest nightly version.
