### ISSUE TITLE
[Enhancement]: Priotiize larger file sizes for best quality videos (instead the opposite)

### ISSUE THREAD

**Issue by bartelsmedia** [0x90d/videoduplicatefinder#548]
## Describe desired feature
VDF seem to prefer smaller file sizes which is contradictive when searchign for the best quality videos.

Currently, VDF prioritizes smaller file sizes (also with red text for larger files). Should be the other way round.

**Comment by rudolphos** [comment]
Large file size always does not mean higher quality these days..

For example **h264** / 1573 kbps / 12 MB video is about the same quality as **hevc** / 483 kbps / 3.9 MB with dimensions 576x1024px.

**Comment by 0x90d** [comment]
@rudolphos is right
