### ISSUE TITLE
videoduplicatefinder 2.0.7 & 2.0.4 does not start on windows

### ISSUE THREAD

**Issue by Peter-48** [0x90d/videoduplicatefinder#55]
**Environment**
Windows

**Describe the bug**
videoduplicatefinder 2.0.7 & 2.0.4 does not start.
Error message: "CurrentDomain.UnhandledException" ...
See screenshoot
![Crash](https://user-images.githubusercontent.com/56576549/66804143-f717c480-ef21-11e9-8ad4-8803ed19f8c1.jpg)

**Expected behavior**
No crash!

**Comment by 0x90d** [comment]
You're missing VC++ 2015 runtime: https://www.microsoft.com/download/details.aspx?id=52685
