### ISSUE TITLE
Opening files in duplicate groups

### ISSUE THREAD

**Issue by Sepulta** [0x90d/videoduplicatefinder#57]
**Environment**
 - OS: Any

**Describe the solution you'd like**
It would be useful to be able to right/double click items in duplicate groups to view them/their properties. Should not be too hard to implement.

**Comment by reddyshyam** [comment]
Double clicking thumbnails certainly play the files and beside thumbnails, one does see its resolution, size and encoding. Am I missing something?

**Comment by Sepulta** [comment]
Double-clicking thumbnails does not open the files on my Linux machine. And even though there is a set of information shown on the right, I would like to be able to more easily get more information about that file. For example: in some cases the full file path is not properly shown because the thumbnail is too small, resulting in a small height and a file path text that is cut off. Being able to right-click and 'open folder' and 'open file', among other features would be a convenient addition.

**Comment by Revan654** [comment]
> 
> 
> Double-clicking thumbnails does not open the files on my Linux machine. And even though there is a set of information shown on the right, I would like to be able to more easily get more information about that file. For example: in some cases the full file path is not properly shown because the thumbnail is too small, resulting in a small height and a file path text that is cut off. Being able to right-click and 'open folder' and 'open file', among other features would be a convenient addition.

Some of Can be the Results of WPF on Linux. WPF is designed for Windows first, Then ported over.

The double Click not sure where it's housed in Linux Code, If it's anything like Windows Code, It's not the most accurate way of obtaining the File Path, It should be done only on the UI with URI instead of the basic string format. This way you can use URI.Absolute Path. Then Attach it to DependencyProperty.

**Comment by 0x90d** [comment]
Right click to open in folder already exist in Windows GUI. Double clicking on the image plays the files. Linux version is missing these things. I completely agree these would be great additions but I'm not sure how to add these especially opening folder of the file. In Windows it enough to run Explorer.exe with folder path as argument. No idea how it works on Linux.

**Comment by vsolina2** [comment]
right click to open a folder can be implemented in linux via xdg-open
xdg-open - opens a file or URL in the user's preferred application

Synopsis

xdg-open { file | URL }

xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
