### ISSUE TITLE
TaskScheduler.UnobservedTaskException

### ISSUE THREAD

**Issue by Quantum00** [0x90d/videoduplicatefinder#58]
![vdf](https://user-images.githubusercontent.com/22214916/67240036-22c60d80-f440-11e9-949f-360ec717472d.png)

Hello, I am running latest build from appveyor (8897be81), .NET Core 3.0 release version and latest ffmpeg and I'm getting a whole lot of this errors during scan. The scan continues and finishes normally and after I dismiss a whole lot of these errors the program works as expected.

Can this be fixed?

**Comment by Revan654** [comment]
> 
> 
> ![vdf](https://user-images.githubusercontent.com/22214916/67240036-22c60d80-f440-11e9-949f-360ec717472d.png)
> 
> Hello, I am running latest build from appveyor ([8897be8](https://github.com/0x90d/videoduplicatefinder/commit/8897be8177e73a7a2a54c120fb2a936323080aa3)), .NET Core 3.0 release version and latest ffmpeg and I'm getting a whole lot of this errors during scan. The scan continues and finishes normally and after I dismiss a whole lot of these errors the program works as expected.
> 
> Can this be fixed?

This is the Results of some of the Changes Mainly add Using to some of the FileStreams, For Dev: It might be worth adding Try, Catch, Finally instead. Using Statements can premature close the streams if your not careful.
