### ISSUE TITLE
program makes error message CurrentDispatcher.UnhandledExeption

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#59]
**Environment**
 - OS: [e.g. Windows / Linux]
Windows 10 Enterprise LTSC. 
Video Duplicate Finder 2.0.7 downloaded latest build and compiled by my PC with downloaded source. Both had a same error.

**Describe the bug**

When I scan multiple external HDDs which contain thousand of movie files and duplicated files encoded different types. ( 4TB three, 8TB five )

About 40 minutes later after scan, this error message comes out.  
"CurrentDispatcher.UnhandledExeption"
Here is the screenshot  
Is this problem of my PC setting?

**Expected behavior**

I want this program can handle much more amount of  files.
![error](https://user-images.githubusercontent.com/43441443/70389275-81e7dd80-1a00-11ea-9393-d3e418127c81.png)
![error2](https://user-images.githubusercontent.com/43441443/70389284-9cba5200-1a00-11ea-96b0-2f3c8452a415.png)

**Comment by wowkkwow** [comment]
Many thanks! No error with the latest build

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
