### ISSUE TITLE
Request: select all lowest resolution + "never select" folder

### ISSUE THREAD

**Issue by voltaireodactyl** [0x90d/videoduplicatefinder#60]
Hey I'm just wondering if there's a way to get the program to select all duplicates of LOWEST size and/or resolution. The idea being to get rid of lower res copies of videos once an HD version is found. (EDIT: ignore this one -- my brain was interpreting the options badly, and I didn't realize a "preserve best quality" already basically exists).

One additional feature that would be a huge help for my workflow would be a function to select a folder (within the scanned folder) that should "never be selected". The idea being to have a "FINAL" folder to dump videos into -- and still be able to remove duplicates without touching that FINAL folder.

Thanks much for all the hard work thus far!

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
