### ISSUE TITLE
Some duplicates are simply grey frames or artifacts

### ISSUE THREAD

**Issue by saucefrog** [0x90d/videoduplicatefinder#61]
Not sure if this is a bug or simply some wrong behaviour when comparing different video files.

**Environment**
 - OS: Windows 7, 64-bit

**Describe the bug**
Video Duplicate Finder shows duplicate groups with greyish thumbnails instead of properly decoding them. The video files aren't even duplicates.

![vdf](https://user-images.githubusercontent.com/8697953/70641255-a4b30580-1c3d-11ea-95cd-c97c58600a2e.png)

**Expected behavior**
The video files play correctly on my system with VLC Player, Video Duplicate Finder should decode them properly too.

**Comment by 0x90d** [comment]
Try updating your ffmpeg version. Looks like the video files are corrupt and VLC automatically repairs them or skip the invalid frames.

**Comment by saucefrog** [comment]
I downloaded the latest stable version from the link on your main page. The installation instructions are a bit unclear, you wrote we should copy the files into VDF's main folder, but there's also a bin folder that already has FFmpeg and FFprobe files inside. I copied the new files into both folders, but VDF still doesn't decode the video files properly.

I also tested my video files, usually VLC asks if it should fix a faulty file before playing it, mine played immediately without error message though.

**Comment by wowkkwow** [comment]
I've same problem with latest table version.

**Comment by 0x90d** [comment]
@saucefrog Can you provide a sample video file? Usually VDF only takes what ffmpeg outputs. And gray images with a colored few pixels only usually indicates a broken frame which VLC skips or repairs in background without any notification for the user. A sample video would let me verify this.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
