### ISSUE TITLE
Windows Image False Positives

### ISSUE THREAD

**Issue by Test1049** [0x90d/videoduplicatefinder#62]
VideoDuplicateFinder [prebuilt](https://github.com/0x90d/videoduplicatefinder/releases): 2.0.7 and also built latest master on my PC.

Roughly 2% of images scanned by VDF are false positives - between 99 and 100% likeness. All said pictures are seen as 1 duplicate group.
I have confirmed that these pictures aren't visually alike to computers with Visipics.
Again, this only happens with images.

I've made sure that FFmpegs are up to [date](https://ffmpeg.zeranoe.com/builds/) and working fine (at least, outside of VDF).

**Comment by 0x90d** [comment]
Can you share two sample images where this happens?

**Comment by Test1049** [comment]
Here's the result of the scan (I've whited out the directories for privacy): https://imgur.com/a/lSHodWo
Here are the files that were scanned (SFW): https://mega.nz/#F!mMxUSApJ!XwH7xCiEuJ9_6EmIck5PpA
D drive is an HDD

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
