### ISSUE TITLE
Thumbnails not created

### ISSUE THREAD

**Issue by 2020pt** [0x90d/videoduplicatefinder#65]
**Environment**
 - OS: Linux Mint

**Describe the bug**
Run search
Results show up without thumbnails

13:42:15	Exception, file: /home/mint/Videos/test_dup.mkv, reason: The type initializer for 'Gdip' threw an exception., stacktrace    at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromDelegate_linux(StreamGetHeaderDelegate getHeader, StreamGetBytesDelegate getBytes, StreamPutBytesDelegate putBytes, StreamSeekDelegate doSeek, StreamCloseDelegate close, StreamSizeDelegate size, IntPtr& image)
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311

**Expected behavior**
1) Expected results to show up as they went along, instead they only seemed to show up in last minute or so of 20 min scan (I thought it hadn't worked)
2) No thumbnails created (although 'Thumbnails' subdirectory was created OK within program folder)

**Comment by 0x90d** [comment]
Do you have libgdiplus installed? https://github.com/0x90d/videoduplicatefinder#linux-user

**Comment by 2020pt** [comment]
I'm pretty sure I did - I was sure I followed all 3 of those commands. Unf did a rebuild for a new kernel so haven't reisntalled again yet

**Comment by ldillon** [comment]
Version: 2.0.7
Similar problem under Linux Mint (5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020)

VideoDuplicateFinderConsole runs but does not generate thumbnails. HTML shows all videos 100% the same.

VideoDuplicateFinderLinux Segmentation fault (core dumped)

libgdiplus is already the newest version (4.2-2)
ffmpeg is already the newest version (7:3.4.6-0ubuntu0.18.04.1).

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
