### ISSUE TITLE
FFProbe process exceeded execution timeout message in scanning a localized google drive

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#66]
**Environment**
 - OS: [e.g. Windows / Linux]
Windows 10 Enterprise LTSC.
Video Duplicate Finder 2.0.7 downloaded latest build 

**Describe the bug**
I am using [RaiDrive ](https://www.raidrive.com/)which can change the google drive with a local drive.
Because of network condition, the access time and the speed are not as fast as a real local drive.
So When I scan this RaiDrive, the scan process makes lower log messages.

12:51:06	OS: Microsoft Windows 10.0.17763
12:51:30	Building file list...
12:51:30	Found previously scanned files, importing...
12:51:30	Previously scanned files imported. 000000 files in 00:00:00.2501144
13:00:28	Finished building file list in 00:08:58.4588416
13:00:28	Start scan
13:00:58	FFProbe process exceeded execution timeout (00:00:15) and was aborted, File: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:00:58	FFprobe error: FFProbe process exceeded execution timeout (00:00:15) and was aborted, File: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:02:24	FFMpeg timeout. File: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:02:24	FFMpegException, file: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:04:19	FFMpeg timeout. File: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:04:19	FFMpegException, file: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:04:53	FFMpeg timeout. File: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:04:53	FFMpegException, file: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:05:19	FFProbe process exceeded execution timeout (00:00:15) and was aborted, File: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:05:19	FFprobe error: FFProbe process exceeded execution timeout (00:00:15) and was aborted, File: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:05:45	FFMpeg timeout. File: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:05:45	FFMpegException, file: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
.

**Expected behavior**
If these timeouts and abortions are caused by a timeout regulation, 

please make a room for the regulation time or add a time option for using a network drive.

Thanks for reading and your works.

**Comment by 0x90d** [comment]
Making the timeout customizable sounds like a good idea, there might be other situations were this is useful.

**Comment by james-cook** [comment]
I support this idea - I'm getting a few of these timeouts (admittedly on an ultrabook)

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
