### ISSUE TITLE
Request: Mark and Unmark All files in Same Folder

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#67]
Hi! Thanks for all your efforts and kindnesses.

I hope a new selection options in right click menu in the result row.

It is "Mark All Files in Same Folder" and "Unmark All Files in Same Folder".

In many case  downloaded package of images and movies are similar property, such as bitrate, file type, codec and resolution.

In many other duplicate file cleaners have same right click menu in the result row.
But not powerful as videoduplicatefinder.

**Comment by 0x90d** [comment]
What should happen if there are two duplicates and both are in the same folder? Mark both files for deletion?

That doesn't sound like a good idea or I am not understanding your request.

**Comment by wowkkwow** [comment]
Thanks for reading.
In many case of other duplicate cleaner, it checks all and makes or marks warning as a special color mark.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
