### ISSUE TITLE
Request: File matching and folder structure rebuilt based on database

### ISSUE THREAD

**Issue by nulledone** [0x90d/videoduplicatefinder#68]
First of all thank you for creating this wonderful open source application, it is extremely useful for me.

Here goes my request;

It may sound unnecessary since it is way too irrelevant feature for this application but I've needed when I almost lost my 7TB video archive (I recovered file structure thanks to the exported files csv and db matching them). I've no idea how could one implement it but it may come handy. 

**Feature is comparing a directory or file set to current database and renaming/moving them based on their match on the database.**

Possible options for the feature:
Recreate folder tree in %% directory.
Only move different named files. 
Only rename files. (if this feature ever got to implemention one should note to use UTF-8 since original files may contain non Latin characters such as "б щ ф". 

Unnecessary detail of my solution;
When I had data loss, almost all recovered files had random names (folder structures were inexistent) so I had no choice but rename and move them to appropriate folders. Given that I had around 14k videos it was almost impossible to do them all since I did not remember most of their names (hence youtube video ids were embedded in the name as well). But thankfully I've scanned them all sometime ago and most of them were recorded in the apps database. 

I've exported already existing db csv and did a rescan with recovered files to export csv from them as well. 2 csv files were not identical since their sorting was changed cause me another issue which I've solved by importing them to database and matching lines. After that a simple rename script did the job for me.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
