### ISSUE TITLE
Open file by double click

### ISSUE THREAD

**Issue by VanTuz5** [0x90d/videoduplicatefinder#69]
- OS: windows
It would be great if the compared file could be launched from the program by double-clicking
(I apologize for my English, not my native language)

**Comment by Revan654** [comment]
> 
> 
>     * OS: windows
>       It would be great if the compared file could be launched from the program by double-clicking
>       (I apologize for my English, not my native language)

That already Exists, Just click on the thumbnail.

**Comment by VanTuz5** [comment]
Stupid me... Thanks!
