### ISSUE TITLE
Add possibility to sort duplicates - linux

### ISSUE THREAD

**Issue by 0x90d** [0x90d/videoduplicatefinder#7]

**Comment by ndc168** [comment]
Can the sort go by folder structure, then % similar? 

By directly dumping the comparison onto screen is somewhat user-unfriendly. For instance, the result would jump around in random sequence but back to same folder. Though none of the dedup programs managed to do it correctly.

Thanks for the work though.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
