### ISSUE TITLE
Support for "long paths" (>260 character) files in Windows 

### ISSUE THREAD

**Issue by bobsage123** [0x90d/videoduplicatefinder#71]
**Environment**
Windows

**Describe the bug**
It seems files with long paths of over the limit of 260 characters in Windows, will not be checked for duplicates. The option for 260+ character paths is something that needs to be enabled manually in windows (see https://betanews.com/2016/05/29/long-paths-windows-10/)

**Expected behavior**
Long paths will be accepted

**Comment by Revan654** [comment]
> 
> 
> **Environment**
> Windows
> 
> **Describe the bug**
> It seems files with long paths of over the limit of 260 characters in Windows, will not be checked for duplicates. The option for 260+ character paths is something that needs to be enabled manually in windows (see https://betanews.com/2016/05/29/long-paths-windows-10/)
> 
> **Expected behavior**
> Long paths will be accepted

Anything Above FrameWork 4.6.2(This Includes 3.0, 3.1 and 5) Already Has Long Path Support By Default and Does Not need to Be Enabled Manually. That Link is Related Other Usages. The Only Exception To this Rule Is if Your Harddrive is Not NTFS.

It's More then Likely Long Path Issue Is Related to FFmpeg, Any Non-#C Code are Not Immune to the Char. Limit.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
