### ISSUE TITLE
show the files names that throwe errors (or even better output in a log)

### ISSUE THREAD

**Issue by rezad1393** [0x90d/videoduplicatefinder#72]
**Environment**
linux archlinux x64

**Describe the solution you'd like**
when scanning folders with lots of files (videos) there are some files that have errors like:
[mp3float @ 0x55726a020640] Header missing
[mpeg2video @ 0x55fd140e1980] ignoring pic cod ext after 0
[mpeg2video @ 0x5618bbc6e680] Invalid frame dimensions 0x0.
[h264 @ 0x56103865c280] SEI type 5 size 4584 truncated at 4571

how can I find the files responsible for this errors?
maybe a output files with path of files with errors (and the error of course)

**Comment by Revan654** [comment]
> 
> 
> **Environment**
> linux archlinux x64
> 
> **Describe the solution you'd like**
> when scanning folders with lots of files (videos) there are some files that have errors like:
> [mp3float @ 0x55726a020640] Header missing
> [mpeg2video @ 0x55fd140e1980] ignoring pic cod ext after 0
> [mpeg2video @ 0x5618bbc6e680] Invalid frame dimensions 0x0.
> [h264 @ 0x56103865c280] SEI type 5 size 4584 truncated at 4571
> 
> how can I find the files responsible for this errors?
> maybe a output files with path of files with errors (and the error of course)

That is the Error ffmpeg outputs, The Logging System should be Updated, Right now it Only grabs global Exceptions. 

ffmpeg has it own share of problems when it reads the video and the byte array. Even if ffmpeg outputs such errors, There could be nothing wrong with the video. Many are false positive.

 Using MediaInfo will give you a more accurate read on the file, ffprobe is not the greatest for reading metadata.

**Comment by rezad1393** [comment]
I understand that this is ffmpeg error output and maybe be false positive but still it would be useful to see which files are giving this errors.
btw can it have false negative too? as in the files has errors but ffmpeg dont show them?

this is not a priority but could be useful.

**Comment by 0x90d** [comment]
It should already print out the file where a critical exception occurs. On Linux when running through bash it may print out a lot of debug code from ffmpeg/ffprobe which may not necessarily cause an issue (this is what it looks like to be). In this case you should simply ignore this. But if you really want to know either run ffmpeg yourself on all your files or replace it with a custom built ffmpeg that prints out the processing file.

**Comment by Revan654** [comment]
> 
> 
> It should already print out the file where a critical exception occurs. On Linux when running through bash it may print out a lot of debug code from ffmpeg/ffprobe which may not necessarily cause an issue (this is what it looks like to be). In this case you should simply ignore this. But if you really want to know either run ffmpeg yourself on all your files or replace it with a custom built ffmpeg that prints out the processing file.

you do have ffmpeg log set to panic which doesn't do anything.

Directly from Doc:

`panic, 0: This is not currently used for anything. `

you want fatal.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
