### ISSUE TITLE
wrong duplicates

### ISSUE THREAD

**Issue by rezad1393** [0x90d/videoduplicatefinder#73]
**Environment**
archlinux

**Describe the bug**
when I scan my movies collections I get a lot of false duplicates.
this happens with one file having a signature(? I think that is the name uses for the id)  and other files having the same signature (incorrectly) but shown with zero length.

if I set the -p to 99 percent the number of these go down but they don't get eliminated.

**Comment by 0x90d** [comment]
How do the thumbnails looks like? Mostly one color? Broken?

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
