### ISSUE TITLE
How to download 2.0.1

### ISSUE THREAD

**Issue by ExodusHour** [0x90d/videoduplicatefinder#74]
How do I download 2.0.1 I don't see a build batch file in the source?

**Comment by 0x90d** [comment]
https://github.com/0x90d/videoduplicatefinder/releases/tag/2.0.7 under Assets you find the download links.

**Comment by ExodusHour** [comment]
That's for 2.07 I want 2.0.1

**Comment by Revan654** [comment]
> 
> 
> That's for 2.07 I want 2.0.1

It has to be built from the Source.
