### ISSUE TITLE
Add side pane with larger preview

### ISSUE THREAD

**Issue by dariox86** [0x90d/videoduplicatefinder#76]
Telling the difference between two similar images can be difficult because they are small in size. There is much wasted space on screen that could be otherwise used to show a quick preview of the selected image or video with a single click on the corresponding file. I am thinking about something like [this](https://pasteboard.co/J52kVG6.png).

**Comment by 0x90d** [comment]
I like this idea though I would probably make it a popup/tooltip instead.
