### ISSUE TITLE
Long Paths in Linux

### ISSUE THREAD

**Issue by vsolina2** [0x90d/videoduplicatefinder#78]
**Environment**
 - OS:  Linux

**Describe the bug**
Long Paths due to server addresses cause the names to disappear additional seems to be limited to height of preview
![Screenshot from 2020-05-05 12-39-32](https://user-images.githubusercontent.com/64821096/81031242-f69b4700-8ece-11ea-94ba-4d63e89a5502.png)
**Expected behavior**
The full name to appear where possible especially if I make the window bigger alternatively the columns could be widened manually like a file browser window

**Comment by 0x90d** [comment]
This may also depend on Avalonia (GUI backend). Their text wrapping logic still contains bugs.
