### ISSUE TITLE
select all duplicates in the same folder

### ISSUE THREAD

**Issue by vsolina2** [0x90d/videoduplicatefinder#79]
**Environment**
 - OS: / Linux / Any

**Describe the solution you'd like**
Right Click option select all duplicates in the same folder
Also Add option to select duplicates not in folder/subfolder

**Comment by 0x90d** [comment]
Same folder as …. ?! The current selected? Or only select duplicates when A and B are in the same folder of each other?

**Comment by vsolina2** [comment]
when the path is displayed right click on a folder in the path and the option acts on it and sub-folders

**Comment by vsolina2** [comment]
Additional deselect Duplicates in those folders/subfolders

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
