### ISSUE TITLE
Request: Please add an option to exclude hardlinked duplicates

### ISSUE THREAD

**Issue by Samhayne** [0x90d/videoduplicatefinder#82]
**Environment**
Any

**Describe the solution you'd like**
Would be great if you could - as an option - check if found duplicates are hardlinks pointing to the same data and exclude them from the result list if they are.

Your tool is of great help for people to save disk space. Though hardlinked dupes are USUALLY something you don't want to remove. And if you use them a lot the result list is totally littered with these and you have to take special care to not accidentally remove one.

Unfortunately I struggled finding a good solution to check whether 2 hardlinks share the same data.
Found this, though it relies on Windows' fsutils. Grrr...
https://stackoverflow.com/questions/59525264/how-to-determine-if-two-file-are-hard-linked-to-the-same-data

**Comment by Revan654** [comment]
> 
> 
> **Environment**
> Any
> 
> **Describe the solution you'd like**
> Would be great if you could - as an option - check if found duplicates are hardlinks pointing to the same data and exclude them from the result list if they are.
> 
> Your tool is of great help for people to save disk space. Though hardlinked dupes are USUALLY something you don't want to remove. And if you use them a lot the result list is totally littered with these and you have to take special care to not accidentally remove one.
> 
> Unfortunately I struggled finding a good solution to check whether 2 hardlinks share the same data.
> Found this, though it relies on Windows' fsutils. Grrr...
> https://stackoverflow.com/questions/59525264/how-to-determine-if-two-file-are-hard-linked-to-the-same-data

The option already exists inside of EnumOptions for the Directory class. However the dev does not use it nor any the extended options. However certain File attribute flags do not work on .netcore with Linux.

The program still needs allot of work.
