### ISSUE TITLE
Fragmentation Search Algo?

### ISSUE THREAD

**Issue by ndc168** [0x90d/videoduplicatefinder#83]
**Environment**
 - OS: [Any]

Sometimes videos can be padded (front, back, in the middle) and cause the % similarity to drop. Can the search traverse and find the first frame of similarity? this way, the thumbnail can "snap" to the last match, show the first thumbnail of mismatch or blank, then resume showing the first thumbnail of  match again?

Also, if it's possible to match by sound as the first pass. Sometimes the frames themselves are "static" i.e. talk shows.

Thanks.

**Comment by ndc168** [comment]
Any updates?

A good example is Video Comparer where it shows where a subset of similarity begins and ends.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
