### ISSUE TITLE
Limit CPU cores

### ISSUE THREAD

**Issue by ndc168** [0x90d/videoduplicatefinder#84]
**Environment**
 - OS: [Windows ]

When the program runs, it took all processing power such that other tasks started to experience lags. Is it possible to hard code and allow 1 thread free? That would help a lot. Thanks.

**Comment by 0x90d** [comment]
The current code let the system handle all the resources. So I don't have much control over the threads it takes. You can still pause, do whatever you need to do and then continue. Also you can use the taskmanager to lower the priority. I have no plans for a limit as this would requires major changes.
