### ISSUE TITLE
skip first "xx" seconds to avoid black screens and Intros.

### ISSUE THREAD

**Issue by Poddi** [0x90d/videoduplicatefinder#85]
skip first "xx" seconds to avoid black screens and Intros.

Saw it in other payed dupe finder apps.

PS. any updates planned in future? last Release is over a Year old

Greets

**Comment by Revan654** [comment]
> rst "xx" seconds to avoid black screens and Intros.

Always skips a small amount of time at the start.

Link: https://github.com/0x90d/videoduplicatefinder/blob/bd7041ec3e827bc730a978330d61c7b8adde786d/DuplicateFinderEngine/FFmpegWrapper/FFmpegWrapper.cs#L12

The last update was 12 days ago: https://ci.appveyor.com/project/0x90d/videoduplicatefinder/branch/master/artifacts

**Comment by smares** [comment]
Would be nice to have this configurable. Currently, I am getting lots of false positives due to intros.

**Comment by 0x90d** [comment]
And what should VDF do if you have chosen to skip first 30 seconds and a video is shorter? Right now if you choose 1 thumbnail it simply takes half of whatever the duration is. This skips all intros. If you still get false positives you can increase the thumbnail count.

**Comment by yami-no-tusbas** [comment]
Why not take percentage into account ? Like divide the 100% duration by whatever screens the user want. 1 would be the 50%, 2 will likely have to be 25% and 75%, and so on, if the use want 10 screens then all 10% do screencaps.

**Comment by 0x90d** [comment]
This is what VDF does already. I don't see any reason to implement a "skip X seconds" feature. The only useful implementation is to detect a black screen and shift the current position by +/- X percent and see if there is also a blackscreen or not. In very rare situations there can be too dark screens that only last a few (milli)seconds, like a cut or something. And if the following second is not a blacksceen its okay to use that. But that is something different than the OP asked for so I'm closing this issue.
