### ISSUE TITLE
No files are rescanned after changing number of thumbnails

### ISSUE THREAD

**Issue by belidzs** [0x90d/videoduplicatefinder#87]
**Environment**
 - OS: Windows 10

**Describe the bug**
After a scan I've changed the number of thumbnails and restarted the scan, but the files which were already scanned (although with different parameters) were not processed again

**Expected behavior**
After changing any quality-related parameter all previous results should be discarded so that the engine checks all files again with the new parameters

**Comment by Revan654** [comment]
> 
> 
> **Environment**
> 
>     * OS: Windows 10
> 
> 
> **Describe the bug**
> After a scan I've changed the number of thumbnails and restarted the scan, but the files which were already scanned (although with different parameters) were not processed again
> 
> **Expected behavior**
> After changing any quality-related parameter all previous results should be discarded so that the engine checks all files again with the new parameters

Any previous files (as long as they were error free) are not re-scanned if the parameter change. It's an oversight. Once the file has byte code it's doesn't look like that file will be rescanned. Atlease from what I can tell it's hard reading some of the source code without any line breaks.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
