### ISSUE TITLE
Store database in user profile directory

### ISSUE THREAD

**Issue by belidzs** [0x90d/videoduplicatefinder#88]
**Environment**
 - OS: Any

**Describe the solution you'd like**
`ScannedFiles.db` should be in the user's home directory instead of together with the executable files. This way the program- and data files would be separated.

I guess these directories should be `C:\Users\<user>\AppData\Roaming\VDF` in Windows and `/home/<user>/.config/vdf` in Linux or something similar.

**Comment by b1n4ryj4n** [comment]
Please don't put "ScannedFiles.db" in the user profile directory. Unless there a parameter to keep it portable.

**Comment by Revan654** [comment]
> 
> 
> Please don't put "ScannedFiles.db" in the user profile directory. Unless there a parameter to keep it portable. But it's just my opinion im a fan of keep all programs portable.

What should have been done in the first place was to allow the user to set the path for any file being used or created.

**Comment by 0x90d** [comment]
See my comment https://github.com/0x90d/videoduplicatefinder/pull/89
