### ISSUE TITLE
Application doesn't find ffmpeg.exe in PATH

### ISSUE THREAD

**Issue by belidzs** [0x90d/videoduplicatefinder#90]
**Environment**
 - OS: Windows

**Describe the bug**
Application doesn't find ffmpeg.exe in PATH, it has to be copied next to the executable.

**Expected behavior**
ffmpeg.exe should be automatically discovered when it's available in PATH

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
