### ISSUE TITLE
Suggest: Please add a "Reflesh List Button"

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#93]
**Environment**
 - OS: [e.g. Windows / Linux / Any]

**Describe the solution you'd like**

Thanks for your works.

I'm using your program as an encoded duplicates file remover, It takes a hole day because network drive has so slow speed. 

But the exact same file (size and contents) detecting is easy and takes a short time with other simple file compare program.

So after removing it, Videodupliatefinder's list would have a old list of 'do not exist'

Or other deleting works can make the same situation. 

So I Suggest add a "Reflesh List Button"

Thanks for reading. Have a nice day!

**Comment by Revan654** [comment]
> after removing it, Videodupliatefinder's list would have a old list of 'do not exist'

You can just click Clean database, it will remove non exist files and reload list as well.

The Database isn't updated or changed after each deletion from what I seen in the code.  Not 100% sure why the dev doesn't update the entries while files are being deleted.

**Comment by wowkkwow** [comment]
Hi! Thanks for reading and replying.

Is cleaning database only effective before a scanning work?


I think Reflesh result list button good for avoiding another scanning process.

( other duplicate detecting program has a similar button )

Thanks for reading.

**Comment by Revan654** [comment]
> 
> 
> Hi! Thanks for reading and replying.
> 
> Is cleaning database only effective before a scanning work?
> 
> I think Reflesh result list button good for avoiding another scanning process.
> 
> ( other duplicate detecting program has a similar button )
> 
> Thanks for reading.

It can be used or after. refresh button shouldn't been needed in the first let alone a cleaning button. It seems there still allot of work to be done with the program.
