### ISSUE TITLE
Version 2.0.7 does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by olivierchoquet** [0x90d/videoduplicatefinder#94]
**Environment**
 - Ubuntu 20.04

**Describe the bug**
Segmentation fault. No more details but after research it seems that's the problem come from Avalonia

**Expected behavior**
The executable VideoDuplicateFinderLinux work.

**Comment by mimran1980** [comment]
I updated avalonia to 0.9.12 and it is working for me on ubuntu 20.04. I have created a PR

**Comment by AccaGihu** [comment]
Same issue on Manjaro: segmentation fault.
I'm waiting on the next release.
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.8.0-2-MANJARO
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 1600 Six-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
