### ISSUE TITLE
I dont undestand how to install it???

### ISSUE THREAD

**Issue by ruloes** [0x90d/videoduplicatefinder#95]
**Environment**
 - OS: [e.g. Windows / Linux]

**Describe the bug**

**Expected behavior**

**Comment by theMARxLENin** [comment]
Yeah, there is no .exe

**Comment by theMARxLENin** [comment]
Oh, it's in /releases

**Comment by ruloes** [comment]
HELP ME PLEASE, I need check my video duplicates, there are thousands of them!!!
Thanks.

De: theMARxLENin [mailto:notifications@github.com]
Enviado el: domingo, 09 de agosto de 2020 7:47
Para: 0x90d/videoduplicatefinder <videoduplicatefinder@noreply.github.com>
CC: ruloes <raulespjim@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [0x90d/videoduplicatefinder] I dont undestand how to install it??? (#95)


Yeah, there is no .exe

**Comment by james-cook** [comment]
Go to https://github.com/0x90d/videoduplicatefinder/releases
And e.g. under **"Video Duplicate Finder 2.0.7"** click "Assets".
The exe file is in VDF.Windows-x64.zip
