### ISSUE TITLE
Show file date in duplicate list

### ISSUE THREAD

**Issue by U1496E** [0x90d/videoduplicatefinder#97]
**Environment**
 - OS: Windows / all

**Describe the solution you'd like**
At first I'd like to thank you all for this great work!
What would help a lot is to find the date and time of the files in the list,
as well as the resolution of pictures.

**Comment by 0x90d** [comment]
The resolution of images is already included, try the latest version:
![image](https://user-images.githubusercontent.com/46010672/92155671-08164080-ee28-11ea-8561-76c681222c93.png)

Filedate is a good point, this should be included...

**Comment by 0x90d** [comment]
Added with latest commit
