### ISSUE TITLE
Make it possible to select "Reference" or "Normal(default)" for directories

### ISSUE THREAD

**Issue by james-cook** [0x90d/videoduplicatefinder#98]
**Environment**
 - OS: [e.g. Windows / Linux / Any]

**Describe the solution you'd like**
In programmes like **dupeguru** you can make one or more directories "Reference" directories.

![f2](https://user-images.githubusercontent.com/2187765/90276562-6b820380-de64-11ea-8e0d-5f7845ab6264.png)

Files are compared as usual but for each compared group one file is then "pre-set" as the file which will not be deleted (by default this file has NO select box to the left).

![f1](https://user-images.githubusercontent.com/2187765/90276481-44c3cd00-de64-11ea-9a13-b445a5fcd00d.png)

The selection of this top "master" file is based on a number of configurable settings including length of file name, depth of file path etc. but also (if you select it) on whether the file is in a reference directory or not.

The advantage of this approach is that you can compare directories of films against a master directory and easily select the duplicates to be deleted. Below image shows the result of  "Mark ALL"...

![f3](https://user-images.githubusercontent.com/2187765/90276587-73da3e80-de64-11ea-8cc5-03276341b57f.png)

**Comment by frebeee** [comment]
Definitely really helpful to solve this! It sounds like two separate problems:

1. I don't want any files in Folder X to be selectable/deletable by the program
2. I want Folder X to have priority over Folder Y

For no. 1, marking as Reference works. Ashisoft calls them "Protected Folders", which is a clearer name than reference. Multiple folders can be protected from deletions by being marked, even if a dupe is present across these protected folders.

![Protected Folders](https://user-images.githubusercontent.com/50500564/103816215-ab48c200-5075-11eb-9f63-1492dcb4d74c.png)

For no. 2, prioritising the folders works much better than Reference vs Normal. For example:

1. Folder X, Y and Z all have files in.
2. Dupe 1 exists in Folder X and Y, and Dupe 2 exists in Folder Y and Z. 
3. If I mark X as a reference, it doesn't help the program decide which Dupe 2 to get rid of
4. If I also mark Y as a reference, the program can't resolve Dupe 1.

Prioritising folders in order solves this problem. VisiPics does this:

![Priority folder list](https://user-images.githubusercontent.com/50500564/103816077-776d9c80-5075-11eb-8d24-c2c9a1ddcca2.png)

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
