### ISSUE TITLE
Move files to folder - provide an option to keep existing folder structure

### ISSUE THREAD

**Issue by james-cook** [0x90d/videoduplicatefinder#99]
**Environment**
 - OS: [e.g. Windows / Linux / Any]

**Describe the solution you'd like**
The current move to files to folder option is "flat" i.e. all files in whatever directories are all moved to the single target directory. 

It would be very useful to preserve the directory structure of the source files in the target directory - particularly when you make a mistake and need to move the moved files back to their original location 

e.g. in dupeguru this is done by checking the "recreate relative path" option:
![f4](https://user-images.githubusercontent.com/2187765/90322727-16bfb500-df58-11ea-9894-ee9e617d1a57.png)

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
